microsoft/Olive

utils/onnxpipeline.py
1. function parameters usage 
2. code comments
=> add comments in onnxpipeline class

docker-images/onnx-converter/requirements.txt, utils/onnxpipeline.py, web/frontend/src/components/Convert.vue, web/frontend/src/components/JobMonitor.vue, web/frontend/src/components/PerfResult.vue
- Sort jobs in descending order in JobMonitor
- Fixed "profiling ops" rendering outside of container
=> OLive Web App UI Improvement

docker-images/perf-tuning/README.md, docker-images/perf-tuning/build_perf_tuning.py, docker-images/perf-tuning/src/perf_tuning.py
Update perf-tuning image source code to reflect changes in Python api in onnxruntime 1.0 and 1.1
- Updated code snippets to use latest python api
- Changed flag "--mkldnn" in "build_perf_tuning.py" to "--dnnl" to align with onnxruntime 1.1. 
- Updated mcr.microsoft.com/onnxruntime/perf-tuning docker image to reflect the changes above.
=> Update Perf-tuning Code Snippet to onnxruntime 1.0

docker-images/perf-tuning/README.md, web/frontend/package-lock.json, web/frontend/src/components/Perf.vue
- Add Nuphar support to OLive web app to enable user to tuning performance under Nuphar execution provider. 
- Update related doc.
=> Add Nuphar Support To Web App

utils/build.bat, web/build.bat, web/build.sh, web/frontend/package-lock.json, web/frontend/package.json, web/frontend/src/components/Perf.vue, web/readme.md, web/start-linux.sh, web/start-windows.bat, web/start-windows.sh, web/stop-windows.bat
- Add .bat files for building and running web app on Windows. 
- UI fix on the UX improvement on supporting PICKLE test data format. Disable "use previous test data" button if the previous job doesn't successfully generate test data.
=> Web Build and UI Update

docker-images/onnx-converter/src/check_model.py, docker-images/onnx-converter/src/onnx_converter.py, docker-images/perf-tuning/build_perf_tuning.py, utils/build.sh, utils/onnxpipeline.py, web/backend/app.py, web/build.sh, web/frontend/src/components/Perf.vue, web/start-linux.sh
- Update `perf-tuning` build scripts to work with ort1.2.0 changes.
- Added web app build script to work on different platforms. 
- Web app UX bug fixes.
=> Build Scripts and Web UI Updates

docker-images/onnx-converter/src/check_model.py, docker-images/perf-tuning/README.md, docker-images/perf-tuning/build_perf_tuning.py, docker-images/perf-tuning/src/maps.py, docker-images/perf-tuning/src/perf_tuning.py, web/backend/app.py, web/frontend/src/components/Perf.vue
Update mcr.microsoft.com/onnxruntime/perf-tuning docker image to consume ort 1.6
- Removes nGraph execution provider.
- Fixes #37
=> Update Docker Image to ORT1.6

README.md, docker-images/perf-tuning/Dockerfile, docker-images/perf-tuning/build_perf_tuning.py, docker-images/perf-tuning/src/perf_tuning.py
update OLive perftuning image with ort 1.8.0 and update related steps to build image
=> update OLive with ort 1.8.0

olive_images/cgmanifest.json
This pull request adds the JSON schema for `cgmanifest.json`.
A JSON schema helps you to ensure that your `cgmanifest.json` file is valid.
JSON schema validation is a build-in feature in most modern IDEs like Visual Studio and Visual Studio Code.
Most modern IDEs also provide code-completion for JSON schemas.
Most modern IDEs like Visual Studio and Visual Studio Code have a built-in feature to validate JSON files.
You can also use [this small script](https://github.com/JamieMagee/verify-cgmanifest) to validate your `cgmanifest.json` file.
Component Detection is able to read camel case and pascal case properties.
However, the JSON schema doesn't have a case-insensitive mode.
We therefore suggest camel case as it's the most common format for JSON.
To deserialize the `cgmanifest.json` file, …
=> Add `$schema` to `cgmanifest.json`

olive/optimization/tuning_process.py
=> change tuning combos

olive/constants.py
Numpy throw an error: " **AttributeError: module 'numpy' has no attribute 'bool**' "
Fixed by changed **numpy.bool** to **numpy.bool_**
=> Changed numpy bool to bool_

.azure_pipelines/package_publish.yaml, README.md, docs/source/getstarted/installation.md
=> add package publish pipeline

examples/bert_ptq_cpu/bert_config.json, examples/bert_ptq_cpu/docker/Dockerfile, examples/resnet_ptq_cpu/conda.yaml, examples/test_bert_ptq_cpu.py, examples/test_resnet_ptq_cpu.py, olive/systems/azureml/aml_system.py, olive/systems/common.py, olive/systems/docker/utils.py, olive/systems/local.py, olive/systems/olive_system.py, olive/systems/system_config.py
Reenable Azure ml test for pipeline.
=> Reenable Azure ml test

README.md, docs/architecture.md, docs/source/getstarted/installation.md, docs/source/getstarted/quickstart_bert_example.md, docs/source/getstarted/quickstart_resnet_example.md, examples/bert_ptq_cpu/README.md, examples/cifar10_openvino_intel_hw/README.md, examples/resnet_ptq_cpu/README.md, examples/snpe/inception_snpe_qualcomm_npu/README.md, examples/snpe/vgg_snpe_qualcomm_npu/README.md, olive/workflows/run/run.py
1. olive wiki: olive -> Olive
2. typos fix.
3. add comments for high-level passes template
=> olive -> Olive & typo fix & remove useless params

examples/test_bert_ptq_cpu.py, examples/test_resnet_ptq_cpu.py
Change number of samples to `3` for examples test to speed up test time.
=> Change number of samples for examples test

olive/strategy/search_results.py, olive/strategy/search_strategy.py
Best execution result doesn't meet metrics criteria. 
(test_olive_qat) leqiao@stcadmin-DGX-Station-002:~/Olive/examples/roberta$ python roberta.py
[2023-03-29 15:19:16,570] [INFO] [engine.py:266:resolve_goals] Resolving goals: {'accuracy': MetricGoal(type='percent-max-degradation', value=10.0), 'latency': MetricGoal(type='percent-min-improvement', value=20.0)}
[2023-03-29 15:19:16,571] [INFO] [engine.py:274:resolve_goals] Computing baseline for metrics ...
[2023-03-29 15:19:16,571] [INFO] [engine.py:278:resolve_goals] Baseline: {'accuracy': 0.8899999856948853, 'latency': 141.37118}
[2023-03-29 15:19:16,571] [INFO] [engine.py:295:resolve_goals] Resolved goals: {'accuracy': 0.8009999871253968, 'latency': 113.09694400000001}
objective_dict:  {'accuracy': {'higher_is_better': True, 'goal': …
=> bugfix best output for metric goal

.azure_pipelines/build-doc.yaml, .azure_pipelines/job_templates/olive-build-doc-template.yaml, .azure_pipelines/olive-ci.yaml, docs/source/api/passes.rst, olive/passes/onnx/float16_conversion.py
This PR adds a job that builds the docs to make sure it does not fail.
=> Add docs build test job to CI pipeline 

docs/source/overview/options.md, docs/source/tutorials/configure_metrics.rst, examples/bert_ptq_cpu/auto_bert_config.json, examples/bert_ptq_cpu/bert_config.json, examples/cifar10_openvino_intel_hw/config.json, examples/quantization_aware_training/bert_qat_customized_train_loop_cpu/bert_config.json, examples/quantization_aware_training/resnet_qat_default_train_loop_cpu/resnet_config.json, examples/quantization_aware_training/resnet_qat_lightning_module_cpu/resnet_config.json, examples/resnet_ptq_cpu/resnet_config.json, examples/resnet_ptq_cpu/resnet_dynamic_config.json, examples/resnet_ptq_cpu/resnet_static_config.json, olive/evaluator/metric.py, olive/evaluator/olive_evaluator.py
Add is_first_priority flag to Metric. Olive Engine run will return top K selected model based on first priority metric.
=> Add is_first_priority flag to Metric

README.md
Add information about pre-commit hooks in the README
=> Formatting info in README

olive/model.py
fix bug if user provide execution provider and doesn't provide session options
=> bug fix for inference settings

examples/directml/stable_diffusion/stable_diffusion.py
Earlier code assumed 1 footprint per pass. This change will look for the relevant footprints based on the specific pass without assuming the total number of footprints.
=> SD sample footprint fix

.azure_pipelines/job_templates/olive-build-template.yaml, .azure_pipelines/package_publish.yaml
Since package publish pipeline might be queued seperately, also add CredScan in package publish pipeline
=> add CredScan

docs/source/exts/auto_config_doc/__init__.py, docs/source/tutorials/advanced_users.md, docs/source/tutorials/configure_pass.rst, examples/snpe/inception_snpe_qualcomm_npu/inception_dev.py, examples/snpe/vgg_snpe_qualcomm_npu/vgg.py, olive/passes/olive_pass.py, olive/workflows/snpe/convertquantize/convertquantize.py, test/integ_test/aml_model_test/test_aml_model.py, test/unit_test/passes/openvino/test_openvino_conversion.py, test/unit_test/passes/openvino/test_openvino_quantization.py, test/unit_test/systems/azureml/test_aml_system.py, test/unit_test/utils.py
refactor search space generation to support device parameters
=> refactor search space generation to support device parameters

docs/source/tutorials/packaging_output_models.md, olive/packaging/packaging_generator.py, olive/packaging/sample_code/ONNXModel/cpp/README.md, olive/packaging/sample_code/ONNXModel/cs/README.md, olive/packaging/sample_code/ONNXModel/python/README.md, olive/packaging/sample_code/ONNXModel/python/requirements.txt
Add ONNXRuntime package to Zipfile packaging zip file
=> Add ONNXRuntime package to Zipfile packaging zip file

examples/bert_ptq_cpu/docker/Dockerfile, test/integ_test/evaluator/docker_eval/dockerfile/Dockerfile
restore Dockerfile deefault olive branch to main
=> restore dockerfile default olive branch

docs/source/api/models.rst
Document CompositeOnnxModel and DistributedOnnxModel
=> Document CompositeOnnxModel and DistributedOnnxModel

.azure_pipelines/job_templates/olive-build-template.yaml, .azure_pipelines/olive-ci.yaml, Makefile, examples/test_whisper.py, examples/whisper/requirements.txt, olive/engine/engine.py, scripts/test_examples.bat, scripts/test_examples.sh
Add test for whisper example and make it a CI pipeline test. 
For the timebeing, we are using custom onnxruntime packages for whisper since the nightly doesn't have the required changes yet. This will be undone in the future.
=> Add whisper test

.azure_pipelines/job_templates/olive-build-template.yaml, Makefile, examples/whisper/README.md, examples/whisper/requirements.txt, scripts/test_examples.bat, scripts/test_examples.sh
Update the whisper example with instructions to install the required packages. The CI tests are updated to use the nightly feed of ort-nightly instead of our custom packages since the nightly packages have the required changes now.
=> Update whisper requirements and readme 

docs/source/examples.md, examples/whisper/README.md
Add whisper to examples list on docs.
=> Add whisper example to docs examples list

olive/packaging/packaging_generator.py
Add nightly ort package download
=> Add nightly ort package download

examples/whisper/README.md, examples/whisper/requirements.txt
whisper example requirements updated with minimum versions for `torch` and `onnx`. README updated with instructions to create a new conda or python virtual environment.
=> Update Whisper README and requirements 

docs/source/overview/options.md, docs/source/tutorials/packaging_output_models.md, examples/bert_ptq_cpu/auto_bert_config.json, examples/bert_ptq_cpu/bert_config.json, examples/cifar10_openvino_intel_hw/config.json, examples/directml/squeezenet/squeezenet_config.json, examples/directml/stable_diffusion/config_safety_checker.json, examples/directml/stable_diffusion/config_text_encoder.json, examples/directml/stable_diffusion/config_unet.json, examples/directml/stable_diffusion/config_vae_decoder.json, examples/directml/stable_diffusion/config_vae_encoder.json, examples/resnet_ptq_cpu/resnet_config.json, examples/resnet_ptq_cpu/resnet_dynamic_config.json, examples/resnet_ptq_cpu/resnet_static_config.json, examples/super_resolution/config.json, examples/test_bert_ptq_cpu.py, examples/test_resnet_ptq_cpu.py, examples/whisper/whisper_template.json, olive/engine/engine.py, olive/workflows/run/config.py, test/integ_test/evaluator/azureml_eval/test_aml_evaluation.py, test/integ_test/evaluator/docker_eval/test_docker_evaluation.py, test/unit_test/engine/test_engine.py
=> update configs, engine

examples/whisper/README.md, examples/whisper/test_transcription.py
Add powershell commands for whisper example. Change ort log severity level to ERROR for `test_transcription.py`.
=> Update whisper readme with powershell commands, set log level in test transcription

docs/source/overview/options.md, olive/__init__.py, olive/workflows/run/config.py, olive/workflows/run/run.py
Olive logger severity config in Olive.Engine.
=> olive logger severity

examples/resnet_ptq_cpu/user_script.py, olive/evaluator/accuracy.py, olive/evaluator/evaluation.py, test/unit_test/evaluator/test_accuracy.py, test/unit_test/evaluator/test_evaluation.py
Rename Metric->evaluate() method to Metric->measure) for clarification.
=> Rename Metric->evaluate() method to Metric->measure) for clarification. 

examples/whisper/prepare_whisper_configs.py, examples/whisper/whisper_template.json, olive/engine/packaging/packaging_generator.py
Add packaging config to Whisper example.
=> Whisper: add packaging config

MANIFEST.in
include engine/packaging/sample_code directory when building wheel.
=> include sample code directory

olive/engine/packaging/sample_code/ONNXModel/cpp/code_sample.cpp, olive/engine/packaging/sample_code/ONNXModel/cs/code_sample.cs
Follow up to https://github.com/microsoft/Olive/pull/242. Update the cpp and cs example code accordingly.
=> Update cpp and cs example code `inference_settings` 

olive/engine/packaging/packaging_generator.py, test/unit_test/engine/packaging/test_packaging_generator.py
Skip packaging if no output model
=> Skip packaging if no output model

.azure_pipelines/olive-ci.yaml, examples/README.md, examples/whisper/README.md
Add a README at `examples`. It has instructions for installing olive and using examples.
=> Add a readme at `examples` 

docs/source/tutorials/advanced_users.md, examples/directml/stable_diffusion/stable_diffusion.py, examples/test_bert_ptq_cpu.py, examples/test_cifar10_openvino_intel_hw.py, examples/test_resnet_ptq_cpu.py, examples/test_whisper.py, examples/whisper/test_transcription.py, olive/engine/engine.py, olive/engine/footprint.py, olive/strategy/search_strategy.py, olive/workflows/run/run.py, test/unit_test/engine/packaging/test_packaging_generator.py, test/unit_test/engine/test_engine.py
make engine register the Pass config instead of Pass instance to support hardware accelerators
=> Refactor engine to support hardware accelerators

examples/bert_hf_cpu_aml/bert_config.json, examples/bert_hf_cpu_aml/conda.yaml, examples/bert_hf_cpu_aml/requirements.txt, examples/bert_hf_cpu_aml/user_script.py, examples/test_bert_hf_aml.py, olive/model.py, olive/systems/azureml/aml_evaluation_runner.py, olive/systems/azureml/aml_pass_runner.py
* Add support for HF AML model
* Add bert HF AML model example
=> Add support for HF AML model

examples/README.md, olive/__init__.py, olive/systems/docker/Dockerfile
=> update version number

olive/cache.py, olive/engine/engine.py, olive/engine/packaging/sample_code/ONNXModel/python/code_sample.py, olive/systems/azureml/aml_evaluation_runner.py, olive/systems/azureml/aml_pass_runner.py, olive/systems/azureml/aml_system.py, olive/systems/python_environment/available_eps.py, olive/systems/python_environment/inference_runner.py, olive/systems/python_environment/is_valid_ep.py, olive/systems/python_environment/python_environment_system.py, olive/systems/utils.py, olive/workflows/run/run.py, olive/workflows/snpe/convertquantize/convertquantize.py, olive/workflows/snpe/evaluate/evaluate.py, setup.py
explicitly close the opened files to prevent file handle leaks
=> explicitly close the opened files

docs/source/tutorials/packaging_output_models.md
Clarify that the zipfile package contains a json file with performance metrics.
=> Clarify zipfile package content

.azure_pipelines/package_publish.yaml
upload package to pipeline artifacts
=> upload package to pipeline artifacts

olive/evaluator/metric.py, olive/systems/docker/eval.py, olive/systems/docker/utils.py
Remove the MetricList which is just used to create MetricList for parsing objective.
=> Remove MetricList

examples/README.md, olive/__init__.py, olive/systems/docker/Dockerfile
Update version number to 0.2.0
=> update version number (#278)

docs/source/overview/options.md, docs/source/overview/quicktour.md, docs/source/tutorials/configure_systems.rst, test/unit_test/workflows/mock_data/only_transformer_dataset.json
=> Update aml client doc

olive/evaluator/olive_evaluator.py, olive/model.py, test/unit_test/evaluator/test_olive_evaluator.py, test/unit_test/utils.py
Support for evaluating distributed onnx models
=> Support for evaluating distributed onnx models

olive/passes/onnx/vitis_ai/qdq_quantizer.py, olive/passes/onnx/vitis_ai/refine.py
Use the correct logger in the `vitis_ai` code. It was using `logging` directly and also setting basic config which affects the root logger.
=> Use olive logger in `olive.passes.onnx.vitis_ai`

docs/source/tutorials/passes/onnx.md
add Vitis documentation in pass documentation section
=> add Vitis documentation in pass documentation section

examples/snpe/inception_snpe_qualcomm_npu/inception_eval.py
To fix the bug in API invoking which pass the wrong parameters which were deprecated already.
=> Bugfix: inception evaluation

.azure_pipelines/build-doc.yaml, .azure_pipelines/job_templates/olive-build-doc-template.yaml, docs/source/conf.py, olive/__init__.py
=> add doc versioning

examples/directml/dolly_v2/README.md, examples/directml/stable_diffusion/README.md
Guides users to `pip install olive-ai[directml]` to ensure a smooth experience with the DML samples.
=> Update DML sample README setup steps

.azure_pipelines/job_templates/olive-build-template.yaml, .azure_pipelines/olive-ci.yaml
extend component detection timeout
=> extend component detection timeout

.coveragerc
enable code coverage for aml runner
=> enable code coverage for aml runner

examples/whisper/test_transcription.py, olive/engine/engine.py, olive/passes/olive_pass.py, test/unit_test/engine/test_engine.py
Allow pass run could be reused cross different hardware
=> Allow pass run could be reused cross different hardware

olive/azureml/azureml_client.py, olive/common/utils.py, olive/engine/engine.py, olive/engine/footprint.py, olive/model.py, olive/passes/onnx/perf_tuning.py, olive/snpe/utils/input_list.py, olive/systems/azureml/aml_system.py, olive/workflows/snpe/convertquantize/convertquantize.py
=> normalize exception handling

examples/whisper/README.md, examples/whisper/requirements.txt, scripts/test_examples.bat, scripts/test_examples.sh
Change whisper dependency from ort nightly to 1.15.0 stable release.
=> Update whisper ort dependency to 1.15.0

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml, .github/pull_request_template.md
=> add issue template

olive/systems/python_environment/inference_runner.py, olive/systems/python_environment/python_environment_system.py, test/unit_test/systems/python_environment/test_python_environment_system.py, test/unit_test/utils.py
Add unit test for python environment system standalone scripts. Fix the `test_evaluate_accuracy` that was skipped.
=> Add unit tests for PythonEnvironmentSystem

olive/workflows/run/run.py, test/unit_test/workflows/test_setup.py
fix workflows setup process: install packages according to accelerators instead of device
=> fix workflows setup

olive/data/component/dataloader.py, olive/data/component/dataset.py, olive/data/component/load_dataset.py, olive/data/component/pre_process_data.py, olive/data/config.py, olive/data/container/__init__.py, olive/data/container/data_container.py, olive/data/container/dummy_data_container.py, olive/data/template.py, olive/evaluator/olive_evaluator.py, olive/model.py, test/unit_test/data_container/test_template.py
=> Simplify the dummy dataloader

olive/engine/engine.py, test/integ_test/aml_model_test/conda.yaml, test/integ_test/aml_model_test/test_aml_model.py, test/integ_test/aml_resource_path/test_aml_resource_path.py, test/integ_test/evaluator/azureml_eval/conda.yaml, test/integ_test/evaluator/azureml_eval/utils.py, test/integ_test/evaluator/docker_eval/utils.py, test/integ_test/evaluator/local_eval/utils.py, test/integ_test/utils.py
=> 🐝 Remove ort version dependency and refine integration test utils

docs/source/tutorials/how_to_write_userscript.md
=> Fix doc typo

test/unit_test/workflows/mock_data/user_script.json, test/unit_test/workflows/test_run_config.py
=> add unit test for azureml_client config

requirements.txt
Remove numpy version constrain
=> Remove numpy version constrain

docs/source/overview/options.md, docs/source/overview/quicktour.md
=> Rewrite Quick Tour

olive/common/config_utils.py, olive/engine/engine.py, olive/passes/olive_pass.py, olive/systems/azureml/aml_system.py
=> Fix check_object bug

docs/source/examples.md, examples/resnet/README.md
=> update Vitis examples readme and doc

docs/source/api/systems.rst, docs/source/overview/options.md, docs/source/overview/quicktour.md, docs/source/tutorials/advanced_users.md, docs/source/tutorials/configure_metrics.rst, docs/source/tutorials/configure_systems.rst, examples/directml/squeezenet/squeezenet_config.json, examples/mobilenet_qnn_qualcomm_npu/mobilenet_config_template.json, examples/snpe/inception_snpe_qualcomm_npu/inception_eval.py
- Remove outdated changes.
- Wiki formatting fix
=> 📝 Update wiki/example use case on system accelerators

examples/test/test_bert_ptq_cpu.py, olive/systems/docker/docker_system.py
=> Add docker system test back

olive/model/model_config.py
=> Add missing copyright header

olive/snpe/configure.py
This change is based on the new SNPE sdks > v2.10 that have declared the folder from vc19 to msvc
=> update target arch for new snpe version from vc19 to msvc

olive/snpe/configure.py, olive/snpe/utils/local.py
This is a follow up to https://github.com/microsoft/Olive/pull/344. Bringing the changes to `main` while also maintaining support for older versions of SNPE.
=> Support snpe arm64-win arch names for new versions

olive/workflows/run/config.py
=> cleanup deadcode

.azure_pipelines/package_publish.yaml
remove release to pypi part from build pipline, since the release task has been onboarded to ESRP
=> remove release task

examples/bert/conda.yaml, examples/bert/docker/Dockerfile, olive/engine/engine.py, olive/engine/footprint.py, olive/model/hf_utils.py, olive/passes/onnx/common.py, olive/resource_path.py, test/unit_test/engine/test_engine.py
Normalize ValueError exception handling. Most of time, user errors need not be caught. So, the engine run need explicitly ignore it.
=> rethrown critical ValueError, AttributeError and TypeError

docs/source/api/evaluator.rst, docs/source/api/metric.rst, docs/source/api/models.rst, docs/source/api/passes.rst, docs/source/api/resource_path.rst, docs/source/api/search-algorithms.rst, docs/source/api/systems.rst, docs/source/conf.py, docs/source/overview/options.md, olive/systems/system_alias.py, olive/systems/system_config.py, test/unit_test/workflows/mock_data/readymade_system.json, test/unit_test/workflows/test_run_config.py
Make Olive has the support of readymade system by using SystemAlias
Fix doc build warnings
=> Let Olive has the ability to support readymade system

olive/systems/docker/utils.py
I added changes to utils.py to determine the correct model path based on some conditions and generates the right path to where it should be mounted to in a container.
=> Fixed ONNX-external data on docker system

docs/source/api/systems.rst, docs/source/tutorials/configure_systems.rst
add readymade system configure document
=> add readymade system configure document

.azure_pipelines/job_templates/olive-build-doc-template.yaml, docs/README.md, docs/source/conf.py, docs/source/tutorials/advanced_users.md, docs/source/tutorials/configure_metrics.rst, docs/source/tutorials/configure_systems.rst, docs/source/tutorials/passes/onnx.md, docs/source/tutorials/passes/pytorch.md, olive/passes/pytorch/quantization_aware_training.py
=> enable linkcheck in doc build

examples/directml/stable_diffusion/requirements.txt, examples/directml/stable_diffusion/stable_diffusion.py
Replace PySimpleGUI with tkinter to avoid complaints from component governance. Tkinter comes out of the box with Python installations on Windows, and it falls under the permissive Python License.
=> Switch SD sample to tkinter to address CG alerts

test/unit_test/data_container/test_template.py, test/unit_test/engine/test_engine.py, test/unit_test/evaluator/test_metric_backend.py
=> 🐞Fix Unit test Patch 

docs/source/overview/options.md, olive/azureml/azureml_client.py, test/unit_test/workflows/test_run_config.py
Expose params of DefaultAzureCredential. Then customer can disable unrequired credential getting ways.
=> 📤Expose params of DefaultAzureCredential

examples/open_llama/open_llama_config_cuda.json, examples/open_llama/user_script.py
=> 📦User_scripts and gpu config for llama

olive/evaluator/accuracy.py, olive/evaluator/metric_backend.py, olive/evaluator/olive_evaluator.py, olive/passes/olive_pass.py, olive/resource_path.py, olive/strategy/search_algorithm/search_algorithm.py
=> fix type hints for registry

examples/open_llama/README.md
=> Fix README title

docs/source/overview/options.md
Comment broken link for huggingface datasets that stopped working today. It is blocking other PRs because of link check in dock build test. Will be reverted when the link comes back online.
=> Docs: Comment out broken link

olive/common/ort_inference.py
JSON cannot persist the Tuple for python. 
It will cause that the load_model cannot load the correct execution providers.
=> 🐞Fix the execution_provider load issue

olive/data/component/dataset.py, olive/model/hf_utils.py, olive/model/model_config.py, olive/passes/onnx/inc_quantization.py, olive/passes/openvino/quantization.py, olive/passes/snpe/conversion.py
=> 🔠Typos fix

olive/data/component/dataset.py, olive/data/component/load_dataset.py, olive/data/template.py
=> 🏑Unify the parameters order and default value of dummy dataset

examples/bert/docker/Dockerfile, test/integ_test/evaluator/docker_eval/dockerfile/Dockerfile
Follow up to https://github.com/microsoft/Olive/pull/392. This requirement is not needed anymore since the requirement is already in the main branch.
=> Remove pydantic version requirement from dockerfiles

docs/source/api/systems.rst, docs/source/overview/options.md, docs/source/tutorials/configure_systems.rst
=> 🔗 Fix ambiguous ref

olive/engine/packaging/packaging_generator.py
=> Fix metric output bug

olive/data/component/post_process_data.py, olive/data/component/pre_process_data.py, olive/data/container/huggingface_container.py, test/requirements-test.txt, test/unit_test/workflows/mock_data/ner_task_dataset.json, test/unit_test/workflows/test_run_config.py
1. Add support to NER task dataset.
2. Attach the test config file for NER model
=> 🤗NER task support in Huggingface dataset

docs/source/overview/options.md, docs/source/tutorials/advanced_users.md, examples/bert/user_script.py, examples/cifar10_openvino_intel_hw/user_script.py, examples/directml/dolly_v2/user_script.py, examples/directml/squeezenet/user_script.py, examples/directml/stable_diffusion/user_script.py, examples/mobilenet_qnn_qualcomm_npu/user_script.py, examples/open_llama/user_script.py, examples/resnet/user_script.py, examples/whisper/code/user_script.py, olive/evaluator/olive_evaluator.py, olive/systems/python_environment/python_environment_system.py, test/integ_test/evaluator/azureml_eval/user_script.py, test/integ_test/evaluator/docker_eval/user_script.py, test/integ_test/evaluator/local_eval/utils.py, test/unit_test/passes/inc/test_inc_quantization.py, test/unit_test/passes/openvino/test_openvino_quantization.py, test/unit_test/passes/vitis_ai/test_vitis_ai_quantization.py, test/unit_test/utils.py
add positional and keyword arguments for dataloader_func so that user have the choice to decide how to load data
=> add positional and keyword arguments for dataloader_func

docs/source/tutorials/configure_metrics.rst, examples/resnet/user_script.py, olive/evaluator/metric_config.py, olive/evaluator/olive_evaluator.py, olive/systems/python_environment/python_environment_system.py, test/unit_test/assets/user_script.py, test/unit_test/evaluator/test_olive_evaluator.py, test/unit_test/systems/test_local.py, test/unit_test/utils.py
1. Added `metric_func` config to custom metric. Olive will run the inference for custom eval func for user. User doesn't need to do inference by themselves.
2. Updated and fixed evaluator unit tests.
=> Updated custom metric logic

docs/source/tutorials/huggingface_model_optimization.md, examples/whisper/README.md, examples/whisper/code/user_script.py, examples/whisper/prepare_whisper_configs.py, examples/whisper/whisper_template.json, olive/model/__init__.py
Add model_name arg to whisper example
=> Add model_name arg to whisper example

examples/open_llama/README.md, examples/open_llama/user_script.py
Update Llama docs to tell the different optimization config for various model size.
=> 📝 Update LLaMa docs

.azure_pipelines/job_templates/olive-build-doc-template.yaml, .azure_pipelines/job_templates/olive-build-template.yaml, .azure_pipelines/olive-ci.yaml, Makefile, examples/bert/README.md, examples/bert/conda.yaml, examples/bert/conda_gpu.yaml, examples/bert/requirements-gpu.txt, examples/bert/requirements.txt, scripts/test_examples.bat, scripts/test_examples.sh
1. Remove ort re-installation for GPU case
2. typos fix
3. Remove skipped ci tests
=> 🎦 CI: Remove ort re-installation

docs/source/overview/options.md, olive/engine/engine.py
Update outdated annotations for engine run.
=> 🆙 Update outdated annotations for engine run

.azure_pipelines/job_templates/olive-build-template.yaml, .azure_pipelines/job_templates/olive-test-template.yaml, Makefile, scripts/test.bat, scripts/test.sh, test/unit_test/data_container/test_template.py, test/unit_test/model/test_hf_utils.py, test/unit_test/model/test_pytorch_model.py, test/unit_test/utils.py
1. split ut and integration test.
2. reduce the huggingface cached model numbers
=> ➖ Reduce pipeline disk usage per agent

test/unit_test/workflows/test_run_config.py
Split AML credentials test cases
=> ♠️ Split AML credentials test cases

olive/passes/utils/whisper_prepost.py
Based on https://github.com/microsoft/onnxruntime-extensions/pull/496, this PR uses `quick_merge` to merge the pre, core and post models instead of `onnx.compose.merge_models` which fails when the models being merged are large (>2GB). The failure is because `onnx.compose.merge_models` calls `onnx.checker.check_model` internally on a large modelproto. 
Also perfom model check on the saved file path instead of the loaded model to avoid the same issue in Olive.
=> Whisper: use quick merge in prepost to support large models 

olive/passes/onnx/conversion.py, test/unit_test/passes/onnx/test_conversion.py
Add support for onnx dynamo export
=> Add support for onnx dynamo export

examples/bert/requirements.txt, examples/directml/dolly_v2/config_dolly_v2.json, examples/resnet/requirements.txt, olive/passes/olive_pass.py, olive/passes/onnx/inc_quantization.py, olive/passes/onnx/optimum_merging.py, olive/passes/onnx/perf_tuning.py, olive/passes/onnx/vitis_ai_quantization.py, test/requirements-test.txt, test/unit_test/passes/test_pass_serialization.py
Remove EP config from OptimumMerge and leverage the accelerators info from accelerator_spec.
=> 🤗 Remove EP dependencies from OptimumMerge

test/unit_test/hardare/test_accelerator.py
Accelerator assert fix with ordered results.
=> 🉑 Accelerator assert fix

olive/passes/onnx/inc_quantization.py, olive/passes/onnx/optimum_merging.py, olive/passes/onnx/perf_tuning.py
Set Accelerator agnostic as False for passes need accelerators
=> 🧆 Set Accelerator agnostic as False for passes need accelerators

scripts/install_olive.bat, scripts/install_olive.sh
CI pipelines have recently started hanging during pip dependency resolution. This PR upgrades the version of pip being used in the pipelines to use the latest dependency resolver. In test pipeline runs, I am not seeing the hanging anymore.
=> Upgrade pip in CI pipeline 

.azure_pipelines/olive-ci.yaml, examples/test/test_bert_ptq_cpu.py, examples/test/test_bert_ptq_cpu_docker.py, examples/test/utils.py
Separate docker test case to avoid hanging on CI pipeline. 
Same as #468 + additional commit to keep aml_system in test. Creating new PR since Jiapeng is unavailable to update the original PR.
=> Separate docker test case

examples/bert/docker/Dockerfile
=> disable the pip cache when building docker images

olive/passes/onnx/quantization.py
Few fixes for Quantization logic
* Cleanup temp directories
* Force external data for preprocessing i.e. set _save_as_external_data_ to True
* Argument passed to _quant_preprocess was a Path object and was being forwarded to onnxruntime.save_model which when combined with _save_as_external_data_ fails to resolve to the correct path. External data end up being written to the current folder instead of putting it right next to the model file itself.
=> Few fixes for Quantization logic

olive/passes/onnx/perf_tuning.py
`logging.error` -> `logger.error`.
=> Fix perf tuning logger

docs/architecture.md, docs/source/index.rst, docs/source/overview/options.md, olive/engine/engine.py
Fix document generation issues.
=> Fix document issues

olive/evaluator/olive_evaluator.py, olive/passes/pytorch/sparsegpt.py, olive/passes/pytorch/sparsegpt_utils.py
Add support for `GPTNeoX` (Dolly architecture) and `Bloom` to `SparseGPT` pass.
=> Add `GPTNeoX` and `Bloom` support to `SparseGPT` pass

docs/architecture.md, docs/source/api/passes.rst, olive/passes/onnx/__init__.py, olive/passes/onnx/conversion.py
=> Add Gpu conversion for onnx

examples/red_pajama/README.md, examples/red_pajama/config.json, examples/red_pajama/requirements.txt, examples/red_pajama/user_script.py
Adding support for Red Pajama model
- [ x] Update documents if necessary.
- [ x] Format your code by running `pre-commit run --all-files`
- [ x] Is this a user-facing change? If yes, give a description of this change to be included in the release notes.
=> Adding support for Red Pajama model

olive/evaluator/olive_evaluator.py
CUDA calls are asynchronous so using cpu timers like `time.perf_counter` is not always correct (unless there are parts of the forward pass that causes the GPU to synchronize before returning). It measures the time taken to make the cuda kernal calls and not the entire execution time. 
We use `torch.cuda.synchronize` after the forward call to wait for all kernels to execute. Also use `torch.cuda.Event` to mark start and end points for the forward pass. 
Refer to https://deci.ai/blog/measure-inference-time-deep-neural-networks/ for more details.
=> Synchronize GPU and use cuda events for pytorch GPU latency

.azure_pipelines/olive-ci.yaml, examples/bert/bert_ptq_cpu_aml.json, examples/test/test_bert_ptq_cpu.py, examples/test/test_bert_ptq_cpu_aml.py, examples/test/utils.py
1. Centralize bert CPU e2e aml tests to reduce confusion.
2. Re-order the ci job by model type.
=> 🟢 Centralize bert CPU e2e aml tests

olive/passes/onnx/inc_quantization.py
=> Fix inc quantization pass bug

olive/engine/engine.py, olive/workflows/run/config.py, olive/workflows/run/run.py, test/unit_test/engine/test_engine.py
Make pass list optional in config. If no pass provided, Olive will only evaluate input model.
=> Make pass list optional in config

docs/requirements.txt, examples/resnet/requirements.txt, olive/extra_dependencies.json, olive/resource_path.py, test/requirements-test.txt
Pin azureml-fsspec to unblock our ci pipeline.
=> ⚒️ Pin fsspec version

.azure_pipelines/build-doc.yaml, docs/source/_static/js/custom_version.js, docs/source/conf.py
Select package version in olive docs with customized JS scripts.
=> 🔗 Select package version in olive docs

.azure_pipelines/build-doc.yaml
Doc version fix for new release package.
=> 🏑 Doc version fix

docs/requirements.txt, examples/resnet/requirements.txt, olive/extra_dependencies.json, olive/resource_path.py, olive/systems/docker/Dockerfile, test/integ_test/aml_model_test/conda.yaml, test/integ_test/evaluator/azureml_eval/conda.yaml, test/requirements-test.txt
1. This reverts commit 9fd6df37297b95bae53bfa36d7ec66396e006ddf. As the bug is fix in azureml-dataprep 4.12.1
https://pypi.org/project/azureml-dataprep/4.12.1/
2. Remove azureml-defaults to avoid the hanging on aml env building.
=> ↩️ Revert "Pin fsspec version (#497)"

examples/bert/bert_inc_dynamic_ptq_cpu.json, examples/bert/bert_inc_ptq_cpu.json, examples/bert/bert_inc_smoothquant_ptq_cpu.json, examples/bert/bert_inc_static_ptq_cpu.json, examples/bert/bert_qat_customized_train_loop_cpu.json, olive/passes/onnx/transformer_optimization.py, olive/workflows/run/run.py, test/unit_test/workflows/mock_data/transformer_dataset.json
1. Should provide num_heads/hidden_size when opt_level == 0 and only_onnxruntime is False
as this issue https://github.com/microsoft/onnxruntime/issues/17254
2. disable search for inc example.
=> 🎊 Should provide num_heads/hidden_size when opt_level == 0 and only_onnxruntime is False

olive/engine/packaging/sample_code/ONNXModel/cs/code_sample.cs
This is a fix for c# example code. We will improve our example code part later with a runnable test.
=> Update cs example code

olive/data/component/text_generation.py
Batch tokenization for `line_by_line` corpus strategy. This can be helpful if the dataset is large and the tokenizer has an optimized batched tokenization. 
BOS and EOS tokens are added manually since some tokenizers (like llama tokenizer) don't add eos tokens. 
Refer to https://github.com/huggingface/transformers/issues/22794 for some background
=> Batched tokenization for line-by-line. Manual special tokens for line-by-line, line-by-line-random

examples/bert/bert_cuda_gpu.json, examples/bert/conda.yaml, examples/bert/conda_gpu.yaml, examples/bert/requirements.txt, examples/cifar10_openvino_intel_hw/requirements.txt, examples/resnet/conda.yaml, examples/resnet/requirements.txt, examples/snpe/inception_snpe_qualcomm_npu/requirements.txt, examples/whisper/requirements.txt, olive/engine/engine.py, olive/engine/footprint.py, olive/evaluator/metric.py, requirements.txt, test/requirements-test.txt
Summarize pass run history to one table which will be print in regular output and stored in output_dir/run_shistory_{eps}.txt
=> 🏉 Summarize pass run history

test/unit_test/common/test_import_lib.py, test/unit_test/systems/docker/test_docker_system.py, test/unit_test/systems/test_local.py
This PR is to fix https://dev.azure.com/aiinfra/Model%20optimization%20Toolkit/_workitems/edit/18983#
=> fix called_once_with by using assert_called_once_with

test/unit_test/evaluator/test_accuracy.py, test/unit_test/test_data_root.py
This PR is to fix https://dev.azure.com/aiinfra/Model%20optimization%20Toolkit/_workitems/edit/18983#
=> 🐛 Fix test accuracy to use assert_any_call

docs/source/features/model_transformations_and_optimizations.rst
Add transformations pass section overview.
=> Add transformations pass section overview.

olive/passes/onnx/optimum_conversion.py, test/requirements-test.txt, test/unit_test/passes/onnx/test_optimum_conversion.py, test/unit_test/utils.py
Bugfix for optimum conversion:
1. if we give the model name in hf_config, optimum do not work then.
2. path joint bug
=> 🐞 Bugfix for optimum conversion

olive/systems/docker/docker_system.py, olive/systems/docker/eval.py, olive/systems/docker/utils.py, test/unit_test/systems/docker/test_docker_system.py
=> add hardware accelerator for docker

examples/open_llama/user_script.py
Align the latency input, add kv_cache for torch model as well.
=> ⚗️ Align model input for latency measurement

docs/source/api/passes.rst, docs/source/conf.py, docs/source/features/passes/pytorch.md, examples/open_llama/README.md, examples/open_llama/llama_qlora.json, examples/open_llama/requirements-qlora.txt, examples/open_llama/requirements-sparsegpt.txt, olive/common/utils.py, olive/data/component/text_generation.py, olive/model/__init__.py, olive/model/hf_mappings.py, olive/model/hf_utils.py, olive/passes/pytorch/__init__.py, olive/passes/pytorch/qlora.py, test/requirements-test.txt, test/unit_test/passes/pytorch/test_qlora.py
Add QloRA pass which performs the fine-tuning approach proposed in https://arxiv.org/abs/2305.14314. Based on the original code at https://github.com/artidoro/qlora/blob/main/qlora.py. 
Added examples, test and docs.
Also ordered the test requirements in alphabetical order. 
Add `QLoRA` pass for fine-tuning language models using the method proposed in https://arxiv.org/abs/2305.14314.
=> Add `QLoRA` pass 

.pre-commit-config.yaml, examples/bert/requirements.txt, examples/directml/dolly_v2/requirements.txt, examples/directml/stable_diffusion/requirements.txt, examples/directml/stable_diffusion_xl/requirements.txt, examples/gptj/requirements.txt, examples/red_pajama/requirements.txt, examples/whisper/requirements.txt, requirements.txt, test/requirements-test.txt
Requirements-txt-fixer for pre-commit to sort the package under requirements-(.*).txt
=> 🐇 Requirements-txt-fixer for pre-commit

examples/test/utils.py
Remove gpu example base image tag.
=> Remove gpu example base image tag

olive/model/__init__.py, olive/passes/olive_pass.py, olive/passes/onnx/conversion.py, olive/passes/onnx/insert_beam_search.py, olive/passes/onnx/optimum_conversion.py, olive/passes/onnx/transformer_optimization.py, olive/passes/pytorch/sparsegpt.py, olive/passes/pytorch/torch_trt_conversion.py, olive/systems/azureml/aml_pass_runner.py, test/unit_test/model/test_pytorch_model.py, test/unit_test/passes/onnx/test_insert_beam_search.py
1. introduce a new field for Olive Model: `model_attributes`
- derived `model_attributes` from`hf_config` if there is `hf_config`
- olive passes will inherit `model_attributes` from input_model. (`model.set_model_attributes(input_model.model_attributes)`)
2. remove hf_config from onnx related model
=> Ⓜ️ Model Attributes

olive/systems/azureml/aml_system.py, olive/systems/system_config.py, test/unit_test/systems/azureml/test_aml_system.py
=> Add vc support

olive/data/component/post_process_data.py, olive/data/container/huggingface_container.py
Typo fix;
text_generatation_post_process  -> text_generation_post_process
=> 🗄️ Typos fix for text_generation_post_process

examples/open_llama/open_llama_config.json
=> Update openllama config

docs/source/features/packaging_output_models.md, olive/engine/packaging/packaging_config.py, olive/engine/packaging/packaging_generator.py, test/unit_test/engine/packaging/test_packaging_generator.py
Add packaging mlflow model option. This PR is a follow up RP for https://github.com/microsoft/Olive/pull/300 as there is no package conflict now.
=> Add packaging mlflow model option.

olive/model/__init__.py, olive/passes/olive_pass.py, test/unit_test/model/test_pytorch_model.py
Fetch hf_config for model_attributes initialization in OliveModel
=> 📟 Fetch hf_config for model_attributes initialization in OliveModel

test/unit_test/engine/packaging/test_packaging_generator.py
PR https://github.com/microsoft/Olive/pull/564 forget to merge main branch changes before merging.
=> fix test failure caused by not merge the main branch code after approval

.azure_pipelines/olive-ci.yaml, examples/resnet/resnet_qat_default_train_loop_cpu.json, examples/resnet/resnet_qat_lightning_module_cpu.json, examples/resnet/user_script.py, examples/test/test_resnet_qat.py, examples/test/utils.py
=> enable test for qat

examples/resnet/README.md, examples/resnet/multiple_ep_requirements.txt, examples/resnet/prepare_model_data.py, examples/resnet/resnet_multiple_ep.json
add example for multiple ep : OpenVINO and DML
=> add multiple ep example

docs/source/index.rst, docs/source/tutorials/configure_data.rst
Docs for data_config settings: how to configure data
=> 📄 Docs for data_config settings

examples/test/test_bert_ptq_cpu_aml.py, olive/engine/engine.py, olive/hardware/accelerator.py, olive/systems/local.py, test/unit_test/engine/test_engine.py
Only get available EP in local and python environment. For AzureML and docker we need let user specify them
=> normalize get available EPs behavior

olive/engine/engine.py, olive/hardware/accelerator.py
Add logs during accelerator spec resolution for debugging.
=> Logs for accelerator spec resolution

test/unit_test/engine/test_engine.py, test/unit_test/utils.py, test/unit_test/workflows/test_run_config.py
Unit tests for same pass with different config in one olive config. To cover this case  https://github.com/microsoft/Olive/issues/573
=> 🍵 Unit tests for same pass with different config in one olive config

README.md, docs/source/getstarted/installation.md
Add status badges for the pipelines so devs can see the most recent status for the pipelines easily. 
Update the docs for olive extras.
=> README: add status badges, update extras docs

.azure_pipelines/job_templates/olive-performance-template.yaml
=> fix perf benchmark ci pipeline synax error

examples/switch/config.json, olive/model/__init__.py, olive/passes/onnx/moe_experts_distributor.py, olive/resource_path.py
Few fixes to get MoE experts distribution to work after recent changes to Olive
=> Few fixes to get MoE experts distribution to work after recent changes to Olive

.azure_pipelines/job_templates/olive-test-template.yaml
Linux multi ep test failed due to no space left on device. Remove docker clean step conditions to clean docker before running the test,
=> clean docker

olive/hardware/accelerator.py
Add rocm ep support. No documentation updated in this PR. Will sync with Mike with a new unified accelerator documentation later.
=> Add rocm ep support

docs/source/features/azureml_integration.md, docs/source/tutorials/configure_model_path.md, examples/deberta/azureml_registry_config.json, olive/azureml/azureml_client.py, olive/model/__init__.py, olive/model/hf_utils.py, olive/resource_path.py, olive/systems/azureml/aml_system.py
Add AML curated model support.
=> Add AML curated model support

olive/systems/docker/docker_system.py, test/integ_test/evaluator/docker_eval/dockerfile/Dockerfile, test/unit_test/systems/docker/test_docker_system.py
* add docker build log
* Don't install cuda stuff to save disk space
=> try to add docker build log

test/requirements-test.txt
pin azureml-metrics to avoid the backtracking
=> pin azureml-metrics to avoid the backtracking

test/requirements-test.txt
Add mlflow to requirements-test.
=> Add mlflow to requirements-test

docs/source/features/passes/onnx.md, olive/passes/onnx/model_optimizer.py, test/unit_test/passes/onnx/test_model_optimizer.py
Two new model optimizations
* On GPU, ArgMax supports a limited input types. To make the model
usuable for inferencing, insert a Cast operator ahead of the
ArgMax.
* Fuse consecutive Reshape operations when the latter results in
flatten-ing the inputs i.e. the shaping input is "[-1]".
=> Two new model optimizations

examples/switch/config.json, examples/switch/inference.py, olive/passes/onnx/moe_experts_distributor.py
Reorganize MoE experts distribution logic to support multiple strategies.
Also, generate ranked models parallelly to improve performance.
=> Reorganize MoE experts distribution logic to support multiple strategies.

.github/workflows/lint.yml, examples/bert/bert_ptq_cpu.json, olive/engine/engine.py, olive/engine/footprint.py, requirements-dev.txt, test/unit_test/engine/mock_data/footprints.json, test/unit_test/engine/test_engine.py
- Fix `if_goals_met` logic bug when `cmp_direction == -1`. 
- Fix grammar error.
- Add `lintrunner` and `lintrunner-adapters` to dev requirements.
=> Fix footprint metric goal bug

examples/bert/docker/Dockerfile, olive/systems/docker/Dockerfile, olive/systems/docker/Dockerfile.gpu, olive/systems/docker/Dockerfile.openvino, test/integ_test/evaluator/docker_eval/dockerfile/Dockerfile
Similar with this issue:
https://github.com/actions/runner-images/issues/2904
=> 🉑 ACCEPT_EULA=Y for docker CI bug fix

olive/passes/onnx/vitis_ai_quantization.py
Follow up to https://github.com/microsoft/Olive/pull/639 that missed this pass.
=> Fix `quant_preprocess` import in VitisAI Quantization pass 

docs/source/conf.py
Docs build failed with broken link from qualcomm. This pr is used to disable link check for qualcomm
=> 👁️‍🗨️ Disable qualcomm linkcheck

examples/cifar10_openvino_intel_hw/cifar10.py, examples/test/utils.py, examples/whisper/test_transcription.py, olive/data/component/dataset.py, olive/data/component/text_generation.py, olive/engine/engine.py, olive/snpe/tools/dev.py, olive/strategy/search_parameter.py, olive/systems/docker/docker_system.py, pyproject.toml, test/integ_test/aml_resource_path/test_aml_resource_path.py, test/multiple_ep/test_aml_system.py, test/multiple_ep/test_docker_system.py, test/multiple_ep/test_python_env_system.py, test/unit_test/engine/packaging/test_packaging_generator.py, test/unit_test/engine/test_engine.py, test/unit_test/model/test_pytorch_model.py, test/unit_test/passes/common/test_user_script.py, test/unit_test/resource_path/test_resource_path.py, test/unit_test/systems/azureml/test_aml_system.py, test/unit_test/systems/docker/test_docker_system.py, test/unit_test/workflows/test_run_config.py
=> fix some pylint issues

olive/passes/onnx/quantization.py
=> 😶‍🌫️ Quick fix for 4bit quantization

olive/passes/onnx/common.py, test/unit_test/passes/onnx/test_model_optimizer.py
Expose all options for onnx model saving.
=> Export `size_threshold` and `convert_attribute` in onnx `external_data_config`

docs/source/api/passes.rst, docs/source/features/passes/pytorch.md
=> Add docs for `LoRA` pass

docs/source/conf.py
Doc build fails for the intel openvino overview link. Website is still present by we get `403 Client Error: Forbidden for url`
=> Disable intel openvino linkcheck

examples/resnet/conda.yaml, examples/resnet/requirements.txt
=> add missed packages causing perftuning failure in resnet example

olive/cache.py, olive/evaluator/olive_evaluator.py, olive/model/__init__.py, olive/passes/olive_pass.py, olive/passes/onnx/moe_experts_distributor.py, olive/resource_path.py, test/unit_test/evaluator/test_olive_evaluator.py
Copy DistributedOnnxModel generated models to output folder.
Also, in the case of large models, copy data files to the output folder.
=> Copy DistributedOnnxModel generated models to output folder

examples/llama2/.gitignore, examples/llama2/llama2.py, examples/llama2/llama2_template.json, examples/llama2/user_script.py
- Update description for `--use_gqa` and make it only valid for `gpu`.
- Add `--tempdir` option to specify custom tempdir root. Useful when the default tempdir root is out of space.
- Version check for `onnxruntime>=1.16.2`
- Remove unused components from the generated configs to avoid confusion
- The above also corrected an issue where the cpu config still used `gqa_evaluator` for some passes. 
- Generated user_scripts are suffixed with `model_name` so that input model cache can be reused between runs. 
- Removed unused functions for legacy `decoder` and `decoder_with_past` models. 
- Made a general `get_merged_sample_with_past_kv_inputs` function that can be used to create dummy inputs for both legacy models and the new "merged" model. The comments describe all possible use cases if …
=> [LlaMA2] Clean up and update scripts

.github/pull_request_template.md
Update the PR checklist to reference `lintrunner` over pre-commit.
=> Mention `lintrunner` in the PR checklist

examples/falcon/README.md, examples/falcon/config.json, examples/falcon/requirements.txt, examples/gptj/requirements.txt
=> Add Falcon example

examples/falcon/config.json, olive/model/hf_utils.py
Add trust_remote_code arg. 
Note: even with this change, I can still get a prompt asking about trusting the custom code or not. Need more investigation about this.
=> add trust_remote_code arg

docs/source/api/models.rst, docs/source/overview/quicktour.md, examples/llama2/requirements.txt
This pull request includes changes to documentation and dependencies. The most important changes include adding instructions on how to use different device ids for cuda device when accelerating a model
Documentation improvements:
* <a href="diffhunk://#diff-736499d7edcbed94b815d0573996a9542c17bfa65da3b2190b1e94f5e1d68204R36-R50">`docs/source/overview/quicktour.md`</a>: Added instructions on how to use different device ids for cuda device when accelerating a model.
* <a href="diffhunk://#diff-6640c32cc3fc866366ea7c60fe57f200e5be18f0e79b2770305d6ec07c69fbf7L44-R44">`docs/source/api/models.rst`</a>: fix docs warnings.
Dependency updates:
* <a href="diffhunk://#diff-b5a086c343c80487164b3956be3f9f944c2d272c37c0aab91d7da05f0969dde3R1-R6">`examples/llama2/requirements.txt`</a>: sort the package …
=> 🇨🇺 Docs for cuda device selection

examples/llama2/README.md
This pull request to the Llama2 example includes updates to the installation command and the addition of a performance comparison table in the README file. The changes aim to improve the installation process and provide useful information for benchmarking the Llama2 model.
* <a href="diffhunk://#diff-8a8abbc64b2dfecf3b744a2e1c122a549b9367910f00b9b2958c9d7929c15881L40-R45">`examples/llama2/README.md`</a>: Updated the installation command and added a performance comparison table to the README file. <a href="diffhunk://#diff-8a8abbc64b2dfecf3b744a2e1c122a549b9367910f00b9b2958c9d7929c15881L40-R45">[1]</a> <a href="diffhunk://#diff-8a8abbc64b2dfecf3b744a2e1c122a549b9367910f00b9b2958c9d7929c15881R85-L87">[2]</a>
=> [Llama2] Performance comparison

examples/directml/llama_v2/requirements.txt
=> Remove --extra-index-url from DirectML's Llama sample

examples/llama2/README.md, examples/llama2/llama2_template.json, examples/llama2/user_script.py
Added latency for token generation and made the names of the latencies clearer. Added values for A100. 
Need to update the values for CPU and V100 later.
=> [Llama2] Latencies for both prompt and token generation

examples/llama2/README.md
Revert llama2 benchmark numbers
=> ◀️ Revert llama2 benchmark numbers

docs/source/api/models.rst, docs/source/overview/options.md, docs/source/overview/quicktour.md, examples/directml/phi/requirements.txt
Update docs for input model configs. Details from this issue: https://github.com/microsoft/Olive/issues/686
=> 📜 Update docs for input model configs

docs/source/api/models.rst, docs/source/overview/options.md, examples/llama2/requirements.txt, olive/engine/engine.py, olive/workflows/run/config.py, test/unit_test/engine/test_engine.py, test/unit_test/workflows/mock_data/default_engine.json, test/unit_test/workflows/test_run_config.py
Make engine optional to simplify the default user config
=> 📶 Make engine optional to simplify the default user config

olive/__init__.py
=> Bump version to 0.5.0

examples/directml/llama_v2/llama_v2.py, examples/directml/llama_v2/requirements.txt, examples/directml/llama_v2/run_llama_v2_dynamic_io_binding.py, examples/directml/llama_v2/run_llama_v2_io_binding.py, examples/directml/stable_diffusion_xl/requirements.txt, examples/directml/stable_diffusion_xl/stable_diffusion_xl.py
Add some parameters to make the DirectML examples easier to use on different hardware.
=> Improve DirectML examples

examples/whisper/code/whisper_encoder.py, examples/whisper/prepare_whisper_configs.py, olive/passes/onnx/insert_beam_search.py, olive/passes/onnx/mixed_precision.py
1. Changes follow ort 1.16.2 for whisper fp 16 cases
2. Topologically sort model before chaining and saving.
Olive optimization:
Right transcription:
=> ☸️ Whisper fp16 in ort 1.16.2

olive/evaluator/metric.py, olive/workflows/run/run.py
Fix issue https://github.com/microsoft/Olive/issues/323 and add dml setup
Originally, Metrics validation uses https://huggingface.co/api/spaces?filter=metric to check whether the submetrics is supported or not by Hugging Face. However, this API is changed, which result in the unit test failure. 
I changed to use evaluate.load to check whether the submetric is supported or not.
=> Fix issue 323 and add dml setup

docs/architecture.md, docs/source/api/passes.rst, docs/source/features/passes/onnx.md, docs/source/overview/options.md, olive/passes/onnx/__init__.py, olive/passes/onnx/conversion.py, test/unit_test/passes/onnx/test_conversion.py
Convert onnx model to target opset version
=> 🧇 Convert onnx model to target opset version

olive/passes/onnx/moe_experts_distributor.py
Add option to configure number of parallel jobs.
=> Add option to configure number of parallel jobs

olive/workflows/run/run.py
move ort loggging config into run engine
=> move ort loggging config into run engine

olive/engine/engine.py, olive/engine/packaging/packaging_generator.py, olive/strategy/search_algorithm/optuna_sampler.py, olive/strategy/search_algorithm/search_algorithm.py, olive/strategy/search_results.py, olive/strategy/search_strategy.py, olive/systems/azureml/aml_system.py, olive/systems/docker/docker_system.py, olive/systems/docker/utils.py, olive/systems/local.py, olive/systems/olive_system.py, olive/systems/python_environment/python_environment_system.py
Move all possible type hint import under TYPE_CHECKING.
=> type hint checking import refactor

olive/passes/onnx/perf_tuning.py, test/unit_test/passes/onnx/test_perf_tuning.py
More logs to perf tuning.
Fix perf tuning best latency bug which will impact the algorithm for next search point
=> Add more logs to perf tuning

examples/whisper/README.md, examples/whisper/prepare_whisper_configs.py, examples/whisper/whisper_template.json, olive/passes/onnx/mixed_precision.py
Expose the atol for mixed precision. See more in this issue: https://github.com/microsoft/Olive/issues/740
=> 🚶Whisper mixed precision atol

docs/source/tutorials/configure_data.rst, examples/llama2/llama2_qlora.json, examples/open_llama/open_llama_lora_tinycodes.json, examples/open_llama/open_llama_qlora_ort_tinycodes.json, examples/open_llama/open_llama_qlora_tinycodes.json, olive/data/config.py, olive/systems/azureml/aml_pass_runner.py, olive/systems/azureml/aml_system.py, olive/workflows/run/config.py, pyproject.toml, test/unit_test/systems/azureml/script_dir/user_script.py, test/unit_test/systems/azureml/test_aml_system.py
Add data config support for aml system. Some passes like LoRA or QLoRA need datasets. The data config should also be uploaded to aml job.
=> Add dataconfig support for aml system

README.md
=> Add News section in Readme.md

olive/evaluator/olive_evaluator.py, olive/model/__init__.py, olive/model/model_config.py
For mlflow model, we will get io config from Huggingface by model_name .
=> Fix io config bug for hf models and mlflow models

docs/source/features/custom_scripts.md, docs/source/overview/options.md, docs/source/tutorials/configure_metrics.rst, examples/AST/ast.json, examples/bert/bert_cuda_gpu.json, examples/bert/bert_trt_gpu.json, examples/bert/debug.py, examples/cifar10_openvino_intel_hw/config.json, examples/mobilenet_qnn_qualcomm_npu/mobilenet_config_template.json, examples/resnet/conda.yaml, examples/resnet/resnet_multiple_ep.json, examples/resnet/resnet_qat_default_train_loop_cpu.json, examples/resnet/resnet_qat_lightning_module_cpu.json, examples/resnet/user_script.py, olive/evaluator/accuracy.py, requirements.txt, test/integ_test/evaluator/azureml_eval/utils.py, test/integ_test/evaluator/docker_eval/utils.py, test/integ_test/evaluator/local_eval/utils.py, test/unit_test/evaluator/test_metric.py, test/unit_test/test_data_root.py, test/unit_test/utils.py, test/unit_test/workflows/mock_data/only_transformer_dataset.json, test/unit_test/workflows/mock_data/transformer_dataset.json
Upgrade torchmetrics to >=1.0.0 
https://github.com/microsoft/Olive/issues/768
=> ⬆️ Upgrade torchmetrics v1

examples/llama2/llama2_qlora.json, olive/passes/onnx/bnb_quantization.py
=> Fix llama2 example bug

examples/directml/stable_diffusion/stable_diffusion.py, examples/directml/stable_diffusion_xl/stable_diffusion_xl.py
Fix incorrect check while creating the output directory.
=> Correct SD and SDXL output directory

examples/llama2/user_script.py
=> Fix llama2 example import

olive/cache.py, olive/systems/local.py
=> Use the new model type name for composite models

examples/directml/stable_diffusion/config.py, examples/directml/stable_diffusion/requirements-common.txt, examples/directml/stable_diffusion/stable_diffusion.py, examples/directml/stable_diffusion/user_script.py
=> Onboard sd-turbo to the DirectML samples

examples/directml/stable_diffusion_xl/config.py, examples/directml/stable_diffusion_xl/stable_diffusion_xl.py, examples/directml/stable_diffusion_xl/user_script.py
=> Onboard sdxl turbo to the DirectML examples

examples/directml/llama_v2/config_llama_v2.json, olive/model/handler/composite.py, test/unit_test/model/test_composite_model.py, test/unit_test/model/user_script.py
try to fix pytorch composite model loading in directml llama2
=> fix pytorch composite model loading in directml llama2

MANIFEST.in, setup.py
1. Exclude the test in the final wheel
2. Add the missed dockerfile for docker system
3. Add both docs/examples in the source distribution
=> Fix setup issues

olive/model/config/hf_config.py, olive/model/handler/mixin/hf_config.py, olive/model/utils/hf_utils.py, olive/passes/onnx/conversion.py, olive/passes/pytorch/tensor_parallel.py, test/unit_test/model/test_hf_utils.py
Remove some hardcoded use cases and organize hf_config/hf_utils
* Move static function in HfConfigMixin to ht_utils
* Add new function to get the hf model type
* Removed hardcoded reference to setup/restore Llama layers
=> Remove some hardcoded use cases and organize hf_config/hf_utils

.pre-commit-config.yaml, requirements-dev.txt
=> unpin ruff version

README.md
Add VS Code Extension link
Add Ignite 2023 blog
=> Update news section 

.pre-commit-config.yaml, examples/whisper/prepare_whisper_configs.py
Remove ruff formatter
Fix whisper config linter
=> 🗑️ Remove ruff formatter

examples/llama2/tensor_parallel_inference.py, olive/model/config/hf_config.py, olive/passes/pytorch/tensor_parallel_layers.py, olive/passes/pytorch/tensor_parallel_llama2.py
Fix llama2 tensor parallel implementation to work with transformers>=4.36.0
=> Fix llama2 tensor parallel implementation to work with transformers>=4.36.0

examples/llama2/tensor_parallel_generate.py, olive/passes/pytorch/tensor_parallel_llama2.py
Example to use model.generate for distributed Llama2 model
Also, a small edit to suppress warnings generated during export and inference.
=> Example to use model.generate for distributed Llama2 model

olive/model/config/__init__.py, olive/model/handler/mixin/hf_config.py, olive/model/handler/pytorch.py, olive/passes/onnx/conversion.py, olive/passes/onnx/merge_decoders.py
Implement ONNX decoder merge
* Introducing logic to merge onnnx decoders
* OnnxConversion now returns a merged ONNX model conditionally.
=> Implement ONNX decoder merge

olive/engine/engine.py, olive/workflows/run/config.py, test/multiple_ep/test_aml_system.py, test/multiple_ep/test_docker_system.py, test/multiple_ep/test_python_env_system.py, test/unit_test/engine/test_engine.py
Remove unused param from Engine
=> Remove unused param from Engine

olive/passes/onnx/inc_quantization.py
=> enable diagnosis for inc quantization

examples/directml/stable_diffusion/user_script.py, olive/passes/openvino/quantization.py, test/requirements-test.txt
fix lint issues with pre-commit
fix stable diffusion example failure caused by diffusers 0.25 release.
=> fix lint issues with pre-commit&fix stable diffusion example with diffusers 0.25

docs/source/features/passes/onnx.md, olive/passes/onnx/inc_quantization.py, olive/passes/onnx/perf_tuning.py
Add enable_profiling for perf tuning
=> Add enable_profiling for perf tuning

olive/engine/engine.py, olive/engine/footprint.py, test/unit_test/engine/test_footprint.py
=> make footprint logic clear

examples/mistral/mistral_optimize.json, examples/mistral/readme.md, examples/mistral/requirements.txt, examples/mistral/user_script.py
=> Add mistral examples

examples/mistral/readme.md
=> update mistral readme

olive/engine/footprint.py
add get_output_model_path back since it is used by stable diffusion examples
=> add get_output_model_path back

docs/source/overview/options.md
Fix issue https://github.com/microsoft/Olive/issues/866
=> update doc link

.pre-commit-config.yaml, olive/data/config.py, olive/engine/packaging/packaging_config.py, olive/evaluator/metric.py, olive/evaluator/metric_config.py, olive/model/config/model_config.py, olive/passes/olive_pass.py, olive/resource_path.py, olive/systems/system_config.py
=> fix ruff warnings

docs/source/tutorials/configure_systems.rst, olive/systems/azureml/aml_system.py, olive/systems/common.py, olive/systems/system_config.py, test/unit_test/systems/azureml/test_aml_system.py
Add support for existing aml environment for aml system. Users can specify env name, version and label to for their Environment.
=> Add support for existing aml environment for aml system

test/unit_test/passes/vitis_ai/test_vitis_ai_quantization.py
=> refactor vitis UT

docs/source/features/packaging_output_models.md, olive/engine/packaging/packaging_generator.py, test/unit_test/engine/packaging/test_packaging_generator.py
Add models rank json file. This file ranks all output models from different EPs. This json file includes `model_config` and `metrics`. User can find model path and EP info from `model_config`.
=> Add models rank json file

olive/passes/onnx/vitis_ai/quant_utils.py, olive/passes/onnx/vitis_ai/quantizer.py
With PR https://github.com/microsoft/Olive/pull/881, the CI pipeline for ORT 1.15 is broken. This PR is to fix the issue.
=> fix vitis CI broken caused by calibrate API changes

test/unit_test/passes/onnx/test_optimum_conversion.py
=> fix UT on older optimum like 1.13.2

examples/directml/stable_diffusion/ov_optimization_utils.py, examples/directml/stable_diffusion/requirements-ov.txt, olive/platform_sdk/qualcomm/configure.py, olive/platform_sdk/qualcomm/create_python_env.ps1, olive/platform_sdk/qualcomm/create_python_env.sh
1. Fix the ci issue where pip install with hash error.
2. Format requirements file.
=> Qnn: create self pyenv with pip arguments

.github/workflows/lint.yml
=> add permission block to fix permission issue

olive/passes/onnx/transformer_optimization.py, test/unit_test/passes/onnx/test_transformer_optimization.py
Fix https://github.com/microsoft/Olive/issues/645 by adding the EP support in case of use_gpu.
=> support dml in transformer optimization

examples/stable_diffusion/README.md
=> Update stable diffusion example README.md

olive/workflows/run/run.py
=> Setup: Fix `sys.executable` 

olive/engine/config.py, olive/engine/packaging/packaging_generator.py, olive/evaluator/metric_config.py, olive/model/config/hf_config.py, olive/model/utils/hf_mappings.py, olive/passes/pytorch/sparsegpt_utils.py, olive/resource_path.py, olive/strategy/search_strategy.py
This PR is make the in clause consistent with https://pylint.readthedocs.io/en/latest/user_guide/messages/refactor/consider-using-tuple.html
=> prefer tuple instead of list for in clause

.pre-commit-config.yaml, examples/directml/llama_v2/chat_app/app_modules/overwrites.py, examples/stable_diffusion/ov_optimization_utils.py, examples/whisper/code/past_helper.py, examples/whisper/code/whisper_decoder.py, examples/whisper/code/whisper_encoder.py, olive/common/utils.py, olive/data/component/post_process_data.py, olive/data/component/pre_process_data.py, olive/data/registry.py, olive/engine/engine.py, olive/model/config/registry.py, olive/model/utils/hf_utils.py, olive/passes/olive_pass.py, olive/passes/onnx/merge_decoders.py, olive/passes/onnx/mixed_precision.py, olive/passes/pass_config.py, olive/passes/pytorch/cluster.py, olive/strategy/search_parameter.py, olive/workflows/snpe/convertquantize/convertquantize.py, olive/workflows/snpe/evaluate/evaluate.py, test/unit_test/workflows/whisper_utils.py
=> fix ruff lint error with new ruff version

.github/workflows/codeql.yml, .github/workflows/lint.yml
Upgrade codeql to v3 by instruction https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/
=> upgrade codeql version

olive/common/utils.py, olive/systems/python_environment/python_environment_system.py, test/unit_test/systems/python_environment/test_python_environment_system.py
=> refactor cmd utils

olive/workflows/run/config.py, test/unit_test/workflows/test_run_config.py
Comb the relationship among search_strategy, disable_search, searchable_values as:
1. if search_strategy is None and user set disable_search as False, raise error.
2. if search_strategy is None and user did not set disable_search, olive set disable_search as True
3. if search_strategy is not None, respect the users settings on disable_search.
4. disable_search cannot be True if user set any parameters as `SEARCHABLE_VALUES`
This PR will raise value error for any cases which violate above rules.
=> 🧭 Comb the relationship among search_strategy, disable_search, searchable_values

.azure_pipelines/olive-ci.yaml, .azure_pipelines/olive-ort-last.yaml, examples/bert/docker/Dockerfile
=> enable bert docker in last ci pipeline

examples/bert/bert_ptq_cpu.json, examples/stable_diffusion/config_safety_checker.json, examples/stable_diffusion/config_text_encoder.json, examples/stable_diffusion/config_unet.json, examples/stable_diffusion/config_vae_decoder.json, examples/stable_diffusion/config_vae_encoder.json, examples/stable_diffusion/requirements-common.txt, olive/common/ort_inference.py, olive/engine/engine.py
=> enable more logs for engine run pass

examples/whisper/test_transcription.py, olive/passes/onnx/model_optimizer.py, olive/workflows/run/config.py
=> fix ruff format issue

.pre-commit-config.yaml, pyproject.toml, requirements-dev.txt
=> upgrade to ruff 0.2.0

examples/inception/README.md, examples/vgg/README.md, olive/platform_sdk/qualcomm/qnn/env.py, olive/platform_sdk/qualcomm/snpe/env.py
=> 🦤 Fix Qualcomm configure doc/comments

examples/directml/llama_v2/run_llama_v2_batched_io_binding.py, examples/inception/download_files.py, examples/stable_diffusion/ov_optimization_utils.py, examples/whisper/code/whisper_decoder.py, olive/model/config/hf_config.py, olive/model/handler/onnx.py, olive/passes/olive_pass.py, olive/passes/onnx/model_optimizer.py, olive/passes/pytorch/qat_utils.py, olive/passes/pytorch/tensor_parallel_llama2.py, olive/platform_sdk/qualcomm/qnn/qnn.py, olive/platform_sdk/qualcomm/snpe/env.py, olive/strategy/search_space.py, olive/strategy/search_strategy.py, olive/strategy/utils.py, olive/systems/azureml/aml_system.py, pyproject.toml, test/unit_test/data_container/test_dataset.py, test/unit_test/passes/onnx/test_transformer_optimization.py, test/unit_test/systems/azureml/test_aml_system.py, test/unit_test/workflows/whisper_utils.py
=> Enable some ignored ruff lint rules.

examples/super_resolution/README.md, examples/super_resolution/requirements.txt, examples/switch/requirements.txt
Add requirements & instructions for switch & super resolution examples
=> Add requirements & instructions for switch & super resolution examples

olive/passes/onnx/__init__.py, olive/passes/onnx/qnn_preprocess.py, test/unit_test/passes/onnx/test_qnn_preprocess.py
=> 📟 [QNN EP] QNN preprocess passes

olive/passes/onnx/quantization.py, test/unit_test/engine/test_engine.py, test/unit_test/passes/onnx/test_quantization.py
=> 🌗 [QNN EP]QNN Quantization config

docs/source/api/passes.rst, docs/source/conf.py, docs/source/features/model_transformations_and_optimizations.rst, docs/source/features/passes/onnx.md, docs/source/features/passes/qnn.md, docs/source/features/passes/snpe.md, olive/passes/onnx/qnn_preprocess.py, olive/passes/qnn/context_binary_generator.py, olive/passes/qnn/conversion.py, olive/passes/qnn/model_lib_generator.py
Add docs for the new qnn related passes
=> Add docs for QNN related passes

olive/systems/azureml/aml_system.py, olive/systems/system_config.py
=> Add tags to AML job

.github/workflows/lint.yml
=> exclude NOTICE.txt for misspell

examples/llama2/llama2.py, examples/phi2/phi2.py, examples/test/test_whisper.py, examples/test/utils.py, examples/whisper/code/whisper_dataset.py, examples/whisper/prepare_whisper_configs.py, examples/whisper/test_transcription.py, olive/azureml/azureml_client.py, olive/common/utils.py, olive/data/component/dataset.py, olive/engine/footprint.py, olive/model/handler/pytorch.py, olive/passes/onnx/moe_experts_distributor.py, olive/platform_sdk/qualcomm/utils/data_loader.py, olive/systems/azureml/aml_evaluation_runner.py, olive/systems/azureml/aml_pass_runner.py, olive/systems/docker/eval.py, olive/systems/python_environment/inference_runner.py, olive/systems/python_environment/pass_runner.py, olive/systems/utils/arg_parser.py, olive/workflows/run/run.py, pyproject.toml, setup.py, test/integ_test/utils.py, test/unit_test/common/test_import_lib.py, test/unit_test/test_cache.py, test/unit_test/workflows/whisper_utils.py
=> ignore ruff PTH123 rule

examples/directml/phi/README.md
=> 🦖 Fix typos in Phi example

olive/systems/azureml/aml_system.py, olive/workflows/run/run.py
Add olive config file to AML job
=> Add olive config file to AML job

olive/passes/onnx/qnn_preprocess.py, olive/passes/onnx/transformer_optimization.py, test/unit_test/passes/onnx/test_qnn_preprocess.py
1. qnn preprocess model path when modified
2. add the missed version.parse
=> 🐛 Bug fix: qnn preprocess model path when modified

olive/engine/engine.py, olive/engine/footprint.py, olive/engine/packaging/packaging_generator.py, olive/hardware/accelerator.py
* For docker system, the EP need specified by user explicitly.
=> Let user specify the ep explicitly for docker system

examples/test/utils.py
=> enable docker run pass in bert example docker test

.lintrunner.toml
This should fix REQUIREMENTS-TXT not work sometimes
=> Fix REQUIREMENTS-TXT lint

.github/pull_request_template.md
=> add example documentation in PR template

olive/hardware/accelerator.py, olive/logging.py, olive/systems/azureml/aml_evaluation_runner.py, olive/systems/azureml/aml_pass_runner.py, olive/systems/azureml/aml_system.py, olive/systems/docker/docker_system.py, olive/systems/docker/eval.py, olive/systems/docker/runner.py, olive/systems/python_environment/evaluation_runner.py, olive/systems/python_environment/pass_runner.py, olive/systems/utils/misc.py, test/unit_test/systems/azureml/test_aml_system.py
* Enable logging level in aml/docker/python env runner
=> Enable logging level in aml/docker/python env

olive/systems/python_environment/python_environment_system.py, olive/systems/utils/misc.py, test/unit_test/systems/python_environment/test_python_environment_system.py
=> install multiple package and requirements at the same time

olive/passes/snpe/conversion.py, olive/passes/snpe/quantization.py
Fix the config documents for `extra_args` which is a string can be passed as is to the snpe tool
=> 🐌 SNPE passes docs fix

olive/passes/pytorch/lora.py
This PR adds support for resuming training in LoRA based passes. Like in transformers and ort-training examples, the training can be resumed by one of:
- Provide a valid checkpoint directing using `resume_from_checkpoint` option
- Provide an `output_dir`. Checkpoints will be saved in this directory instead of a temporary directory. If the pass is run again with the same `output_dir`, it will find the last checkpoint in the directory and resume training from it.
`LoRA`, `QLoRA` and `LoftQ` passes support resuming training from checkpoints.
=> Resumption from checkpoint in LoRA based passes

olive/passes/olive_pass.py, olive/passes/onnx/inc_quantization.py, olive/systems/azureml/aml_pass_runner.py, olive/systems/azureml/aml_system.py, olive/systems/docker/docker_system.py, test/unit_test/passes/test_pass_serialization.py, test/unit_test/systems/azureml/test_aml_system.py, test/unit_test/systems/docker/test_docker_system.py
=> make Pass.config public

olive/passes/onnx/inc_quantization.py, test/unit_test/workflows/test_whisper_workflow.py
=> allow set workspace path for inc quantizer

examples/mistral/mistral.py
In the last PR missed the addition of config argument to the optimize command. Changes are already done in the readme
=> Add config argument

olive/__init__.py
=> Bump version to 0.6.0

olive/model/handler/pytorch.py, test/unit_test/model/test_pytorch_model.py
1. mlflow loading fix where the from_pretrained_args is missed.
2. add ut
=> Ⓜ️ mlflow loading fix

olive/engine/engine.py, olive/passes/olive_pass.py, olive/passes/onnx/inc_quantization.py, olive/passes/onnx/perf_tuning.py, test/unit_test/passes/onnx/test_perf_tuning.py
*  Allow pass run on target for perftuning/inc_quantization
=> Allow pass run on target

test/unit_test/conftest.py, test/unit_test/model/test_pytorch_model.py, test/unit_test/systems/isolated_ort/test_isolated_ort_system.py, test/unit_test/workflows/test_setup.py, test/unit_test/workflows/test_whisper_workflow.py
=> cleanup the UT directories

olive/common/utils.py, olive/platform_sdk/qualcomm/runner.py, test/unit_test/snpe/test_adb_run.py
=> fix windows shutil.which return None when passing full python path

olive/common/utils.py, olive/model/handler/mixin/dummy_inputs.py, olive/model/handler/mixin/hf_config.py, olive/model/utils/hf_utils.py, olive/passes/onnx/perf_tuning.py, test/unit_test/model/test_pytorch_model.py, test/unit_test/workflows/test_setup.py
1. Fill the gap of dummy input in MLFlow transformer model
2. Fix typos.
=> 🎲 Fill the gap of dummy input in MLFlow transformer model

olive/systems/system_config.py, test/unit_test/systems/isolated_ort/test_isolated_ort_system.py
=> fix isolated system validation logic for None python path

olive/common/auto_config.py, olive/common/config_utils.py, olive/evaluator/metric.py, olive/passes/olive_pass.py, olive/resource_path.py, olive/strategy/search_strategy.py
=> simplify validate_config signature

olive/passes/onnx/inc_quantization.py, olive/passes/onnx/optimum_merging.py, olive/passes/onnx/transformer_optimization.py, olive/passes/onnx/vitis_ai_quantization.py, olive/systems/isolated_ort/isolated_ort_system.py, olive/systems/local.py
Basically, all passes need create InferenceSession need to be run on target. For e.g. transformer optimization.
=> move all pass need create inference session to run on target

olive/passes/onnx/quantization.py, test/unit_test/passes/onnx/test_quantization.py
Update arguments of matmul 4bit for ort>=1.17.0
1. accuracy_level
2. algorithm
=> 🆙 Update matmul 4bit for ort>=1.17.0

docs/source/features/packaging_output_models.md, olive/engine/engine.py, olive/engine/packaging/packaging_config.py, olive/engine/packaging/packaging_generator.py, olive/workflows/run/config.py, test/unit_test/engine/packaging/test_packaging_generator.py
* Add AzureML packaging support:
* AzureMLModels: output models will be registered to AML workspace Models
* AzureMLData: output models will be uploaded to AML workspace Data.
* Support multi type packaging options.
* Add 2 new packaging type: `AzureMLModels`, `AzureMLData`. The output models from Olive pipeline can be automatically registered to AzureML workspace Models or Data
* Support multi type packaging options.
=> Add AzureML packaging support

docs/source/features/azureml_integration.md
=> Update aml integration doc

examples/mistral/requirements.txt
Added onnxruntime-gpu to requirements.txt since it was not included before and caused an error
=> Update requirements.txt to add onnxruntime-gpu

examples/mistral/mistral.py
Fix the path of the ep in Mistral after the recent change: https://github.com/microsoft/Olive/commit/44de528b7ff3d350d9cab1d6d322404ea49329b7
=> Fix the ep path for mistral

olive/engine/packaging/packaging_generator.py, test/unit_test/engine/packaging/test_packaging_generator.py
Update the model_rank file for zipfile packaging type. The model path now is the path relative to the output zip file.
https://github.com/microsoft/Olive/issues/1007
=> Update zipfile packaging model_path to output path

docs/architecture.md, olive/engine/engine.py, olive/passes/olive_pass.py, olive/passes/onnx/conversion.py, olive/passes/pytorch/gptq.py, olive/passes/pytorch/sparsegpt.py, olive/passes/pytorch/tensor_parallel.py, test/unit_test/passes/test_pass_serialization.py
Introduce host device concept for pass so that each pass could choose override it or choose it.
=> introduce host_device for pass

olive/hardware/accelerator.py, olive/workflows/run/run.py
1. Comments about where and how accelerators specs are used.
2. Typos fix.
=> 🍸 Comments about where and how accelerators specs are used

examples/phi2/README.md, examples/phi2/phi2.py
Add mlflow packaging option for phi2 example
=> Add mlflow packaging option for phi2 example

olive/common/utils.py, olive/passes/onnx/conversion.py, olive/passes/onnx/inc_quantization.py, olive/passes/onnx/quantization.py, olive/passes/onnx/transformer_optimization.py, olive/passes/onnx/vitis_ai_quantization.py, olive/workflows/run/config.py
=> refactor dict exclude logic

examples/test/test_resnet_ptq_cpu.py, examples/test/utils.py, olive/azureml/azureml_client.py
=> Only turn off azure logging when user doesn't specify logging level

docs/source/tutorials/advanced_users.md, olive/engine/__init__.py, olive/engine/config.py, olive/engine/engine.py, olive/workflows/run/config.py, olive/workflows/run/run.py, test/multiple_ep/utils.py, test/unit_test/engine/packaging/test_packaging_generator.py, test/unit_test/engine/test_engine.py
* simplify the create engine logic
* Cleanup engine config
=> Engine config refactoring

olive/engine/engine.py
=> simplify engine init

docs/Makefile, docs/make.bat, docs/source/api/systems.rst, docs/source/tutorials/configure_systems.rst, olive/systems/common.py, olive/systems/system_config.py, test/unit_test/systems/azureml/test_alias_system.py, test/unit_test/workflows/mock_data/readymade_system.json, test/unit_test/workflows/test_run_config.py
Rewrite the configure system documentation.
=> update configure system document

examples/directml/llama_v2/chat_app/interface/hddr_llama_onnx_dml_interface.py, examples/llama2/llama2.py, examples/mobilenet/mobilenet_qnn_ep.py, examples/phi2/phi2.py, examples/test/test_qnn_tooklit.py, examples/test/test_snpe_toolkit.py, olive/common/ort_inference.py, olive/engine/packaging/sample_code/ONNXModel/python/code_sample.py, olive/evaluator/olive_evaluator.py, olive/passes/onnx/perf_tuning.py, olive/passes/onnx/quantization.py, olive/passes/onnx/vitis_ai/calibrate.py, olive/passes/onnx/vitis_ai/quant_utils.py, olive/passes/onnx/vitis_ai/refine.py, olive/strategy/search_space.py, olive/strategy/search_strategy.py
=> fix partial codel scan issues

olive/passes/olive_pass.py, olive/passes/onnx/vitis_ai/calibrate.py, olive/passes/onnx/vitis_ai/quant_utils.py, olive/passes/onnx/vitis_ai/quantize.py, olive/passes/onnx/vitis_ai/quantizer.py, olive/passes/onnx/vitis_ai/refine.py, olive/passes/pass_config.py, olive/strategy/search_algorithm/exhaustive.py, olive/strategy/search_algorithm/optuna_sampler.py, olive/strategy/search_algorithm/random_sampler.py, olive/strategy/search_algorithm/search_algorithm.py, olive/strategy/search_algorithm/tpe_sampler.py, olive/strategy/search_parameter.py, olive/strategy/search_space.py, olive/strategy/search_strategy.py, olive/systems/azureml/aml_system.py, test/unit_test/common/test_retry.py
=> fix codeql issues

olive/model/utils/hf_utils.py, test/unit_test/model/test_hf_utils.py, test/unit_test/passes/onnx/test_quantization.py, test/unit_test/systems/docker/test_docker_system.py
=> fix codeql warnings

examples/directml/llm/decoder_model.py
=> Fix chunking order in DirectML's decoder model SILU

.azure_pipelines/olive-ci.yaml
There are no example tests yet for this example so no need to run the azure pipeline jobs.
=> CI: skip for `examples/directml/llm`

examples/directml/llm/README.md, examples/directml/llm/llm.py, examples/directml/llm/requirements.txt
=> Update DML version in LLM example

docs/source/features/passes/onnx.md
Bubble up Intel Neural Compressor and AMD Vitis Quantizer passes in the transformations and optimization list.
=> List Intel Neural Compressor and AMD Vitis Quantizer passes

olive/engine/engine.py, olive/engine/footprint.py, olive/evaluator/metric.py, olive/evaluator/metric_backend.py, olive/evaluator/metric_result.py, olive/evaluator/olive_evaluator.py, olive/passes/onnx/inc_quantization.py, olive/passes/onnx/perf_tuning.py, olive/strategy/search_algorithm/optuna_sampler.py, olive/strategy/search_results.py, olive/strategy/search_strategy.py, olive/systems/azureml/aml_system.py, olive/systems/docker/docker_system.py, olive/systems/isolated_ort/isolated_ort_system.py, olive/systems/local.py, olive/systems/olive_system.py, olive/systems/python_environment/python_environment_system.py, test/integ_test/evaluator/azureml_eval/test_aml_evaluation.py, test/integ_test/evaluator/docker_eval/test_docker_evaluation.py, test/integ_test/evaluator/local_eval/test_local_evaluation.py, test/unit_test/engine/test_engine.py, test/unit_test/evaluator/test_metric_backend.py, test/unit_test/passes/onnx/test_perf_tuning.py, test/unit_test/systems/azureml/test_aml_system.py, test/unit_test/systems/docker/test_docker_system.py, test/unit_test/systems/python_environment/test_python_environment_system.py, test/unit_test/systems/test_local.py
* Fix circular import between metric and metric_backend: https://github.com/microsoft/Olive/security/code-scanning/10643
=> Codeql: fix metrics circular import

olive/passes/__init__.py, olive/platform_sdk/qualcomm/utils/__init__.py, olive/strategy/search_algorithm/__init__.py
* fix https://github.com/microsoft/Olive/security/code-scanning/10653
=> fix codeql qualcom issue

README.md
For better visibility of these resources. 
Shows up like below but on the same line
[![PyPI release](https://img.shields.io/pypi/v/olive-ai)](https://pypi.org/project/olive-ai/)
[![Documentation](https://img.shields.io/website/https/microsoft.github.io/Olive?down_color=red&down_message=offline&up_message=online)](https://microsoft.github.io/Olive/)
=> Add badges to readme for pypi release and documentation

docs/source/api/passes.rst, docs/source/features/passes/onnx.md, docs/source/overview/options.md, examples/llama2/README.md, examples/llama2/llama2_model_builder.py, examples/llama2/llama2_model_builder_template.json, examples/phi2/phi2.py, examples/phi2/phi2_genai.json, olive/olive_config.json, olive/passes/onnx/model_builder.py
Fix all references across the codebase.
Renamed GenAIModelExporter to ModelBuilder
=> Rename GenAIModelExporter to ModelBuilder

test/unit_test/passes/pytorch/test_quantization_aware_training.py
=> add optional ep pass serialization test

.azure_pipelines/olive-ort-nightly.yaml
=> disable vitis CI examples test

.azure_pipelines/job_templates/olive-example-template.yaml, .azure_pipelines/job_templates/olive-test-template.yaml, examples/test/utils.py, test/integ_test/utils.py
Using managed identify auth instead of sas token
This change is enabled with both code changes and azure setttings updates(_to link the managed identiy and corresponding azure app, **done**_).
After this PR, we need to remove the tokens and disable sas auth in azure settings.
=> 🪟 Using managed identity auth instead of sas token

examples/test/test_resnet_ptq_cpu.py, test/integ_test/aml_resource_path/test_aml_resource_path.py
Expected failed for aml dataset related test since there is azureml-fsspec cannot get right identity information.
=> ㊙️ Expected failed for aml dataset related test

examples/llama2/README.md, examples/phi2/README.md, olive/engine/packaging/sample_code/GenAIOnnxModel/python/README.md, olive/engine/packaging/sample_code/GenAIOnnxModel/python/code_sample.py, olive/workflows/run/config.py
1. genai 0.1.0, `set_generator_params` accept dict as argument. But after that, `set_generator_params` uncompresses the dict as kwargs. This PR is used to support all of the version of genai.
2. Typos fix
=> ⚱️ new interface for `set_generator_params` for genai > 0.1.0

olive/engine/packaging/packaging_generator.py, test/unit_test/engine/packaging/test_packaging_generator.py
Add ort-genai packaging download
=> Add ort-genai packaging download

examples/directml/llm/run_llm_batched_io_binding.py, examples/directml/llm/run_llm_io_binding.py, examples/directml/llm/run_vision_llm_io_binding.py, examples/gptj/user_script.py, examples/open_llama/user_script.py, olive/passes/onnx/vitis_ai_quantization.py, olive/passes/openvino/quantization.py, olive/strategy/search_space.py, test/unit_test/engine/packaging/test_packaging_generator.py
=> Fixing a few issues reported by newest version of pylint

examples/utils/generator.py, examples/utils/kv_cache_utils.py, olive/passes/onnx/onnx_dag.py
**Generator**
- Infer past present names and io types from model graph
- Some dml related fixes
**OnnxDAG**
- handle `""` inputs. Some inputs are unused so skip them when processing model
=> Generator update, OnnxDAG handle empty inputs

examples/phi2/phi2.py, examples/phi2/phi2_optimize_template.json
1. fix unfound data configs
2. fix phi2 genai json name.
=> 🐛 phi2 example config fix

examples/bert/bert_cuda_gpu.json, examples/bert/bert_inc_dynamic_ptq_cpu.json, examples/bert/bert_inc_ptq_cpu.json, examples/bert/bert_inc_smoothquant_ptq_cpu.json, examples/bert/bert_inc_static_ptq_cpu.json, examples/bert/bert_ptq_cpu.json, examples/bert/bert_ptq_cpu_aml.json, examples/bert/bert_trt_gpu.json, examples/bert/conda.yaml, examples/bert/npu/bert_snpe.json, olive/__init__.py, olive/passes/onnx/conversion.py, pyproject.toml, requirements.txt
- pin requests version temporary to work around the docker py bug.
- change some bert config to opset to support sdp attention.
- add eager in cpu bert to fix the CI failure after upgrading transformers to 4.41.1.
- update bert conda.yaml transformers version to support attn_implementation parameter.
- upgrade olive dev version to 0.7.0
- suppress ruff UP037 lint error.
=> Fix CI pipeline failures

examples/phi3/README.md, examples/phi3/phi3.py, examples/phi3/requirements.txt
=> add AzureML support

.pre-commit-config.yaml, olive/engine/engine.py, olive/passes/pytorch/lora.py, pyproject.toml
=> 🔗 linter fix

examples/bert/requirements.txt, requirements.txt, test/requirements-test.txt
=> bump docker to 7.1

olive/common/utils.py, test/unit_test/common/test_hardlink_copy.py
Support for using hardlinks
Adding utility functions to support using hardlinks.
=> Support for using hardlinks

.github/workflows/codeql.yml
=> ignore codeql for cs file

test/unit_test/passes/onnx/test_extract_adapters.py
The test is flaky for some reason. Static quantization in the setup sometimes fails due to mismatched input shape to node `/model/layers.0/self_attn/Reshape`. Needs further investigation.
=> UT: Skip QDQ model in `test_extract_adapters`

olive/passes/qnn/context_binary_generator.py, test/unit_test/passes/qnn/test_qnn_context_bin_generator.py
Accept SNPE DLC model for qnn context binnary generator
=> 🗡️ Accept SNPE DLC model for qnn context binary generator

docs/source/conf.py, docs/source/overview/options.md, olive/common/config_utils.py, olive/workflows/run/run.py, test/unit_test/workflows/test_run_config.py
Support YAML files as workflow config file. 
 
`olive run` now accepts YAML files as workflow configuration files.
=> Support yaml workflow config

olive/workflows/run/config.py, test/unit_test/workflows/test_workfow_run.py
Fix engine config bugs:
- system in engine config can be null.
- evaluator value can be provided in engine config directly.
=> Fix engine config bugs

olive/systems/azureml/aml_pass_runner.py
fix for the data_config mutation used in AML.
=> fix for update_data_config in aml_pass_runner

examples/bert/user_script.py, examples/llama2/llama2_generate.json, examples/llama2/user_script.py, examples/resnet/user_script.py, examples/whisper/test_transcription.py, olive/common/ort_inference.py, olive/evaluator/metric.py, olive/evaluator/metric_config.py, olive/evaluator/olive_evaluator.py, olive/model/config/model_config.py, olive/model/handler/base.py, olive/model/handler/composite.py, olive/model/handler/onnx.py, olive/model/handler/openvino.py, olive/model/handler/pytorch.py, olive/model/handler/qnn.py, olive/model/handler/snpe.py, olive/model/handler/tensorflow.py, olive/systems/isolated_ort/inference_runner.py, test/unit_test/passes/pytorch/test_lora.py, test/unit_test/systems/isolated_ort/test_isolated_ort_system.py
=> Add support for evaluating generative models in Olive

examples/falcon/config.json, examples/llama2/llama2_qlora.json, examples/llama2/llama2_template.json, examples/llama2/notebook/llama2/config.json, examples/llama2/notebook/llama2_multiep/config_cpu.json, examples/llama2/notebook/llama2_multiep/config_gpu.json, examples/llama2/notebook/llama2_multiep/config_multi_ep.json, examples/open_llama/llama_qlora.json, examples/open_llama/open_llama_loftq_tinycodes.json, examples/open_llama/open_llama_lora_tinycodes.json, examples/open_llama/open_llama_qlora_ort_tinycodes.json, examples/open_llama/open_llama_qlora_tinycodes.json, examples/open_llama/open_llama_sparsegpt_gpu.json, examples/phi/phi_qlora_tinycodes.json, examples/phi2/phi2_optimize_template.json, examples/phi3/pass_configs/data_configs.json, olive/data/component/pre_process_data.py, olive/data/component/text_generation.py
- make ["text"] default value for text_cols and update all example json config
- `corpus_strategy` default value: `join`
- `jointer` default value: `\n\n`
- `source_max_len` default value: 1024 https://github.com/artidoro/qlora/blob/7f4e95a68dc076bea9b3a413d2b512eca6d004e5/qlora.py#L111
=> 📽️ Fix values of pre_process_data_config for text generation

examples/stable_diffusion/sd_utils/ov.py, examples/stable_diffusion/stable_diffusion.py
=> Add optional seed to stable diffusion example to enable deterministic generation

examples/directml/llm/llm.py, examples/directml/llm/model_type_mapping.py, examples/directml/llm/requirements.txt
=> Add llama-3 to list of supported DML LLM models

.azure_pipelines/job_templates/olive-build-template.yaml, .azure_pipelines/olive-ci.yaml, .azure_pipelines/olive-ort-last.yaml, examples/test/test_bert_cuda_gpu.py, examples/test/test_resnet_ptq_cpu.py, examples/test/test_resnet_vitis_ai_ptq_cpu.py, requirements-dev.txt, test/multiple_ep/test_aml_system.py, test/multiple_ep/test_docker_system.py
Storage accounts are currently not accessible. Commenting out or skipping affected tests until a solution is found.
=> CI: Skip AzureML and Integration tests

.azure_pipelines/job_templates/olive-build-template.yaml, .azure_pipelines/olive-ci.yaml, olive/auto_optimizer/template_mapping.py, olive/evaluator/olive_evaluator.py, olive/model/handler/pytorch.py, olive/passes/pytorch/qat_utils.py, requirements-dev.txt, test/integ_test/aml_model_test/test_aml_model.py, test/integ_test/aml_resource_path/test_aml_resource_path.py, test/integ_test/evaluator/azureml_eval/test_aml_evaluation.py, test/multiple_ep/test_docker_system.py, test/unit_test/systems/docker/test_docker_system.py
- Storage access for these tests have been resolved. Azure ML tests are still blocked.
- Fix lint issues due to new ruff release 0.5.0
=> CI: Re-enable integration tests and QC toolkit tests

olive/model/handler/pytorch.py
updated json keys for `mlflow_transformer_model_cache_dir`.
=> fix for read-only on AML

.azure_pipelines/olive-ci.yaml, examples/test/test_bert_cuda_gpu.py, examples/test/test_resnet_ptq_cpu.py, examples/test/test_resnet_vitis_ai_ptq_cpu.py, test/integ_test/aml_model_test/test_aml_model.py, test/integ_test/aml_resource_path/test_aml_resource_path.py, test/integ_test/evaluator/azureml_eval/test_aml_evaluation.py
=> CI: Re-enable AzureML tests

test/unit_test/model/test_pytorch_model.py
- load_model test is updated to check for model type. The previous test is outdated since we don't use mlflow to load the model anymore.
- test model changed to "hf-internal-testing/tiny-random-BertForSequenceClassification" which is smaller and also has the classification head.
=> UT: Update MLFlow model test

olive/azureml/azureml_client.py, olive/common/utils.py, olive/engine/cloud_cache_helper.py, olive/engine/engine.py, olive/model/config/model_config.py, olive/workflows/run/config.py, olive/workflows/run/run.py, test/multiple_ep/utils.py, test/unit_test/engine/packaging/test_packaging_generator.py, test/unit_test/engine/test_cloud_cache_helper.py, test/unit_test/engine/test_engine.py
=> Add cloud model cache

docs/source/features/custom_scripts.md, docs/source/overview/options.md, docs/source/tutorials/configure_metrics.rst, examples/bert/bert_inc_dynamic_ptq_cpu.json, examples/bert/bert_inc_ptq_cpu.json, examples/bert/bert_inc_smoothquant_ptq_cpu.json, examples/bert/bert_inc_static_ptq_cpu.json, examples/bert/user_script.py, examples/mobilenet/mobilenet_qnn_ep_template.json, examples/open_llama/open_llama_inc_woq.json, examples/open_llama/user_script.py, examples/resnet/resnet_ptq_cpu.json, examples/resnet/resnet_vitis_ai_ptq_cpu.json, examples/resnet/user_script.py, olive/evaluator/olive_evaluator.py, test/unit_test/assets/user_script.py, test/unit_test/evaluator/test_olive_evaluator.py
* Update documentation
* Remove references to deprecated keys in Metric/user_config
* Move Metric/user_config/data_dir & Metric/user_config/batch_size into Metric/evaluate_func_args/* as they apply only to custom evaluation
=> Clean up post metric change

.lintrunner.toml, .pre-commit-config.yaml, scripts/format_json.py
Add pre-commit hook for json format linter.
=> JSON Format `pre-commit` hook

.azure_pipelines/olive-ci.yaml, .azure_pipelines/olive-ort-last.yaml, .azure_pipelines/olive-ort-nightly.yaml
Training is slow on windows cpu. qat is not really used + training is not usually done on cpu.
=> CI: Remove resnet qat example test

olive/common/hf/utils.py, olive/model/handler/mixin/hf.py, test/unit_test/model/test_hf_model.py
Some models like [phi3](https://huggingface.co/microsoft/Phi-3-mini-4k-instruct/blob/main/config.json) has additional module files such as `configuration_phi3.py` which are required if `AutoConfig.from_pretrained` is called with `trust_remote_code = True`. 
Updated the `save_metadata` method to save any such files if present.
=> HfModelHandler: save module files along with metadata

olive/passes/pytorch/lora.py
=> Fix lora pass output type

docs/source/features/run_workflow_remotely.md
Fix remote workflow section title
=> Fix remote workflow section title

olive/cache.py, olive/common/config_utils.py, olive/engine/cloud_cache_helper.py, olive/engine/engine.py, olive/systems/azureml/aml_system.py, test/unit_test/engine/test_cloud_cache_helper.py
Add adapter path support for cloud model cache
=> Add adapter path support for cloud model cache

docs/source/overview/quicktour.md, olive/cli/run.py, olive/workflows/run/run.py, test/unit_test/cli/test_cli.py, test/unit_test/workflows/test_workflow_run.py
Add --packages to cli to list required packages
=> Add --packages to cli to list required packages

.azure_pipelines/job_templates/olive-example-template.yaml, .azure_pipelines/olive-aml-ci.yaml, .azure_pipelines/olive-ci.yaml, README.md, examples/test/azureml/test_bert_ptq_cpu_aml.py, examples/test/azureml/test_resnet_ptq_cpu_aml.py, examples/test/azureml/test_resnet_vitis_ai_ptq_cpu_aml.py, examples/test/local/test_bert_cuda_gpu.py, examples/test/local/test_bert_ptq_cpu.py, examples/test/local/test_bert_ptq_cpu_docker.py, examples/test/local/test_mobilenet_qnn_ep.py, examples/test/local/test_qnn_tooklit.py, examples/test/local/test_resnet_ptq_cpu.py, examples/test/local/test_resnet_qat.py, examples/test/local/test_resnet_vitis_ai_ptq_cpu.py, examples/test/local/test_snpe_toolkit.py, examples/test/local/test_stable_diffusion_cuda_gpu.py, examples/test/local/test_whisper.py, examples/test/utils.py, pyproject.toml
- Separate aml example test from pipeline
- New aml example test pipeline had been setup.
- AML example pipeline will run once a week.
- AML example pipeline will be triggered when code merged, and pr trigger for azureml client and aml system.
=> Separate aml example test from pipeline

examples/llama2/README.md, examples/llama2/conda_gpu.yaml, examples/llama2/llama2.py, examples/llama2/llama2_qlora.json
- Add remote workflow and cloud cache support to llama2 example.
- Fix markdown format.
=> Add remote workflow and cloud cache support to llama2 example

docs/source/features/huggingface_model_optimization.md, docs/source/features/run_workflow_remotely.md, olive/systems/azureml/aml_system.py, olive/systems/azureml/aml_workflow_runner.py
Update remote workflow and huggingface doc
=> Update remote workflow and huggingface doc

olive/engine/cloud_cache_helper.py, olive/engine/engine.py, olive/resource_path.py, test/unit_test/engine/test_cloud_cache_helper.py
Add cloud cache support for aml models
=> Add cloud cache support for aml models

docs/source/features/lora.md, docs/source/index.rst
=> Document LoRA feature

olive/engine/cloud_cache_helper.py, olive/engine/engine.py, olive/systems/azureml/aml_system.py, test/unit_test/engine/test_cloud_cache_helper.py
Add aml model support for remote workflow
=> Add aml model support for remote workflow

olive/cli/cloud_cache.py, olive/cli/launcher.py, test/unit_test/cli/test_cli.py
Add cli to remove model from cloud cache
New cli command to delete models from cloud cache. Please check cli documentation for more details.
=> Add cli to remove model from cloud cache

olive/olive_config.json
Add onnxruntime-genai as extrad dependency for ModelBuilder pass
=> Add onnxruntime-genai as extra dependency for ModelBuilder pass

docs/source/features/run_workflow_remotely.md, olive/engine/cloud_cache_helper.py, olive/engine/engine.py, olive/systems/azureml/aml_system.py, olive/systems/azureml/aml_workflow_runner.py, test/unit_test/engine/test_cloud_cache_helper.py
- Add additional files support for cloud cache.
- Fix minor bugs.
- New AML job can't delete existing blobs. So one option here is to call AML Data API to archive the old data. Another option is to using current time as folder name to distinguish different runs. This PR takes the second proposal.
=> Add additional files support for cloud cache

examples/phi3/README.md, examples/phi3/README_VISION.md, examples/phi3/phi3_vision.py, examples/phi3/requirements-vision.txt, examples/phi3/vision/config_templates/text_config.json, examples/phi3/vision/config_templates/text_embedding_config.json, examples/phi3/vision/config_templates/vision_config.json, examples/phi3/vision/scripts/prepare_phi3_vision_for_olive.sh, examples/phi3/vision/scripts/user_script.py
=> 👓  phi3-vision tutorial

.lintrunner.toml, docs/Makefile, docs/make.bat, requirements-dev.txt
=> Fix editor format

olive/cli/base.py, olive/cli/constants.py, olive/cli/finetune.py, olive/cli/perf_tuning.py
Add remote options to finetune and perf-tuning cli
=> Add remote options to finetune and perf-tuning cli

examples/phi3/phi3.py
=> Do not force quarot

olive/cli/base.py, olive/cli/capture_onnx.py, olive/cli/finetune.py
Refactor HF model options in special commands
=> Refactor HF model options in special commands

.azure_pipelines/job_templates/olive-example-template.yaml, .azure_pipelines/olive-aml-ci.yaml, .azure_pipelines/olive-ci.yaml, examples/llama2/conda_gpu.yaml, examples/llama2/requirements-pipeline.txt, examples/llama2/requirements-qlora.txt, examples/test/azureml/test_llama2.py, examples/test/local/test_llama2.py, examples/test/utils.py
Add llama2 example to pipeline
=> Add llama2 example to pipeline

olive/workflows/run/config.py
custom data config doesn't have `type`.
=> fix dataconfig bug

olive/cache.py, olive/common/hf/mlflow.py, test/unit_test/model/test_hf_model.py, test/unit_test/model/test_mlflow_model.py
1. Update and simplify mlflow logic. 
New mlflow folder structure:
```
mlflow_folder/
├── model/
│   ├── model_files
│   └── config.json
└── components/
└── tokenizer/
└── tokenizer_files
```
2. Update downloading non-local resource logic. Add support to download azureml curated model (not sure which PR changes this logic before).
=> update mlflow logic

olive/cli/capture_onnx.py
https://github.com/microsoft/Olive/issues/1348
=> fix cli bug

examples/llama2/llama2_lmeval.json, olive/evaluator/olive_evaluator.py
* Added a new Evaluator to use lm_eval to evaluate hf model
* Added a llama2 config to use the new evaluator
=> Add evaluation support for using lm-eval harness

olive/data/component/text_generation.py
Some text generation datasets have chat data like https://huggingface.co/datasets/trl-internal-testing/dolly-chatml-sft. Support using default or user provided chat template instead of text columns/templates.
=> Text-gen: Support `chat_template`

docs/source/features/cli.rst, olive/cli/base.py, olive/cli/capture_onnx.py, olive/cli/export_adapters.py, olive/cli/finetune.py, olive/cli/perf_tuning.py, olive/common/user_module_loader.py, olive/model/handler/hf.py, olive/model/handler/mixin/dummy_inputs.py, olive/model/handler/pytorch.py, olive/passes/qnn/context_binary_generator.py, test/unit_test/cli/output_model/model_config.json, test/unit_test/cli/test_base.py, test/unit_test/cli/test_cli.py
Add local pytorch model and cli-produced-model support for cli.
=> Add local pytorch model and cli-produced-model support for cli

examples/directml/stable_diffusion_xl/config_unet.json, examples/directml/stable_diffusion_xl/config_vae_decoder.json, examples/directml/stable_diffusion_xl/config_vae_encoder.json, examples/directml/stable_diffusion_xl/stable_diffusion_xl.py
Issue: SD XL optimization for DirectML doesn't work due to incorrect config
=> Fix SDXL optimization for DirectML

examples/llama2/requirements-qlora.txt, test/requirements-test-gpu.txt
=> pin bitsandbytes to 0.43.3

olive/cli/auto_opt.py, olive/cli/base.py
Refactor auto-opt serach option handling
=> Refactor auto-opt search option handling

olive/workflows/run/config.py
=> Deprecate support for inline data configs

docs/source/index.rst, olive/cli/auto_opt.py, olive/cli/export_adapters.py
Use separate section for CLI documentation.
=> Use separate section for CLI documentation.

docs/source/features/cli.rst
=> Document quantize command

olive/passes/pytorch/lora.py
Make `deepspeed` an exposed `training_args` option. Along with the dict and string types supported by default, we also allow bool. If set to `True`, it will use a default deepspeed config which enables ZeRO3 with cpu offloading.
=> LoRA: Expose `deepspeed` option with default value if True

examples/llama2/llama2_lmeval.json
=> Add QLoRA pass to Llama lm-eval example

docs/source/conf.py, examples/llama2/requirements-qlora.txt
=> CI: Fix test dependencies

olive/auto_optimizer/__init__.py, olive/auto_optimizer/regulate_mixins.py
remove accuracy_drop check for gpu device
=> remove accuracy_drop check for gpu device

olive/data/component/dataloader.py, olive/data/component/post_process_data.py, olive/data/component/text_generation.py, olive/model/handler/hf.py, olive/model/handler/pytorch.py, olive/passes/pytorch/cluster.py, olive/passes/pytorch/lora.py, olive/passes/pytorch/tensor_parallel.py, olive/passes/pytorch/tensor_parallel_llama2.py, olive/passes/pytorch/trt_utils.py, olive/platform_sdk/qualcomm/utils/data_loader.py, olive/systems/isolated_ort/isolated_ort_system.py
remove unnecessary top level torch imports
=> remove unnecessary top level torch imports

olive/resource_path.py
Add AzureMLRegistryModel to AZUREML_RESOURCE_TYPES
=> Add AzureMLRegistryModel to AZUREML_RESOURCE_TYPES

olive/cli/quantize.py, test/unit_test/cli/test_cli.py
=> Rework quantize cli command to use algorithm, and precision as input

olive/common/hf/peft.py, olive/passes/onnx/common.py, olive/passes/onnx/extract_adapters.py
Add new lora node support for extract adapter
=> Add new lora node support for extract adapter

olive/cli/capture_onnx.py
Fix cli argparse help format: tuple -> str. Now `olive -h` works automatically.
```
➜ Olive git:(xiaoyu/cli) olive -h
usage: olive
positional arguments:
{run,auto-opt,capture-onnx-graph,finetune,generate-adapter,convert-adapters,quantize,tune-session-params,configure-qualcomm-sdk,manage-aml-compute,shared-cache}
run                 Run an olive workflow
auto-opt            Automatically optimize the performance of the input model.
capture-onnx-graph  Capture ONNX graph using PyTorch Exporter or Model Builder from the Huggingface model or
PyTorch model.
finetune            Fine-tune a model on a dataset using peft. Huggingface training arguments can be provided
along with the defined options.
generate-adapter    Generate ONNX model with adapters as inputs. Only accepts ONNX models. …
```
=> Fix cli argparse help format

docs/source/features/cli.rst, olive/cli/auto_opt.py, olive/cli/base.py, olive/cli/convert_adapters.py, olive/cli/finetune.py, olive/cli/quantize.py
Clarify help messages for the command line options.
Fix hyper link to the doc in help message.
=> Clean up CLI docs

docs/source/extending_olive/how_to_add_optimization_pass.md, docs/source/exts/auto_config_doc/__init__.py, olive/passes/olive_pass.py, olive/passes/onnx/inc_quantization.py, olive/passes/onnx/nvmo_quantization.py, olive/passes/onnx/quantization.py, olive/passes/onnx/vitis_ai_quantization.py, olive/passes/pass_config.py, olive/passes/pytorch/lora.py, olive/passes/snpe/quantization.py
Update to conditionally turn user provided input values into Categorical search suggestions.
=> Use user provided values as searchable suggestions

olive/passes/onnx/model_builder.py
=> Add adapter_path option in model builder pass

docs/architecture.md, docs/source/extending_olive/how_to_add_optimization_pass.md, docs/source/features/passes/quant_onnx.md, docs/source/overview/options.md, docs/source/tutorials/configure_pass.rst, examples/bert/bert_inc_dynamic_ptq_cpu.json, examples/bert/bert_inc_ptq_cpu.json, examples/bert/bert_ptq_cpu.json, examples/deberta/deberta.json, examples/directml/llm/config_llm.json, examples/directml/llm/llm.py, examples/test/utils.py, olive/auto_optimizer/regulate_mixins.py, olive/engine/engine.py, olive/passes/olive_pass.py, olive/workflows/run/config.py, olive/workflows/run/run.py, test/unit_test/auto_optimizer/test_auto_optimizer.py, test/unit_test/engine/test_engine.py, test/unit_test/workflows/test_run_config.py
=> Deprecate "disable_search" from Pass config

olive/passes/onnx/extract_adapters.py
Allow `optional_inputs` for quantized adapters also. The default initializers have the same shape as the original weights but the scales are made 0 so that the dequantized weight is 0. Quant weight and zero point are also made 0 to be clean and consistent.
=> ExtractAdapters: Default initializer for quantized modules

.azure_pipelines/olive-ci.yaml, examples/phi3/phi3.py, examples/phi3/phi3_template.json
Fix example that was broken by #1401.
Fixes #1447
=> Phi3: Fix example

examples/phi3/README.md, examples/phi3/phi3_nvmo_ptq.json
=> update phi3_nvmo_ptq example and onnxruntime-directml version

olive/cli/auto_opt.py, olive/olive_config.json
=> Fix an order of operation issue causing AttributeError

olive/cache.py
=> SharedCache: Fix incorrect calls

olive/cli/auto_opt.py
=> Add option to use dynamo exporter for onnx conversion pass

docs/source/features/passes/quant_onnx.md, examples/phi3/README.md, examples/phi3/requirements-nvmo-awq.txt, olive/olive_config.json
=> Update TensorRT Model Optimizer documentation and dependencies 

olive/__init__.py
We already already done some `0.7.x` releases so, updating the dev version to `0.8.0.dev0`. This way it's ahead of the official releases and we can differentiate dev builds from official releases.
Similar to how transformers versions their dev branch.
=> Update main version to 0.8.0.dev0

examples/stable_diffusion/config.py, examples/stable_diffusion/config_vae_decoder.json, examples/stable_diffusion/config_vae_encoder.json, examples/stable_diffusion/sd_utils/config.py, examples/stable_diffusion/sd_utils/ort.py, examples/stable_diffusion/stable_diffusion.py, examples/stable_diffusion/user_script.py
=> Named dim override for Stable Diffusion 

examples/whisper/prepare_whisper_configs.py, olive/evaluator/__init__.py, olive/hardware/__init__.py, olive/model/config/__init__.py, olive/model/handler/__init__.py, olive/passes/__init__.py, olive/passes/onnx/vitis_ai/__init__.py, olive/passes/pytorch/trt_utils.py, olive/platform_sdk/qualcomm/qnn/qnn.py, olive/platform_sdk/qualcomm/snpe/__init__.py, olive/strategy/search_algorithm/__init__.py
=> Fix RUFF format

docs/source/conf.py, docs/source/extending/advanced-users.md, docs/source/how-to/index.rst, examples/llama2/README.md, examples/llama2/notebook/llama2/notebook.ipynb, olive/cli/base.py
=> Fix doc link

docs/source/getting-started/getting-started.md, docs/source/why-olive.md
=> Tidy up docs

olive/common/container_client_factory.py
Fix shared cache bug
https://github.com/microsoft/Olive/issues/1509
=> Fix shared cache bug

docs/source/how-to/configure-workflows/onnx-graph-surgeon.md, docs/source/how-to/index.rst, olive/passes/onnx/graph_surgeries.py, test/unit_test/passes/onnx/test_graph_surgeries.py
Add graph surgeries pass.
Add surgeon:
- RenameInputs
- RenameOutputs
- InferShapes
- RemoveShapes
- ReorderInputs
- ZeroOutInput
- RemoveInputs
- ExposeOutputs
- ExposeQuantizedOutput
=> Add graph surgeries pass

docs/source/how-to/configure-workflows/onnx-graph-surgeon.md, olive/passes/onnx/graph_surgeries.py, test/unit_test/passes/onnx/test_graph_surgeries.py
Add ReorderInputs to GraphSurgeries Pass
=> Add ReorderInputs to GraphSurgeries Pass

docs/source/how-to/configure-workflows/onnx-graph-surgeon.md, olive/passes/onnx/graph_surgeries.py, test/unit_test/passes/onnx/test_graph_surgeries.py
Add ReplaceErfWithTanh to GraphSurgeries
=> Add ReplaceErfWithTanh to GraphSurgeries

olive/olive_config.json, olive/passes/onnx/peephole_optimizer.py, test/requirements-test.txt, test/unit_test/passes/onnx/test_peephole_optimizer.py
Add constant folding and remove initializer from input to peephole optimizer.
=> Add constant folding and onnxoptimizer to peephole optimizer

examples/getting_started/text-gen-optimized-slms.ipynb
Added a notebook that allows users to select from a curated list of popular SLMs to optimize.
=> new notebook for optimizing popular SLMs

.azure_pipelines/olive-examples.yaml
=> Disable a few more tests

examples/mistral/mistral_fp16.json, examples/test/local/test_mistral_fp16.py
=> Fix mistral example and reenable test

docs/source/how-to/configure-workflows/model-opt-and-transform/index.rst, docs/source/how-to/configure-workflows/model-opt-and-transform/onnx.md, docs/source/how-to/index.rst
Tidy up peephole optimizer doc.
=> Tidy up peephole optimizer doc.

docs/source/how-to/configure-workflows/model-opt-and-transform/onnx.md, olive/passes/onnx/peephole_optimizer.py, test/unit_test/passes/onnx/test_peephole_optimizer.py
Set onnxoptimizer.optimize as default for peepholeoptimizer
=> Set onnxoptimizer.optimize as default for peepholeoptimizer

.azure_pipelines/dockerfiles/linux-cpu.dockerfile, .azure_pipelines/dockerfiles/linux-gpu.dockerfile, .azure_pipelines/job_templates/build-docker-image-template.yaml, .azure_pipelines/job_templates/olive-build-doc-template.yaml, .azure_pipelines/job_templates/olive-example-linux-template.yaml, .azure_pipelines/job_templates/olive-example-win-template.yaml, .azure_pipelines/job_templates/olive-setup-template.yaml, .azure_pipelines/job_templates/olive-test-cpu-template.yaml, .azure_pipelines/job_templates/olive-test-linux-gpu-template.yaml, .azure_pipelines/olive-ci.yaml, .azure_pipelines/olive-examples.yaml, .azure_pipelines/olive-ort-nightly.yaml, .azure_pipelines/scripts/run_test.sh, test/requirements-test.txt, test/unit_test/passes/onnx/test_nvmo_quantization.py, test/unit_test/passes/onnx/test_transformer_optimization.py, test/unit_test/passes/vitis_ai/test_vitis_ai_quantization.py
Fix ort nightly pipeline
- Upgrade to cuda 12.6 + TensorRT 10.5.
- Fix python 3.8 example test.
- Fix & skip some tests.
- Fix yaml format.
=> Fix ort nightly pipeline

olive/data/component/pre_process_data.py
- For huggingface data preprocessing (except text-gen which has it's own logic), truncate the data before tokenization if `max_samples` is provided.
- There is no need to tokenizer and process the whole dataset if only a subset is going to be used. This is useful for large datasets where the tokenized data might be too large to fit in memory.
=> Hf data preprocessing: Truncate dataset if `max_samples` is provided

olive/common/hf/mappings.py, olive/common/hf/utils.py, olive/common/hf/wrapper.py, olive/common/utils.py, olive/data/component/dataset.py, olive/model/config/io_config.py, olive/passes/onnx/transformer_optimization.py, olive/passes/pytorch/capture_split_info.py, olive/passes/pytorch/gptq.py, olive/passes/pytorch/sparsegpt.py, olive/passes/pytorch/sparsegpt_utils.py, olive/passes/pytorch/torch_trt_conversion.py, test/unit_test/common/test_hf_wrapper.py, test/unit_test/passes/pytorch/test_gptq.py, test/unit_test/passes/pytorch/test_torch_trt_conversion.py
- Implemented a new huggingface `ModelWrapper` that acts as in interface with huggingface models. It keeps maps for different model types that allows the user to get model attributes and submodules.
- All code using the previous mappings directly have been updated accordingly.
=> Add huggingface `ModelWrapper`

test/requirements-test.txt
Pin mlflow version for test to unblock pipeline. azureml team (or us if they go with mlflow changes) needs to fix the compatibility issue.
=> Pin mlflow version for test

docs/source/reference/index.rst
=> Rename Reference page title

.azure_pipelines/olive-examples.yaml, examples/phi2/requirements-pipeline.txt
=> Fix gpu example pipeline

.azure_pipelines/olive-examples.yaml, examples/test/local/test_mobilenet_qnn_ep.py, examples/test/local/test_qnn_tooklit.py
=> Skip qnn tests in pipeline

docs/source/how-to/configure-workflows/model-opt-and-transform/pytorch.md, docs/source/reference/options.md, docs/source/reference/pass.rst, examples/llama2/llama2_lmeval.json, examples/llama2/llama2_qlora.json, examples/phi3/phi3_template.json, olive/cli/finetune.py, olive/olive_config.json, olive/passes/pytorch/lora.py, olive/passes/pytorch/train_utils.py, test/unit_test/passes/pytorch/test_lora.py
- Add LoHa Pass.
- Add unit test.
- Update docs.
=> Add LoHa and LoKr Pass

olive/passes/onnx/graph_surgeries.py
=> Remove print remnant

olive/passes/onnx/conversion.py
=> [dynamo exporter] Add optimize to onnx conversion config

docs/source/examples.md
Update examples.md to add clip example.
=> Update examples.md to add clip example.

examples/clip/README.md, examples/clip/laion_CLIP-ViT-B-32-laion2B-s34B-b79K_ptq_qnn.json, examples/clip/openai_clip-vit-base-patch16_ptq_qnn.json, examples/clip/openai_clip-vit-base-patch32_ptq_qnn.json, examples/clip/openai_clip-vit-large-patch14_ptq_qnn.json
- Add qnn examples of laion/CLIP-ViT-B-32-laion2B-s34B-b79K model.
- Clean unused config.
```json
{
"accuracy-accuracy": {
"value": 1.0,
"priority": 1,
"higher_is_better": true
},
"latency_qnn-avg": {
"value": 340.28136,
"priority": 2,
"higher_is_better": false
},
"latency_qnn-max": {
"value": 439.1883,
"priority": -1,
"higher_is_better": false
},
"latency_qnn-min": {
"value": 250.1979,
"priority": -1,
"higher_is_better": false
},
"latency_cpu-avg": {
"value": 431.19076,
"priority": 3,
"higher_is_better": false
},
"latency_cpu-max": {
"value": 573.6913,
"priority": -1,
"higher_is_better": false
},
"latency_cpu-min": {
"value": 303.0901,
"priority": -1,
"higher_is_better": false
},
"throughput-avg": {
"value": 2.23641,
"priority": -1,
"higher_is_better": true
},
"throughput-max": { …
```
=> Add qnn examples of laion/CLIP-ViT-B-32-laion2B-s34B-b79K model.

olive/common/ort_inference.py
This issue https://github.com/microsoft/Olive/issues/1636 to support https://onnxruntime.ai/docs/api/python/api_summary.html#onnxruntime.SessionOptions.log_severity_level
=> add log_verbosity_level

.azure_pipelines/job_templates/olive-example-win-template.yaml, .azure_pipelines/job_templates/olive-test-cpu-template.yaml, .azure_pipelines/job_templates/olive-test-linux-gpu-template.yaml, .azure_pipelines/olive-ci.yaml, .azure_pipelines/olive-ort-nightly.yaml, olive/passes/onnx/model_builder.py, test/requirements-test-cpu.txt, test/requirements-test-gpu.txt, test/unit_test/passes/onnx/test_model_builder.py
- Fix config access in model builder pass
- Add unit test for model builder. CPU tests now has its own requirements file.
- Do some clean up in the pipeline yamls:
- set gpu defaults in gpu test templates
- removed unused `device` template parameters
- remove redundant parameter assignment from template calls
- nightly gpu test uses gpu image
Fixes #1635
=> Model Builder: fix config access, add UT, clean up CI yamls

olive/cli/auto_opt.py
Use OnnxDynamicQuantization for dynamic quantization of ONNX model
=> Use OnnxDynamicQuantization for dynamic quantization

examples/bge/bge-small-en-v1.5_ptq_qnn.json, examples/bge/readme.md
=> bge uses mask value

docs/source/examples.md, examples/table_transformer_detection/README.md, examples/table_transformer_detection/prepare_datasets.py, examples/table_transformer_detection/ttd.py, examples/table_transformer_detection/ttd_config.json
Add Table Transformer Detection (https://huggingface.co/microsoft/table-transformer-detection) QNN example.
Input model on CPU:
{
"accuracy-mean_of_max_iou": 0.8218905329704285,
"accuracy-f1_score": 0.9561123496676195,
"latency-avg": 232.75268
}
output model on NPU:
{
"accuracy-mean_of_max_iou": 0.8153600096702576,
"accuracy-f1_score": 0.9516611285450918,
"latency-avg": 124.70602,   
}
=> Add Table Transformer Detection QNN example

olive/engine/packaging/Dockerfile.base
=> Add a comment to suppress warnings during OneBranch build

examples/llama2/README.md, examples/llama2/notebook/llama2/notebook.ipynb, olive/cli/base.py
Some links referencing olive doc pages changed after #1669.
=> Docs: update links

.azure_pipelines/scripts/client_patch.py, examples/directml/llm/chat_app/app.py, scripts/format_json.py
New ruff version got released. Updating the code to comply with it.
=> Lint fixes

olive/evaluator/olive_evaluator.py
=> Fix evaluator bug

olive/cli/quantize.py
=> Fix quantize cli bug

docs/source/reference/pass.rst, olive/olive_config.json
=> add OnnxQuantizationPreprocess to config

.azure_pipelines/olive-ort-nightly.yaml
=> CI: Fix mobilenet qnn ep folder

examples/bert/README.md, examples/bert/google_bert_qdq.json, examples/clip/README.md, examples/resnet/README.md, examples/vit/README.md
=> Tidy up example README files

olive/cli/quantize.py, olive/package_config.py, olive/passes/pytorch/capture_split_info.py, olive/workflows/run/config.py, olive/workflows/run/run.py, test/unit_test/workflows/test_run_config.py
* Typo error in quantize CLI command (w_bit not w_bits)
* Use of list (i.e. data structure) instead of List (i.e. from Typing) in capture_split_info.
* Added validation for AutoOptimizerConfig and also resolve in data_config member references
* Moved function to identify a module as ONNX (vs. PyTorch) in package config. This is now needed in AutoOptimizer as well.
=> Fixing a few issues found over the course of implementing auto_optimizer

.azure_pipelines/olive-ci.yaml, examples/phi3_5/README.md, examples/phi3_5/requirements.txt
=> Make QNN llm instructions clearer

.azure_pipelines/job_templates/huggingface-login-template.yaml, .azure_pipelines/job_templates/olive-example-win-template.yaml, .azure_pipelines/job_templates/olive-test-cpu-template.yaml, .azure_pipelines/job_templates/olive-test-linux-gpu-template.yaml, .azure_pipelines/scripts/run_test.sh
=> login hf for pipeline

examples/bert/README.md, examples/bert/google_bert_qdq.json
Update google bert example with DynamicToFixedShape pass and ReplaceAttentionMaskValue surgery
=> Update google bert example

docs/source/reference/options.md, docs/source/reference/pass.rst, examples/sample/onnxscript_fusion_sample.json, olive/olive_config.json, olive/passes/onnx/onnxscript_fusion.py, test/unit_test/passes/onnx/test_onnxscript_fusion.py
The first attempt to establish onnx-script fusions to Olive.
=> [Fusion] ONNX script fusion

docs/source/how-to/index.rst
=> Docs: Fix path to custom-model-evaluator

examples/llama2/llama2_lmeval_onnx.json, olive/evaluator/lmeval_onnx_model.py, olive/evaluator/olive_evaluator.py, olive/passes/olive_pass.py, olive/workflows/run/config.py, olive/workflows/run/run.py
Also, handle non-existent "passes" key in workflow config gracefully.
=> Implement lmeval based evaluator for ONNX GenAI models

olive/passes/onnx/onnxscript_fusion.py, requirements.txt
In 0.2.4 onnxscript updated its api for optimize_for_ort. This PR removes the compatibility branch and updated the onnxscript dependency requirement so users are always leveraging the updated features.
=> Update onnxscript_fusion to match the latest onnxscript API

olive/cli/capture_onnx.py, olive/passes/onnx/conversion.py, test/unit_test/cli/test_cli.py
1. Update default conversion opset.2
2. add --static to capture-onnx-graph cli to export static input shape onnx model.
=> Update default conversion opset & add --static to conv cli

docs/source/features/onnx-transformations.md, olive/passes/onnx/graph_surgeries.py, olive/passes/onnx/onnx_dag.py, test/unit_test/passes/onnx/test_graph_surgeries.py
Add MatMulAddGemm Graph Surgery to transform Add Op followed by Matmul as Gemm op
Contributed by @gnedanur, #1745
=> Add MatMulAddGemm Graph Surgery

docs/source/features/ihv-integration/openvino.md, docs/source/reference/options.md, docs/source/reference/pass.rst, olive/olive_config.json, olive/passes/openvino/io_update.py, test/requirements-test.txt, test/unit_test/passes/openvino/test_openvino_encapsulation.py, test/unit_test/passes/openvino/test_openvino_io_update.py
=> Openvino: Update docs and rename reshape pass to IoUpdate pass

examples/bert/openvino/bert_base_uncased_mrpc/README.md, examples/bert/openvino/bert_base_uncased_mrpc/bert-base-uncased-mrpc_context_ov_static.json, examples/bert/openvino/bert_base_uncased_mrpc/requirements.txt, examples/bert/openvino/bert_base_uncased_mrpc/user_script.py
=> adding bert example

.azure_pipelines/job_templates/olive-example-linux-template.yaml, .azure_pipelines/scripts/find_failed_commit.py, olive/platform_sdk/qualcomm/configure/configure.py, pyproject.toml, requirements-dev.txt
=> Fix remaining lint errors

examples/vit/imagenet.py
Updating Mean standard deviation for Google Vit to improve accuracy. .77 -> .82
values used for this model can be found here: https://huggingface.co/google/vit-base-patch16-224/blob/main/preprocessor_config.json
=> Updating Mean standard deviation for Google Vit

olive/cli/convert_adapters.py, olive/passes/onnx/quantization.py, test/unit_test/passes/onnx/test_mnb_to_qdq.py
onnxruntime uses MatMulNBitsQuantizer since 1.22.0, due to https://github.com/microsoft/onnxruntime/pull/24472/
=> Adapt to MatMulNBitsQuantizer

olive/passes/onnx/quantization.py, test/requirements-test-cpu.txt, test/requirements-test.txt
=> Fix nightly pipeline

docs/source/how-to/configure-workflows/build-workflow.md, docs/source/how-to/configure-workflows/engine-configuration.md, docs/source/how-to/index.rst, olive/engine/config.py, olive/workflows/run/config.py
=> Document steps to build a Olive workflow from scratch

olive/passes/openvino/encapsulation.py
Add code to generate genai_config.json for ORT GenAI models in OpenVINO Encapsulation pass.
=> Generate GenAI config in OpenVINO Encapsulation pass

examples/bert/openvino/bert_base_uncased_mrpc/bert-base-uncased-mrpc_context_ov_static.json, olive/passes/openvino/io_update.py
=> Intel bert custom names

olive/passes/openvino/encapsulation.py
Refactor pad_token_id handling in create_genai_config function
=> Pad token id fix in OV Encapsulation pass

examples/resnet/openvino/resnet_context_ov_static.json, examples/vit/openvino/vit_base_patch16_224_context_ov_static.json
These 2 examples have user scripts that will use `cache` to cache dataset. Using the same cache folder for workflow.
=> Unify example cache folder

examples/resnet/openvino/resnet_context_ov_static.json, examples/vit/openvino/vit_base_patch16_224_context_ov_static.json
=> Lint: Fix lint issues

examples/bert/README.md, examples/clip/README.md, examples/deepseek/README.md, examples/llama3/README.md, examples/phi3_5/README.md, examples/qwen2_5/README.md, examples/resnet/README.md, examples/resnet/imagenet.py, examples/resnet/resnet_ptq_qdq_vitis_ai.json, examples/vit/README.md, olive/olive_config.json, olive/passes/onnx/vitis_ai/preprocess.py
- Update ResNet50 Recipe (change input from NCHW to NHWC)
- README updates for VitisAI examples
=> [VitisAI] Update Resnet50 recipe, READMEs

examples/README.md
=> Examples: Note about torch with CUDA on Windows

docs/source/how-to/index.rst
Fixes non-existent link created by #1840
=> Doc: remove invalid link to custom-model-evaluator

examples/deepseek/openvino/DeepSeek-R1-Distill-Qwen-1.5B_context_ov_dynamic_sym_gs128_bkp_int8_sym_r1.json, examples/phi3_5/openvino/Phi-3.5-mini-instruct_context_ov_dynamic_sym_gs128_bkp_int8_sym.json, examples/phi4/openvino/phi_4_reasoning/Phi-4-reasoning_context_ov_dynamic_sym_gs128_bkp_int8_sym.json, examples/phi4/openvino/phi_4_reasoning_plus/Phi-4-reasoning-plus_context_ov_dynamic_sym_gs128_bkp_int8_sym.json, examples/qwen2_5/openvino/Qwen2.5-1.5B-instruct_context_ov_dynamic_sym_bkp_int8_sym_r1.json
=> Change quantization info to improve accuracy

docs/source/reference/options.md, docs/source/reference/pass.rst
Fix broken links in options doc.
=> Fix broken links in options doc

.azure_pipelines/olive-ci.yaml, test/requirements-test-cpu.txt, test/requirements-test.txt
=> Pin onnxruntime 1.21.1

olive/passes/openvino/encapsulation.py
Refactor pad_token_id assignment logic in create_genai_config function
=> OpenVINO Encapsulation pad_token_id fix

olive/__init__.py, olive/common/ort_inference.py
=> patch to support winml

olive/olive_config.json, test/requirements-test.txt
=> Copy of #1862

olive/passes/onnx/conversion.py, olive/passes/pytorch/tensor_parallel.py
Small PR - Evaluates and displays the model type on error.
=> Display model type on error

olive/__init__.py
Bump up dev version to 0.10.0.dev0
=> Bump up dev version to 0.10.0.dev0

.azure_pipelines/olive-ci.yaml
Reenable win integ test in pipeline
=> Reenable win integ test in pipeline

.azure_pipelines/olive-ci.yaml, olive/cli/convert_adapters.py
=> Correct `quantize_matmul_4bits` import in `convert-adapter` cli

olive/passes/onnx/peephole_optimizer.py
Do not discard model optimized by onnxscript optimizer
=> Do not discard model optimized by onnxscript optimizer

olive/passes/openvino/encapsulation.py, requirements.txt
fix ir version for openvino encapsulation pass
=> fix ir version for openvino encapsulation pass

.azure_pipelines/olive-ort-nightly.yaml
Was accidentally removed in #1884.
=> CI: Use ort nightly in nightly linux cpu example test

requirements.txt
Bump version to ensure package interop compatibility.
=> Update onnxscript and onnx_ir requirements

olive/passes/onnx/context_binary.py
=> Context binary generator: Only support regular ort

olive/passes/onnx/hqq_quantization.py, olive/passes/onnx/rtn_quantization.py, test/unit_test/passes/onnx/test_hqq_quantization.py, test/unit_test/passes/onnx/test_rtn_quantization.py
1. Remove `HqqQuantizer`.
1. Add onnxruntime import check.
1. Remove duplicated unit tests.
=> Refactor hqq quantization pass

docs/source/how-to/configure-workflows/systems.md
Update document about run job on AML system
=> Update document about run job on AML system

test/unit_test/passes/onnx/test_graph_surgeries.py, test/unit_test/passes/onnx/test_trt_dla_transforms.py
=> Pin model ir for tests

docs/source/features/azure-ai/azure-ai.md, docs/source/features/azure-ai/azure-arc.md, docs/source/features/azure-ai/azure-script.md, docs/source/features/azure-ai/remote-workflow.md, docs/source/how-to/configure-workflows/systems.md, olive/systems/azureml/aml_system.py, olive/workflows/run/run.py
=> Add AML deprecation warning

olive/common/ort_inference.py
Version 1.22.1 released and fails this check. Check for >= 1.23 instead and include nightlies.
=> Ort Auto-EP version check fix

olive/passes/onnx/model_builder.py
Add the NvTensorRTRTXExecutionProvider for model builder
=> Add the NvTensorRTRTXExecutionProvider for model builder

examples/directml/llm/README.md, examples/llama2/llama2_multilora.ipynb, examples/phi2/phi2.py, examples/stable_diffusion/README.md, examples/stable_diffusion/notebook/sd_multilora.ipynb, examples/stable_diffusion_xl/README.md, olive/hardware/constants.py, olive/systems/python_environment/python_environment_system.py, olive/systems/utils/misc.py, olive/workflows/run/run.py
=> Remove references to ort-nightly

docs/source/how-to/index.md
- H1 is #
- Markdown relative links don't support .html
- files need to be referenced in some toctree
=> Doc: Fix how-to doc

olive/passes/onnx/peephole_optimizer.py
=> Fix peephole optimizer bug

README.md
=> Add docs pipeline status to Readme

olive/model/handler/onnx.py
Remove dead code that uses get_available_provider() from ORT
=> Remove dead code

olive/olive_config.json
Fix OnnxStaticQuantization ep and gpu config. OnnxStaticQuantization is not limited to cpu.
=> Fix OnnxStaticQuantization ep and gpu config

olive/common/hf/quant.py, olive/common/quant/linear.py, olive/passes/pytorch/autogptq.py, olive/passes/pytorch/gptq.py, olive/passes/pytorch/selective_mixed_precision.py, test/unit_test/passes/onnx/test_conversion.py, test/unit_test/passes/pytorch/test_selective_mixed_precision.py
=> Gptq: Use native precision + export support, SelectiveMP: Include all qkv

docs/source/features/onnx-transformations.md, olive/constants.py, olive/passes/onnx/graph_surgeries.py, test/unit_test/passes/onnx/test_graph_surgeries.py
Add QuickGeluToSigmoid surgery. Lower QuickGelu to Mul + Sigmoid + Mul: `QuickGelu(x) = x * sigmoid(alpha * x)`
=> Add QuickGeluToSigmoid surgery

olive/olive_config.json, olive/passes/onnx/mnb_to_qdq.py, olive/passes/pytorch/gptqmodel.py
Added a new Olive pass for GPTQ quantization for QNN
=> Add GptqModel Olive pass for QNN

examples/bert/qnn/requirements.txt, examples/clip/qnn/requirements.txt, examples/resnet/qnn/requirements.txt, examples/vit/qnn/requirements.txt
- Fixed datasets version to 3.6.0 as trust_remote_code is removed in newer version
- Added pillow
- Added scikit-learn
=> Updated requirements of QNN example recipes

docs/source/how-to/cli/cli-optimize.md, docs/source/how-to/index.md
Document how to use `optimize` command
=> Add a doc on how to use `optimize` command

olive/cli/optimize.py
- enable symmetric Gptq quantization if data type is signed
- StaticQuantization quant format doesn't depend on gptq
- Static Quantization excludes common contrib ops which are expected to run on CPU and don't require further quantization around them.
=> Optimize: Gptq symmetric, StaticQuantization QDQ

examples/amd_olmo/vitisai/AMD-OLMo-1B-SFT-DPO_quark_vitisai_llm.json, examples/deepseek/vitisai/DeepSeek-R1-Distill-Llama-8B_quark_vitisai_llm.json, examples/deepseek/vitisai/DeepSeek-R1-Distill-Qwen-1.5B_quark_vitisai_llm.json, examples/deepseek/vitisai/DeepSeek-R1-Distill-Qwen-7B_quark_vitisai_llm.json, examples/llama2/vitisai/Llama-2-7b-chat-hf_quark_vitisai_llm.json, examples/llama2/vitisai/Llama-2-7b-hf_quark_vitisai_llm.json, examples/llama3/vitisai/Llama-3.2-1B-Instruct_quark_vitisai_llm.json, examples/llama3/vitisai/Llama-3.2-3B-Instruct_quark_vitisai_llm.json, examples/llama3/vitisai/Meta-Llama-3-8B_quark_vitisai_llm.json, examples/llama3/vitisai/Meta-Llama-3.1-8B_quark_vitisai_llm.json, examples/mistral/vitisai/Mistral-7B-Instruct-v0.2_quark_vitisai_llm.json, examples/mistral/vitisai/Mistral-7B-Instruct-v0.3_quark_vitisai_llm.json, examples/phi3/vitisai/Phi-3-mini-128k-instruct_quark_vitisai_llm.json, examples/phi3/vitisai/Phi-3-mini-4k-instruct_quark_vitisai_llm.json, examples/phi3_5/vitisai/Phi-3.5-mini-instruct_quark_vitisai_llm.json, examples/phi4/vitisai/Phi-4-mini-instruct_quark_vitisai_llm.json, examples/phi4/vitisai/Phi-4-mini-reasoning_quark_vitisai_llm.json, examples/qwen2_5/vitisai/Qwen1.5-7B-Chat_quark_vitisai_llm.json, examples/qwen2_5/vitisai/Qwen2-7B-Instruct_quark_vitisai_llm.json, examples/qwen2_5/vitisai/Qwen2.5-0.5B-Instruct_quark_vitisai_llm.json, examples/qwen2_5/vitisai/Qwen2.5-1.5B-Instruct_quark_vitisai_llm.json, examples/qwen2_5/vitisai/Qwen2.5-7B-Instruct_quark_vitisai_llm.json, examples/qwen2_5/vitisai/Qwen2.5-Coder-0.5B-Instruct_quark_vitisai_llm.json, examples/qwen2_5/vitisai/Qwen2.5-Coder-1.5B-Instruct_quark_vitisai_llm.json, examples/qwen2_5/vitisai/Qwen2.5-Coder-7B-Instruct_quark_vitisai_llm.json, olive/olive_config.json, olive/passes/quark_quantizer/quark_quantization.py
Rename QuarkQuantizationPass to QuarkQuantization
=> Rename QuarkQuantizationPass to QuarkQuantization

examples/phi3/qnn/phi3_mini_128k_instruct_qnn_config.json, examples/phi3/qnn/phi3_mini_4k_instruct_qnn_config.json, examples/phi3_5/qnn_config.json, examples/phi4/qnn/phi4_mini_instruct_qnn_config.json, examples/qwen2_5/qnn/qwen_2.5_1.5b_instruct_qnn_config.json
=> Perf optimizations for QNN

olive/passes/onnx/aimet_quantization.py, test/passes/onnx/test_aimet_quantization.py
Support excluding op types from quantization in AimetQuantization pass.
=> Support excluding op types in aimet quantization pass

olive/common/config_utils.py, olive/model/config/io_config.py, olive/passes/onnx/inc_quantization.py
While working on https://github.com/microsoft/Olive/pull/1765, I realized that some typing annotations and error behavior can be improved. I isolated the changes here as a separate PR.
=> Improve typing in config and error behavior

olive/passes/onnx/aimet_quantization.py, test/passes/onnx/test_aimet_quantization.py
Add support for LPBQ quantization to aimet pass.
=> Add LPBQ support to aimet quantization pass

olive/passes/onnx/graph_surgeries.py, test/requirements-test.txt
1. Fix onnx 1.19.0 issue in graph surgery
1. Pin onnx version in test requirements.txt
=> Fix onnx 1.19.0 issue in graph surgery

docs/source/features/quantization.md
=> Remove invalid link from docs

olive/cli/api.py, olive/cli/run.py, olive/engine/engine.py, test/engine/test_engine.py, test/workflows/test_setup.py
Also, don't fail the entire workflow if one of the samples during search throws an exception.
=> CLI commands are expected to return workflow output

docs/source/reference/python_api.md, olive/cli/run.py, olive/systems/docker/workflow_runner.py, olive/workflows/run/run.py, test/cli/test_cli.py, test/workflows/test_setup.py, test/workflows/test_workflow_run.py
Deprecate logic to install required packages and replace it with option to list required packages.
=> Deprecate setup CLI option

olive/model/handler/pytorch.py
=> Fix slicegpt bug

examples/deepseek/README.md, examples/deepseek/qnn/DeepSeek_R1_Distill_Qwen_1.5B_qnn_config.json, examples/llama3/README.md, examples/llama3/qnn/llama3.1_8b_instruct_qnn_config.json, examples/llama3/qnn/llama3.2_1b_instruct_qnn_config.json, examples/phi3_5/README.md, examples/phi3_5/requirements.txt, examples/phi4/README.md, examples/qwen2_5/README.md, examples/qwen2_5/qnn/qwen_2.5_7b_instruct_qnn_config.json
=> QNN: Pin AOT ort-qnn version to 1.22.2

docs/source/_static/versions.json
=> Doc: Increment latest version in versions.json

.azure_pipelines/job_templates/olive-test-cpu-template.yaml, .azure_pipelines/job_templates/olive-test-linux-gpu-template.yaml
- We no longer have Azure ML and integration tests so these variables are not required.
=> CI: Remove unused env vars

docs/source/features/ihv-integration/openvino.md, docs/source/reference/options.md, docs/source/reference/pass.rst, olive/olive_config.json, olive/passes/openvino/compression.py, olive/passes/openvino/quantization.py, test/passes/openvino/test_openvino_compression.py, test/requirements-test.txt
Introduce OpenVINO Weight Compression Pass. This pass performs Weight Compression on Hugginface models to produce OpenVINO or ONNX models, as well as on ONNX models to produce ONNX models using Intel® NNCF compress_weights() functionality.
---------
=> Introduce Intel® OpenVINO Weight Compression Pass

olive/cli/quantize.py, olive/constants.py, olive/olive_config.json, test/cli/test_cli.py
Adds support for AIMET algorithms to quantize CLI
=> Enable AIMET in olive quantize CLI
