docker-images/onnx-converter/README.md, docker-images/onnx-converter/requirements.txt
- Fix Keras dependency as pointed out in #15 
- Fix tensorflow version to 1.14 as the newest Tensorflow version is incompatible with the other packages.
- Updated mcr.microsoft.com/onnxruntime/onnx-converter to reflect the changes.
=> Fix onnx-converter image dependency

docker-images/perf-tuning/Dockerfile, docker-images/perf-tuning/build_perf_tuning.py, docker-images/perf-tuning/src/perf_tuning.py
Steps to try it out:
1. Build onnxruntime with Nuphar:
```
python ./build_perf_tuning.py --onnxruntime_home /path/to/ort --use_nuphar
```
You may specify --llvm_path /path/to/llvm-build/lib/cmake/llvm if llvm is not found. Linux prebuilt could be downloaded [here](http://releases.llvm.org/download.html)
2. build docker image with onnxruntime binaries:
```
cd /OLive_root/docker-images/perf-tuning
docker build -t perf_tuning -f Dockerfile .
```
3. run symbolic shape inference on input model using the image (mounting data which holds the models):
```
docker run -v ~/data:/data --entrypoint python3.7 -t perf_tuning /perf_tuning/bin/RelWithDebInfo/all_eps/symbolic_shape_infer.py --input /data/path/to/model --output /data/path/to/shape_inferred_model --auto_merge
```
4. run perf_tuning with …
=> Initial support for Nuphar execution provider

docker-images/onnx-converter/Dockerfile, docker-images/onnx-converter/requirements.txt, docker-images/onnx-converter/src/onnx_converter.py, docker-images/perf-tuning/build_perf_tuning.py, docker-images/perf-tuning/src/maps.py, docker-images/perf-tuning/src/perf_tuning.py, web/frontend/package-lock.json, web/frontend/src/components/ConvertResult.vue
- Updated `mcr.microsoft.com/onnxruntime/onnx-converter` docker image to use the latest converter modules.
- Updated `mcr.microsoft.com/onnxruntime/perf-tuning` to use build onnxruntime 1.1.2
- Set "-x 1" when tuning OMP_NUM_THREADS
- Fix code snippet to correctly generate code for parallel execution mode
- Add OMP environment variables tuning for Nuphar, DNNL and nGraph
- Tune "-x" in sequential execution mode before parallel execution mode
- Fixed support for Nuphar execution provider. 
- Build Nuphar with MKLML instead of MLAS.
- Use OpenMP environment variables for Nuphar thread pool tuning. 
- Improved web app UI to generate model download link in onnx-converter even when the inputs are not successfully generated
=> Update onnx-converter and perf-tuning to onnxruntime 1.1.2

docker-images/perf-tuning/build_perf_tuning.py, docker-images/perf-tuning/src/perf_tuning.py
Build nGraph execution provider separately from other execution providers in `build_perf_tuning.py` in `perf-tuning` image. This change is to avoid possible nGraph build compatibility issue under different CPUs. 
Updated `mcr.microsoft.com/onnxruntime/perf-tuning` docker image to reflect this change.
=>  Build nGraph Separately in Perf-tuning Docker Image

docker-images/perf-tuning/Dockerfile, docker-images/perf-tuning/README.md, docker-images/perf-tuning/build_perf_tuning.py, docker-images/perf-tuning/src/perf_tuning.py, web/readme.md
- Update perf-tuning docker image
- Update to use ONNX Runtime 1.2.0 build
- Update perf-tuning docker image to use CUDA 10.2 to meet the ONNX Runtime 1.2.0 requirements
- Update README to reflect the latest Docker command - "--runtime=nvidia" --> "--gpus all"
- Tune threads up to number of logical cores instead of number of physical cores.
- Add unsetting all OMP environment variables to perf test candidates in the OpenMP enabled execution providers
=> Update Docker Images to use ONNX Runtime 1.2.0

utils/onnxpipeline.py, web/backend/app.py, web/backend/app_config.py, web/frontend/src/App.vue, web/frontend/src/components/Convert.vue, web/frontend/src/components/ConvertResult.vue, web/frontend/src/components/Perf.vue, web/frontend/src/components/PerfResult.vue, web/frontend/src/utils/const.js
- Previously the "perf-tuning" feature in the web app only supports running with model from the most recent "convert" run. This PR extends this feature to supporting all previously successful "convert" runs.
- Disable "upload input" button by default if previously converted model and test data are used for the perf run.
- Update paths to render better ui for Windows
=> Web App Perf-tuning Support Job Selection From Previous Step

docker-images/onnx-converter/README.md, utils/convert_test_data.py, web/backend/app.py, web/frontend/src/components/Convert.vue, web/frontend/src/components/ConvertResult.vue, web/frontend/src/components/PerfResult.vue
This PR adds a script (utils/convert_test_data.py) to convert pickle test data file to ONNX .pb files as an alternative data format for onnx-converter and perf-tuning test data. A valid pickle file should be stored from a dictionary like the following
{
"input_name_0": test_input_np
...
}
This PR also enables web app support for the feature above. User may upload a pickle file instead of pb files in the "convert" and "perf" steps.
=> Support Pickle Files As Test Data Format Alternative in Web App

docker-images/onnx-converter/README.md, docker-images/onnx-converter/requirements.txt, docker-images/onnx-converter/src/create_input.py, docker-images/onnx-converter/src/onnx_converter.py, docker-images/perf-tuning/README.md
- Add test_data_path to `onnx-converter` docker image. This allows user to specify test data folder if not in the same folder as the input model file. The test data in the user specified folder will then be copied over to the  `onnx-converter` output folder so that the folder will have the following format that is ready to be consumed by the `perf-tuning` image. 
```
-- output_folder 
-- model.onnx 
-- test_data_set_0
-- input_0.pb
...
-- test_data_set_1
...
...
```
- Update `onnx-converter` dependency to use latest packages
- Update README for instructions on how to generate pb files from PICKLE file using python script.    
These changes have been reflected in the latest `mcr.microsoft.com/onnxruntime/onnx-converter` public docker image and ready for use.
=> Add test_data_path Parameter to onnx-converter

docker-images/perf-tuning/Dockerfile, docker-images/perf-tuning/build_perf_tuning.py, docker-images/perf-tuning/src/perf_tuning.py
Necessary updates in `perf-tuning`  docker image according to the ONNX Runtime 1.3.0 release. 
- Separate build for execution provider "cpu" and "cpu_openmp"
- Remove deprecated setting --intra_op_num_threads = 1 when using openmp. 
- Update necessary dependencies for building onnxruntime with `build_perf_tuning.py`
=> Updates in Perf-Tuning Image For ORT 1.3.0

.gitignore, olive/__main__.py
If olive is invoked without any parameters it throws an exception. This PR fixes that.
I also updated .gitignore to include files to ignore during local development.
=> Fixed exception when olive is invoked without parameters

olive/web/backend/app.py
I had submitted a security disclosure earlier via huntr.io . Since that has remained pending for quite some time now, I am sending a PR with the proposed fix.
There is a path traversal bug in this project due to the use of `os.path.join` call with untrusted input. This can be fixed by using `flask.safe_join` instead.
=> use `flask.safe_join` instead of `os.path.join`

docs/source/overview/options.md, olive/cache.py, olive/engine.py, olive/workflows/run/config.py, olive/workflows/run/run.py, test/unit_test/test_cache.py, test/unit_test/test_engine.py, test/unit_test/utils.py
This PR adds support for running passes without search strategy. If `search_stategy` is `None`, the passes are run on the input_model and the final output model is evaluated if there is a valid evaluator. The output of the run is the final output model and evaluation results. 
Added tests for the new functionalities introduced. 
Updated relevant pre-existing tests.
=> Support run with no search strategy

docs/source/overview/options.md, olive/engine.py, olive/workflows/run/config.py, olive/workflows/run/run.py, test/unit_test/test_engine.py
This PR adds an `evaluation_only` boolean option to engine run and `olive.workflows.run`. When `True` the input model is evaluated, and the result is returned. 
Added `test_run_evaluation_only` to `test_engine`.
=> Add `evaluation_only` option to run 

docs/architecture.md, docs/source/overview/options.md, docs/source/overview/quicktour.md, docs/source/tutorials/advanced_users.md, docs/source/tutorials/configure_pass.rst, docs/source/tutorials/passes/onnx.md, examples/bert_ptq_cpu/bert_config.json, examples/quantization_aware_training/bert_qat_customized_train_loop_cpu/bert.py, examples/quantization_aware_training/bert_qat_customized_train_loop_cpu/bert_config.json, examples/quantization_aware_training/resnet_qat_default_train_loop_cpu/resnet.py, examples/quantization_aware_training/resnet_qat_lightning_module_cpu/resnet.py, examples/resnet_ptq_cpu/resnet_config.json, examples/resnet_ptq_cpu/resnet_dynamic_config.json, examples/resnet_ptq_cpu/resnet_static_config.json, examples/snpe/inception_snpe_qualcomm_npu/inception_dev.py, examples/snpe/vgg_snpe_qualcomm_npu/vgg.py, olive/common/config_utils.py, olive/passes/olive_pass.py, olive/passes/pass_config.py, olive/workflows/run/config.py, olive/workflows/snpe/convertquantize/convertquantize.py, test/integ_test/aml_model_test/test_aml_model.py, test/unit_test/test_engine.py, test/unit_test/utils.py
This PR changes `default_to_search` to `disable_search` to make the purpose of the parameter clear. When `disable_search` is `False`, the pass config parameters uses the searchable values (if any) while they use the default fixed values if `True`. The default value for `disable_search` is `False`. 
In `olive.workflows.run`, if there is a search strategy, the passes have `disable_search` as `False` unless the user explicitly sets it to `True`. If there search strategy is None, `disable_search` is always `True` and user cannot override it.
=> Change `default_to_search` -> `disable_search`

olive/common/config_utils.py, olive/workflows/run/config.py, olive/workflows/run/run.py
We use pydantic models for our config classes. By default, pydantic models ignore parameters that are not part of the config class. This is a desirable feature but we should warn the user if the config dict they provided has such parameters.
=> Warn about parameters that are not part of config

olive/strategy/search_results.py, olive/strategy/search_strategy.py
When chosing the best models, we apply goals to filter the models. However, in the pass-by-pass execution order, the intermediate models might not meet goals. This causes the search to crash like in the recent CI failures. 
In this PR, we instead warn the user about the goal not being met and sort the models without applying goals so that the search can proceed. 
Also, updated the model sorting logic to fix a mistake in the previous implementation. The comment above the new logic explains the steps used.
=> Search Strategy: Sort models without goals if no model meets goals, Fix sorting bug

examples/resnet_ptq_cpu/prepare_model_data.py, examples/test_resnet_ptq_cpu.py
The pytorch model for resnet example is trained in `prepare_model_data.py`. Because of randomness during training, the model is not the same between ci runs and causes inconsistent behavior. Set random seed before training so that the pytorch model is the not random.
=> Set seed before training resnet model

docs/source/api/passes.rst, docs/source/tutorials/passes/onnx.md, olive/passes/onnx/float16_conversion.py
- Updates docs to include `OnnxFloatToFloat16`
- Both `op_block_list` and `node_block_list` should default to `None`.
=> Update docs on ONNX FP16 pass and fix defaults

olive/passes/onnx/quantization.py
This PR exposes the shared (dynamic and static) `extra_options` parameters. We also provide a parameter called `extra_options` where an advanced user can provide additional extra options. If an option is already exposed, the value of the exposed parameter overwrites the value in the `extra_options` dict. 
Fixes #139
=> Expose some `extra_options` in Onnx quantization passes 

olive/model.py, olive/passes/onnx/conversion.py, olive/passes/onnx/float16_conversion.py, olive/passes/onnx/model_optimizer.py, olive/passes/onnx/quantization.py, olive/passes/onnx/transformer_optimization.py, olive/passes/snpe/snpe_to_onnx.py
Large models cannot be converted into a fully self-contained .onnx file (protobuf has a limit of 2GB), so the ONNX format allows tensor data to be stored as [external data](https://github.com/onnx/onnx/blob/main/docs/ExternalData.md) files on disk. The call to `torch.onnx.export` will write external data automatically when the graph and tensor data won't fit into a single .onnx file. This creates a problem for Olive, since output models are saved into a shared cache directory: the filenames of external data are based on the tensor names in the graph, so multiple passes on an ONNX model could collide and overwrite the data files.
Two potential solutions came to mind:
1. Have passes write ONNX files to subdirectories of the cache; the subdirectory has the .onnx file and potentially external …
=> Support external data in PyTorch-to-ONNX conversion pass

olive/passes/onnx/conversion.py, olive/systems/azureml/aml_evaluation_runner.py, olive/systems/azureml/aml_pass_runner.py, olive/systems/azureml/aml_system.py, olive/systems/utils.py, test/unit_test/systems/azureml/test_aml_system.py
This PR adds support for ONNX models with external data for AzureML systems (both model evaluation and pass run). 
It also uses a temporary directory for onnx model conversion since the output model path or it's parent could be used by other processes if not provided carefully. 
`all_tensors_to_one_file` default value is now `True` like it is for `onnx.save_model`. This is beneficial since there is only one external data file. Also, for models with unsupported tensor names, the external data files have randomly generated names which is not ideal.
=> Handle ONNX model with external data for AzureML systems

olive/passes/onnx/quantization.py
`_exposed_extra_options_config` keys were printed as set before but the set does not have the keys in the same order every time. So, the doc gets updated everytime even though the keys are the same.
=> Print `_exposed_extra_options_config` keys as list instead of set

olive/engine/__init__.py, olive/engine/footprint.py
Currently, when checking if a point is dominated or not, we check if all values for current points are less than those for another points. However, this adds points to the pareto frontier that should not be present. For instance, points `[1,1]`, `[2,1]` are both present even though `[2,1]` is better. So we replace with `<=` and also check for equality.
Mathematically speaking, `<` might be more correct but it looks like `<=` is more used in practice. Optuna also does the same https://github.com/optuna/optuna/blob/master/optuna/study/_multi_objective.py#L72
Before 
After
=> Pareto frontier: check for `<=` instead of `<`

olive/engine/footprint.py
This PR makes sure only candidate models are considered when finding the pareto frontier model.
=> Only include candidate models in pareto frontier

examples/directml/stable_diffusion/config_unet.json, olive/cache.py, olive/passes/onnx/common.py, olive/passes/onnx/conversion.py, olive/passes/onnx/float16_conversion.py, olive/passes/onnx/model_optimizer.py, olive/passes/onnx/quantization.py, olive/passes/onnx/transformer_optimization.py, olive/passes/snpe/snpe_to_onnx.py, olive/snpe/tools/dev.py
Due the limit of protobuf, large onnx models (>2GB) cannot be saved to a single onnx file. The tensors must be saved to an external data file. Our onnx related passes do not handle this case. 
This PR adds options for user to specify whether to save as external data or not. If the model is too large, we override the user's configuration and save as external data regardless. A warning is also generated to inform the user of this. This ensures that the pass doesn't fail when saving the onnx model to file.  
The model save logic is based on a similar implementation by onnxruntime https://github.com/microsoft/onnxruntime/blob/main/onnxruntime/python/tools/transformers/onnx_model.py#L947 but with more control on the name of the external data file.
=> Support external data for all onnx passes

olive/evaluator/metric_config.py
These arguments should not be treated as object.
=> modify args

olive/evaluator/evaluation.py
When run Olive in gpu device, the evaluation will put the model in cuda, but forget to return back to cpu when evaluation is done. It caused conversion failed.
=> reset model to cpu after evaluation on gpu

olive/evaluator/evaluation.py
no need to create dummy dataloader if user providers eval function
=> remove dummy dataloader when user provides eval function

examples/test_bert_ptq_cpu.py, examples/test_resnet_ptq_cpu.py, olive/evaluator/evaluation.py, olive/passes/onnx/conversion.py
To avoid the case where user define the customized evaluation functions and forget to reset the device back to cpu.
Further fix for PR: https://github.com/microsoft/Olive/pull/177
=> dummy inputs to cpu & model to cpu before conversion

docs/requirements.txt, docs/source/api/metric.rst, docs/source/api/systems.rst, docs/source/conf.py
`enum-tools` has GPL requirement which causes security compliance issue. So, removing it from docs requirement.
=> Remove `enum-tools` from docs requirement

examples/resnet_ptq_cpu/resnet_config.json, examples/resnet_ptq_cpu/user_script.py, olive/evaluator/metric_config.py, olive/passes/onnx/perf_tuning.py
1. When construct the latency metrics configs, it lost several configs like 'user_scirpts'. And the list is hard coded in perf-tuning which can crash again if we change the metrics schema in the future.
2. Enhance the e2e ResNet tests to make it cover the above failed case.
3. typos fix
=> bugfix for latency metrics config in perf tuning

examples/resnet_ptq_cpu/resnet_config.json, olive/evaluator/evaluation.py, olive/passes/onnx/perf_tuning.py
1. Align the batch_size for olive examples, which inconsistency bring gap for perf_tuning metrics and olive evaluations. 
3. Refine perf-tuning's messy logger info.
=> bugfix: perf_tuning batch size != latency.batch_size

docs/source/exts/auto_config_doc/__init__.py, olive/passes/olive_pass.py, olive/passes/pass_config.py, olive/systems/azureml/aml_pass_runner.py
Since, we will be updating `pass.default_config` to take in the accelerator specs to generate the search space, it is not available inside the pass itself or before we know the accelerato specs. 
This PR removes such references by storing the instance of `default_config` that created the specific pass object as a private attribute of the `config_class`. 
Also added TODO for places where we have to update calls to `default_config` by providing the relevant accelerator specs.
=> Remove direct use of pass.default_config()

olive/model.py, olive/passes/olive_pass.py, olive/systems/local.py
Introduce CompositeOnnxModel to represent models with encoder and decoder subcomponents as individual OnnxModels.
Separate PRs will introduce support for creating CompositeOnnxModel and converting CompositeOnnxModel into a OnnxModel
=> Introduce CompositeOnnxModel

examples/bert_ptq_cpu/bert_config.json, examples/test_bert_ptq_cpu.py, olive/systems/docker/dev_mount_cleanup.py, olive/systems/docker/docker_system.py, olive/systems/docker/utils.py, olive/systems/system_config.py, test/integ_test/evaluator/docker_eval/utils.py, test/unit_test/systems/docker/test_docker_system.py
Add `dev` mode for `DockerSystem` so that we don't need to keep updating the dockerfiles with dev branches. Works similar to `AzureMLSystem` dev mode where a copy of the project directory is mounted to the same directory as the evaluation script runner. 
It also cleans up the mounted directory since the evaluation call creates `__pycache__` which cannot be deleted automatically by the host due to docker running with higher privileges.
=> `dev` mode for `DockerSystem`

examples/whisper/user_script.py, examples/whisper/whisper_template.json, olive/common/ort_inference.py, olive/evaluator/evaluation.py, olive/model.py, olive/passes/onnx/append_pre_post_processing_ops.py
Add dataloader for whisper example and evaluator. 
The model has onnxruntime-extensions ops, so this PR introduce an option in ONNXModel to use onnxruntime-extensions during creation of inference sessions.
=> add whisper evaluation

olive/passes/onnx/conversion.py
Remove the deepcopy of the pytorch model before conversion. This was added unintentionally after testing it during the whisper model debug. It breaks the stable diffusion example and is not needed.
=> Remove deepcopy before model conversion

examples/test_bert_ptq_cpu.py, examples/test_resnet_ptq_cpu.py, examples/test_whisper.py
Sometimes, the example tests fail because the setups (preparing model, data, config, etc) fail randomly. Retry the test setups to catch such errors. 
Test fixtures are also updated to make them simpler and consistent across examples.
=> Retry test setup for example tests

examples/test_bert_ptq_cpu.py
Skip docker system test for bert example until bug is fixed: https://github.com/docker/docker-py/issues/3113
=> Skip docker system test for bert example

examples/whisper/requirements.txt
Onnx 1.14.0 was just released. However, the whisper example doesn't work it due to IR version mismatch between the components in the prepostprocessing step. So, pinning the onnx version in the whisper example requirements.
=> Whisper: pin onnx to 1.13.1

olive/__init__.py
`olive.set_default_logger_severity` takes int from 0-4 for severity level. The corresponding levels for `logging` are 10-50, not 0-40. Update the mapping for this.
=> Correct logger severity mapping

olive/engine/packaging/packaging_generator.py, olive/engine/packaging/sample_code/ONNXModel/python/code_sample.py
`pf_footprint.get_model_inference_config(model_id)` gets the `inference_settings` dictionary from the model config. So, the additional nesting with key `inference_settings` is not present. The inference_config dict is the inference settings dict.
=> Fix inference_config structure in packaging

examples/whisper/README.md, olive/passes/onnx/append_pre_post_processing_ops.py, olive/passes/utils/whisper_prepost.py, scripts/test_examples.bat
Add recent ort-extensions downsampling support for whisper audio preprocessing. Some other changes to whisper prepostprocessing tools to align with the latest whisper_e2e example script. The pass also now uses external data config to save the model to the desired path correctly and keep track of external data if any.
=> Whisper: update pre/post-processing script to latest ort-extensions

olive/systems/azureml/aml_system.py, olive/systems/system_config.py
The default `read_timeout` value for `MLClient` is `3000` seconds. However, this value is too large and causes `AzureMLSystem` pass runs and model evaluations to hang for a long time during the job streaming and download steps when there are multiple jobs being created at the same time (like in the CI pipelines). We already have retries set up for this step, so it is better to reduce the read_timeout value for Olive. 
With this change the bert and resnet ci tests now only take ~50 minutes instead of ~2 hours it takes when the hanging happens. 
We also allow user to set their own default values if they find the connections are timing out even with retries. I don't expect this to be needed much but it is safer to allow the user to overwrite instead of hardcoding it to `60`.
=> Change `read_timeout` for `azure.ai.ml.MLClient`

examples/whisper/README.md, examples/whisper/prepare_whisper_configs.py, examples/whisper/whisper_template.json
Update the dynamic quantization pass to add `Gather` to `op_types_to_quantize`. This reduces the model size from 121MB to 64MB for the tiny model. 
Change the default `model_name` in `prepare_configs.py` to `openai/whisper-tiny.en` .
=> Whisper: quantize embedding layer for smaller model, change default model to tiny 

olive/cache.py, olive/engine/engine.py, olive/passes/onnx/common.py, olive/passes/onnx/quantization.py, test/unit_test/test_cache.py
When we try to save large onnx models (>2GB), we get a value error. However, the error message depends on the version of `onnx`. We previously tried to check the model byte size but there are cases when the byte size returned is negative. 
So, we always try again with `save_as_external_data=True` if the save failed without it. 
If this also fails, then raise original error. 
The `_quant_preprocess` method in onnx quantization pass doesn't handle cases where the quant preprocess fails but the original model has external data. In such cases, just copying the `.onnx` file is not enough.
=> Always try save_as_external_data for `model_proto_to_file`, handle external data for quant preprocess

olive/data/component/pre_process_data.py
When preprocessing a huggingface dataset, `label_col[0]` is renamed to `"label"`. So pass `label_cols=["label"]` when instantiating BaseDataset. 
We didn't catch this bug before since the bert example original label col was also `"label"`. Refer to [this example](https://github.com/microsoft/Olive/blob/jambayk/dolly/examples/dolly/dolly_config.json) for a dataset with different label name.
=> Fix HF preprocessed label_cols

olive/workflows/run/run.py
modify `pip install ` into `python -m pip install` in case the path to pip is not the same as the pip used by the current python environment.
=> fix pip install path

olive/engine/packaging/packaging_generator.py
When I installed onnxruntime-gpu locally, the olive package generation will fail to prepare onnxruntime. The ut failed as well.
=> packing onnxruntime fix

olive/passes/pytorch/pytorch_lightning_utils.py, olive/passes/pytorch/qat_utils.py, olive/passes/pytorch/quantization_aware_training.py, test/unit_test/engine/test_engine.py, test/unit_test/model/test_pytorch_model.py, test/unit_test/passes/pytorch/test_quantization_aware_training.py
When I run unit test locally, always generate many temp files in root folder. It often breaks my git track for changed files.
This PR is used to move those temp files into temp folder and remove them when test is done.
=> Auto remove unit test resulting files

docs/source/overview/options.md, docs/source/tutorials/configure_metrics.rst, docs/source/tutorials/how_to_write_userscript.md, examples/bert_ptq_cpu/bert_config.json, olive/engine/footprint.py, olive/evaluator/accuracy.py, test/unit_test/utils.py, test/unit_test/workflows/mock_data/only_transformer_dataset.json, test/unit_test/workflows/mock_data/transformer_dataset.json
For bert example, when we apply `f1_score`, olive got the unmatched number with official report as the `task` is not assigned to `binary` for bert-mnli task.
https://huggingface.co/Intel/bert-base-uncased-mrpc
This PR added the `task` parameters into accuracy base class which can help get correct numbers.
=> Bert example bugfix for f1_score

test/requirements-test.txt
The supported version for `openvino` extra is `2022.3.0` but the test requirement has no version requirement. There is a new release for openvino and one of the window's test fails. So set the same version in the test.
=> Use same version for openvino in tests as extra

olive/passes/onnx/perf_tuning.py, test/unit_test/passes/onnx/test_perf_tuning.py
if user does not specify input_names and input_shapes for perf tuning, olive will use model io_config read from onnx model graph
=> use model io_config for perf tuning

examples/bert/bert_ptq_cpu.json, examples/bert/bert_ptq_cpu_aml.json, examples/test/utils.py
input specs info is necessary for perf tuning pass if model io_config has dynamic axe.
The assertation is always true because `self.nodes = nodes or OrderedDict()`
=> fix examples

test/requirements-test.txt
There are some changes in the latest mlflow version 2.4.0. https://github.com/mlflow/mlflow/issues/8629 
Our example installs `mlflow-1.28.0, azureml-evaluate-mlflow-0.0.2 azureml-mlflow-1.51.0` after depency resolution. So we need an older version of mlflow-skinny too.
=> Pin mlflow-skinny to 2.3.2 

examples/bert/bert_ptq_cpu.json, examples/bert/bert_ptq_cpu_aml.json, olive/engine/engine.py, olive/passes/onnx/perf_tuning.py
Use the provided `data_config` for perf tuning. We only infer model io config to create dummy data if the user doesn't provide input_names/input_shapes or data config.
=> Use `data_config` for ort perf tuning

olive/passes/onnx/perf_tuning.py
=> 🐛 Fix: cannot get accelerator spec info in perf tuning

examples/snpe/inception_snpe_qualcomm_npu/inception_config.json, examples/snpe/inception_snpe_qualcomm_npu/user_script.py, olive/data/config.py
Add `user_script` and `script_dir` to `DataConfig` and load the user script during initialization so that the custom components are registered.
=> Register custom data config components using user script

examples/bert/conda.yaml, examples/bert/docker/Dockerfile, examples/test/test_whisper.py, examples/test/utils.py, examples/whisper/README.md, examples/whisper/requirements.txt, examples/whisper/test_transcription.py, olive/engine/engine.py, scripts/test_examples.bat, scripts/test_examples.sh
Add ImportError to list of exceptions to rethrow.  
Fix the output check for example tests. We need to check that `footprints` is not empty. Otherwise, we don't catch failed engine runs that just return empty footprints dict. 
Updated the docker and azureml requirements so that the tests are not broken anymore. 
Updated the whisper example requirement to use onnxruntime-extensions directly from pypi. Test is also updated to run `test_transcription` script also.
=> Rethrow ImportError, Fix example tests output check, Update bert and whisper requirements

olive/passes/onnx/quantization.py
Remove weight/activation limitation on onnx quantization. Also test S8U8, worked for resnet static case.
https://onnxruntime.ai/docs/performance/model-optimizations/quantization.html#data-type-selection
=> 🐛 Remove weight/activation limitation on onnx quantization

docs/source/overview/options.md, examples/snpe/vgg_snpe_qualcomm_npu/vgg_config.json, olive/engine/engine.py, olive/snpe/configure.py, olive/snpe/tools/inference.py, olive/snpe/utils/local.py, olive/workflows/run/config.py, olive/workflows/run/run.py
Add `output_name` option to `PassRunConfig` so that output models from intermediate passes can also be saved in no-search mode. The engine's `output_name`, if provided, takes precedence over the final pass' `output_name`.
=> Add option to save intermediate models in no-search, Fix snpe win target arch name

examples/whisper/code/user_script.py, examples/whisper/code/whisper_decoder.py, examples/whisper/code/whisper_encoder.py, examples/whisper/code/whisper_encoder_decoder_init.py, examples/whisper/prepare_whisper_configs.py, olive/passes/onnx/common.py, olive/passes/onnx/insert_beam_search.py
Fix `prepare_whisper_configs.py` to create the correct `WhisperConfig` object. It was not picking up the correct model and made the fp32 configs incorrect. 
Also port over the changes from https://github.com/microsoft/onnxruntime/pull/15880 that removes the unnecessary `encoder_attention_mask` inputs for whisper components. 
Added an option in `model_proto_to_olive_model` to check the onnx model.
=> Whisper: Fix WhisperConfig init, Remove encoder_attention_mask

olive/passes/onnx/inc_quantization.py
The newly release version of `neural-compressor` has removed the `use_distributed_tuning` from their quant configs. 
Since we were not using `use_distributed_tuning` in any of our examples before, removing this doesn't affect any workflows. 
Another option is to check for neural-compressor version and ignore this parameter for the latest versions. 
I think it is better to remove this parameter for now. In the latest `neural-compressor`, distributed tuning must be done by calling the python script with mpirun. This is not possible in Olive since we call the tuner directly in our pass run code. There is no provision to run olive with mpirun. We will need to think through how to support inc distribued tuning if we want to support it in the future.
=> Remove `use_distributed_tuning` config param from INC quantization passes

docs/source/overview/options.md
This reverts commit 25c91b9279b59ffaa43b587fe880b90b00b6fb8a.
The link is back online.
=> Revert "Docs: Comment out broken link (#376)"

examples/whisper/README.md, examples/whisper/code/user_script.py, examples/whisper/code/whisper_dataset.py, examples/whisper/code/whisper_decoder.py, examples/whisper/code/whisper_encoder_decoder_init.py, examples/whisper/prepare_whisper_configs.py, examples/whisper/requirements.txt, examples/whisper/test_transcription.py, examples/whisper/whisper_template.json, olive/passes/onnx/insert_beam_search.py
This PR adds support for the latest ORT version and multilingual support. 
Also added transformer optimization pass in the `cpu,int8` config. It was previously ommited due to a bug in ORT which was already resolved in version `1.15.0`.
We currently don't have tests for the latest ORT and multilingual support since there are no publically available ort-nightly builds. Will look into this in the future. 
Fixes: #293 
Fixes: #341
=> Whisper: Add multilingual support, Updated with latest ORT

examples/whisper/README.md, examples/whisper/requirements.txt, olive/passes/onnx/quantization.py, olive/passes/onnx/vitis_ai/calibrate.py, olive/passes/onnx/vitis_ai/quantize.py
ORT main branch recently removed some functions in https://github.com/microsoft/onnxruntime/commit/89f8f20a61ceac0276c42d894c38400d86b175d0. 
For vitis ai code, the import of these functions is made lazy (only imported where needed). vitis ai code needs to be updated later to actually be compatible with ORT 1.16.0. Since this version of ORT is not released yet, it is not urgent. 
For onnx quantization passes, `optimize_model` config parameter is removed in ORT and we do the same. Using this option was already not recommended so I think it might be okay to remove it from Olive onnx quantization passes and always set it to `False` in older versions of ORT. As described in the code comments, we already have `quant_preprocess` which does the same optimization step as part of preprocessing. …
=> Make Olive compatible with ORT 1.16.0 (nightly)

.gitignore, olive/passes/openvino/quantization.py, olive/snpe/data_loader.py, test/unit_test/passes/openvino/test_openvino_quantization.py
Add support for `data_config` in `OpenVINOQuantization` pass. If data_config is given, the pass converts it into the correct `openvino.tools.pot.api.DataLoader` format.
=> Support data_config in OpenVINOQuantization quantization pass

olive/common/config_utils.py, olive/engine/engine.py, olive/evaluator/metric.py, olive/systems/docker/docker_system.py, test/integ_test/evaluator/docker_eval/test_docker_evaluation.py, test/unit_test/systems/docker/test_docker_system.py
Sometimes, the CI pipeline failed with Connection error for docker tests, but the raised error is shown as None metric results. 
That is caused by:
docker.container.run failed, but olive continue run to get the empty results
MetricResult accept empty value which will put off the failure again.
=> 🐎Raise the failure in time after docker.container.run failed

olive/engine/engine.py, olive/exception/__init__.py, olive/passes/onnx/quantization.py, test/unit_test/engine/test_engine.py
Sometimes, the quantization would fail https://dev.azure.com/aiinfra/Model%20optimization%20Toolkit/_build/results?buildId=321080&view=logs&j=83e9455c-f768-5dd6-ffb8-4d16293cb8a9&t=8c02a2da-1821-5532-3cad-c631fe1ed2f8 
Olive should have the ability to handle this kind of error not caused by Olive bug. when this happens, the quantization should be ignored. 
As the result, we introduce OliveException system to allow Olive throw the ignorable exception in pass run
=> add Olive exception skeleton

docs/requirements.txt, examples/bert/docker/Dockerfile, requirements.txt, test/integ_test/evaluator/docker_eval/dockerfile/Dockerfile
There is a new major release for pydantic 2.0.0 which has multiple breaking changes. So we pin pydantic to version < 2.0.0. We can consider upgrading to the latest major release in the future. 
There is no corresponding release for `autodoc_pydantic` yet but also changing it to be safe.
=> Use pydantic<2.0.0

olive/systems/docker/docker_system.py, test/unit_test/systems/docker/test_docker_system.py
Currently, there are a few concerns about docker logs
1. docker logs are printed with `info` level even if the docker logs container errors.
2. the failure log in docker container cannot be exposed in raised exception.
This pr is used to improve above issues.
=> 🤯 Expose docker logs

requirements.txt
With onnx is released to version 1.14.0, the required protobuf is set as >3.20.2. But for `transformers`, I met the error of protobuf version. It failed when run following importing:
`from transformers import AutoModelForMaskedLM, AutoTokenizer, PreTrainedModel, PreTrainedTokenizerBase`
So I tried to pin the protobuf version as 3.20.3 to meet the requirements from `onnx` and `transformers`
LInks:
1. onnx protobuf limitation: https://github.com/onnx/onnx/blob/rel-1.14.0/requirements.txt
=> ⛏️Pin protobuf to 3.20.3

examples/switch/README.md, examples/switch/config.json, examples/switch/inference.py, olive/cache.py, olive/passes/onnx/__init__.py, olive/passes/onnx/moe_experts_distributor.py
MoE Experts Distributor
Introducing a pass to distribute experts in onnx model by splitting the graph equally, making each individual such graph capable of running on its own GPU.
NOTE: The implementation requires a custom onnxruntime build with "--use_mpi" flag enabled.
=> MoE Experts Distributor

olive/systems/python_environment/python_environment_system.py, test/unit_test/systems/python_environment/test_python_environment_system.py
"accelerator - execution_provider" info is not used in python env system evaluation. Fix this issue
=> add accelerator into python env system

examples/test/test_whisper.py, examples/whisper/README.md, examples/whisper/prepare_whisper_configs.py, examples/whisper/requirements.txt, examples/whisper/whisper_template.json
Add a whisper example using Intel® Neural Compressor Quantization.
=> Add a whisper example using Intel Neural Compressor

examples/bert/README.md, examples/bert/bert_inc_ptq_cpu.json, examples/bert/bert_inc_smoothquant_ptq_cpu.json
Add a BERT example using Intel® Neural Compressor SmoothQuant.
Add an introduction of Intel® Neural Compressor SmoothQuant to the README.
=> Add a BERT example using Intel Neural Compressor SmoothQuant

docs/source/overview/options.md, examples/cifar10_openvino_intel_hw/config.json, examples/mobilenet_qnn_qualcomm_npu/mobilenet_config_template.json, examples/whisper/whisper_template.json, olive/engine/engine.py, olive/engine/footprint.py, olive/engine/packaging/packaging_generator.py, olive/workflows/run/config.py, olive/workflows/run/run.py, test/unit_test/engine/packaging/test_packaging_generator.py, test/unit_test/engine/test_engine.py
Currently, if you want to get the evaluation result from input_model, they need to set:
1. `evaluation_only`: in this case, olive only evaluate input model without passes run.
2. or to set metric `goal` to tell the metric tolerance based on the baseline.
Several customers would love to compare the input model metrics with output model's metrics by default. So in this PR, we make input model is evaluated as long as there is the given metrics. 
If user do not need to evaluate input model, they can manually set `evalute_input_model` as `False`.
With the PR, the default behaviors. is like:
1. evaluate input model with given metrics.
2. if user gives the metric goal, olive read the result in step 1 from cache.
3. then olive will run search or no_search passes w.r.t given metrics.
Replace …
=> ☂️Opt in input model eval

docs/source/conf.py, docs/source/getstarted/installation.md, docs/source/overview/options.md, docs/source/overview/quicktour.md, docs/source/tutorials/advanced_users.md, docs/source/tutorials/configure_model_path.md, docs/source/tutorials/design.md, docs/source/tutorials/how_to_add_optimization_pass.md, docs/source/tutorials/how_to_write_userscript.md, docs/source/tutorials/huggingface_model_optimization.md
The markdown under olive docs contains the flag from `myst-parser` which makes the `git markdown preview` weird. Just found that it can be simply fixed and keep the `myst_parser` worked.
=> 🪂 Ensure markdown file under docs can be parsed solely

examples/whisper/README.md, examples/whisper/code/whisper_dataset.py, examples/whisper/prepare_whisper_configs.py, examples/whisper/test_transcription.py, olive/workflows/run/run.py
This PR contains changes to improve the whisper example:
- `WhisperDataset` now takes in additional init parameters: `file_ext`, `language` and 'task`
- `test_transcription.py` infers `file_ext` from `audio_path`. User can override default values for `language` and `task`. 
- README updated to make it clear that the `ort-nightly` installation is done after installing the requirements.txt 
Logging is improved for setup.
=> Whisper: Expose language,task in dataset, support different file ext. Improve setup logging

examples/directml/dolly_v2/config_dolly_v2.json, examples/directml/squeezenet/squeezenet_config.json, examples/directml/stable_diffusion/config_safety_checker.json, examples/directml/stable_diffusion/config_text_encoder.json, examples/directml/stable_diffusion/config_text_encoder_2.json, examples/directml/stable_diffusion/config_unet.json, examples/directml/stable_diffusion/config_vae_decoder.json, examples/directml/stable_diffusion/config_vae_encoder.json
Input model evaluation doesn't currently work for DirectML because Olive equates `gpu` accelerators to `cuda` pytorch devices, which doesn't work when torch cuda isn't installed (and it won't usually be when people are running DML examples).
This PR is meant to unblock those examples, but in the future we should have a path to fallback to the CPU or use pytorch-directml when using `"evaluate_input_model": true`.
=> Disable input model evaluation for DirectML examples

olive/passes/onnx/conversion.py
We use huggingface data config to auto-generate dummy inputs for onnx conversion. However, sometimes the data has more inputs that the inputs we want for the converted models. This PR removes the unused dummy inputs so that the converted onnx model doesn't have the unused input as one of its required inputs. 
For example if the `input_names=['input_ids', 'attention_mask']` and the data has items `['input_ids', 'attention_mask','token_type_ids']`, the converted `.onnx` model has input names `['input_ids', 'attention_mask','input.1']`. 
This is not what we want. 
Removing `'token_type_ids'` prevents this issue. 
Try this model+dataset to replicate the bug:
```json
"input_model": {
"type": "PyTorchModel",
"config": {
"hf_config": {
"model_name": …
```
=> Remove unused dummy input in `OnnxConversion`

test/integ_test/evaluator/docker_eval/dockerfile/Dockerfile
Disable pip cache for docker image building
=> 💾  Disable pip cache for docker image building

olive/data/component/dataset.py, olive/data/component/load_dataset.py, olive/data/component/pre_process_data.py, olive/data/template.py, olive/passes/onnx/conversion.py
This PR exposes the `data_files` argument for load_dataset. Sometimes we only want specific files from the dataset to be used. 
`max_samples` is used during pre-processing to limit the maximum number of samples. Some datasets have a large number of samples which might be too much for evaluation or calibration purposes. 
In the future, we could provide other arguments such as `max_calibration_samples` or `max_calibration_batches` if needed.
=> Huggingface DataConfig: Add support for `data_files` and `max_samples`

examples/bert/bert_cuda_gpu.json, examples/bert/bert_trt_gpu.json, olive/engine/engine.py, olive/hardware/accelerator.py, test/unit_test/hardare/test_accelerator.py
From many users' feedback, when they ensure cuda/trt ep is run on gpu certainly, they have to write the accelerators configs to tell current device is [`gpu`]
This PR is used to remedy this. The logic is like:
If Olive can find unique accelerator for each EP provided by users, then use it unless if user set it explicitly.
For examples:
Eps, inferred acceleartors:
(["CPUExecutionProvider"], None),
(["CUDAExecutionProvider"], ["gpu"]),
(["CUDAExecutionProvider", "CPUExecutionProvider"], None), // as we find multi-accelerators(cpu/gpu/npu) for CPU ep.
(["DmlExecutionProvider", "CUDAExecutionProvider"], ["gpu"]),
(["QNNExecutionProvider", "CUDAExecutionProvider"], ["npu", "gpu"]),
=> 🛺 Auto infer accelerators with EPs

olive/passes/onnx/conversion.py
Use 13 as default opset for onnx conversion pass to be compatible with torch version < 2.0
=> Use 13 as default opset for onnx conversion pass

olive/evaluator/accuracy.py, olive/evaluator/olive_evaluator.py, olive/systems/python_environment/python_environment_system.py, test/unit_test/evaluator/test_accuracy.py, test/unit_test/systems/python_environment/test_python_environment_system.py
During accuracy evaluation, we convert the output and target tensors to list before computing the metric value. However, this method is expensive and not efficient when the tensors are large since we end up converting them back to torch tensors anyways. 
This is felt significantly when evaluating perplexity for large language models where the `preds` tensor is a large logit tensor of size `batch_size, seqlen, vocab` (like `1 X 2048 X 32000`). This is very slow. 
In this PR, we just move the tensors to `cpu` if not already on cpu and concatenate them using `torch.cat`. This has the same effect as `list.extend`.
=> Keep `preds` and `targets` as torch tensor during accuracy evaluation

olive/data/component/pre_process_data.py, olive/data/config.py, test/unit_test/workflows/mock_data/text_generation_dataset_random.json, test/unit_test/workflows/test_run_config.py
`DataConfig` supports multiple ways to pass parameters to the components. They are:
- `DataConfig.params_config` - the parameters for different components are provided as members of this dictionaries. Only the named parameters of components are updated using this. There is no way to specify component specific kwargs. 
- `DataConfig.components["component_name"].params` - We can provide component specific kwargs using this but it is hard to access. Moreover, there is not way to provide this for hf datatemplate or `HFConfig.datasets` for input model. 
This PR introduces a reserved member in `DataConfig.params_config` called `component_kwargs` where we can provide component specific kwargs. An example usage is:
```
{
"name": "c4_train",
"type": "HuggingfaceContainer",
"params_config": { …
```
=> Add `component_kwargs` in `DataConfig.params_config`

olive/evaluator/accuracy.py, test/unit_test/evaluator/test_accuracy.py
Olive metrics will generate metrics config regarding various downstream metrics.
There is a bug about `kwargs` which need be expanded when measuring. But Olive metrics configs contain that before this fixing.
=> 🐛 Bugfix: remove kwargs from accuracy config when measuring

docs/source/overview/options.md, examples/bert/bert_cuda_gpu.json, examples/test/test_bert_cuda_gpu.py, examples/test/utils.py, examples/whisper/test_transcription.py, olive/engine/engine.py, olive/engine/footprint.py, olive/strategy/search_strategy.py, olive/workflows/run/config.py, olive/workflows/run/run.py, test/unit_test/engine/test_engine.py
Provide the interface to let use set the multi pass flows to run in save olive workflow. 
The search strategy will traverse multi-passes sequentially:
for example, for the flows of `[[pass_a, pass_b, pass_c], [pass_a, pass_c]]`
1. `joint`: 
- `[pass_a, pass_b, pass_c]`
- `[pass_a, pass_c]`
3. `pass-by-pass`: 
- `[[pass_a], [pass_b], [pass_c]]`
- `[pass_a]`
- `[pass_b]`
- `[pass_c]`
-  `[[pass_a], [pass_c]]`
- `[pass_a]`
- `[pass_c]`
Provide the interface to let use set the multi pass flows to run in save olive workflow. 
```json
"passes": {
"onnx_conversion": {
"type": "OnnxConversion",
"config": {
"target_opset": 13
}
},
"transformers_optimization": {
"type": "OrtTransformersOptimization",
"config": {
"model_type": "bert",
"num_heads": 12,
"hidden_size": 768,
"float16": true
}
}, …
```
=> 🎏 Multi passes run in same olive workflow

docs/source/overview/options.md, olive/model/hf_onnx_config.py, olive/model/hf_utils.py, test/unit_test/model/test_hf_utils.py, test/unit_test/model/test_pytorch_model.py
Olive uses `transformer.onnx.FeaturesManager` to automatically get onnx conversion args. However, huggingface has started using `optimum` for this instead and haven't added support for newer models in `transformers.onnx`. 
In this PR, we add support for `opt`, `llama` and `gptneox` (model type for dolly) by extending `FeaturesManager`. All of these models are text decoder model so they are using the same onnx config. 
Also, infer `feature` from `task` if not provided. We previously used `default` but that doesn't work as expected if the `task` is different from the default. Such as `sequence-classification` for gpt2 whose default is `causal-lm`.
=> Automatic onnx conversion for opt, llama, gptneox. Infer `feature` from `task`

olive/passes/onnx/transformer_optimization.py
Make transformer optimization not agnostic for accelerator as recently we leverage the EPs info to prune search point.
Then we should set `is_accelerator_agnostic` as False.
=> 🐛 Bugfix: make transformer optimization not agnostic for accelerator

requirements.txt
`perplexity` support was added in https://github.com/microsoft/Olive/pull/444. However, `torchmetrics` only supports this metrics in versions >= 0.10.0. So, we update the requirement to `~=0.10.0`.
=> Pin `torchmetrics` version to `~=0.10.0`

olive/passes/onnx/conversion.py, test/unit_test/passes/onnx/test_conversion.py, test/unit_test/utils.py
**summary:** 
Skip removing past_key_values in dummy input in OnnxConversion, which is required for hf model with past.
**Details:**
GPTJ example failed in OnnxConversion with error: `RuntimeError: The size of tensor a (8) must match the size of tensor b (18) at non-singleton dimension 3`
To quickly reproduce the error:
```python
from olive.model import PyTorchModel
from olive.passes.olive_pass import create_pass_from_dict
from olive.passes.onnx.conversion import OnnxConversion
from olive.systems.local import LocalSystem
local_system = LocalSystem()
hf_config={"model_name": "hf-internal-testing/tiny-random-gptj",
"task": "text-generation",
"feature": "causal-lm-with-past"}
pytorch_model = PyTorchModel(hf_config=hf_config)
onnx_conversion_config = {}
p = …
```
=> Fix OnnxConversion failure in GPTJ example

olive/engine/config.py, olive/engine/engine.py, olive/passes/onnx/transformer_optimization.py
Separate `PRUNED_CONFIG` into `INVALID_CONFIG` and `FAILED_CONFIG`. 
`INVALID_CONFIG` is used when the run config is invalid for a given accelerator spec.
`FAILED_CONFIG` is used when the run config is valid, but the pass run fails for some reason. 
This helps us make the search more efficient. the transformer optimizer pass was made `not accelerator_agnostic` even though the pass run itself doesn't depend on the accelerator. All information is already in the `run_config`. 
It is okay for a pass to be `accelerator_agnostic` but the search space to have points invalid for specific `accelerator_specs`. 
What matters when determining if a pass is `accelerator_agnostic` is if the pass run uses the accelerator specs and the output depends on it. 
In the transformer optimizer case, the …
=> Separate `failed` and `invalid` pass run configs

docs/source/api/passes.rst, docs/source/features/passes/pytorch.md, examples/open_llama/README.md, examples/open_llama/open_llama_sparsegpt_gpu.json, examples/open_llama/requirements.txt, olive/extra_dependencies.json, olive/passes/pytorch/__init__.py, olive/passes/pytorch/sparse_trt_conversion.py, olive/passes/pytorch/sparsegpt.py, olive/passes/pytorch/sparsegpt_utils.py, olive/passes/pytorch/torch_trt_conversion.py, olive/passes/pytorch/trt_utils.py, olive/workflows/run/run.py, test/unit_test/passes/pytorch/test_torch_trt_conversion.py
This PR adds `TorchTRTConversion` pass which converts `nn.Linear` modules in transformer layers to `TRTModule` from `torch-tensorrt`. `torch-tensorrt` is an extension to `torch` where TensorRT engines can be used like normal `nn.Module`. 
We require this conversion to take advantage of `2:4` sparsity. 
~~I have not added unit test for the pass since the pass requires GPU and we don't have GPU support for ci tests yet. I will add a unit test in a follow up PR that uses aml system to run the pass and evaluation on GPU.~~
Add `TorchTRTConversion` pass.
=> Add `TorchTRTConversion` pass

examples/bert/bert_cuda_gpu.json, examples/bert/bert_ptq_cpu.json, examples/bert/bert_ptq_cpu_aml.json, examples/bert/bert_trt_gpu.json, olive/data/constants.py, olive/passes/olive_pass.py, olive/passes/onnx/inc_quantization.py, olive/passes/onnx/perf_tuning.py, olive/passes/onnx/quantization.py, olive/passes/openvino/quantization.py, olive/passes/pass_config.py, olive/passes/pytorch/sparsegpt.py, olive/passes/pytorch/torch_trt_conversion.py, olive/passes/snpe/quantization.py, olive/workflows/run/config.py, test/unit_test/workflows/mock_data/ner_task_dataset.json, test/unit_test/workflows/mock_data/only_transformer_dataset.json, test/unit_test/workflows/mock_data/text_generation_dataset.json, test/unit_test/workflows/mock_data/text_generation_dataset_random.json, test/unit_test/workflows/mock_data/transformer_dataset.json, test/unit_test/workflows/test_run_config.py
This PR is an update to [#506](https://github.com/microsoft/Olive/pull/505) with changes discussed offline. 
`Pass` has a class attribute `_requires_data_config` that we use to add a config parameter with type `DataConfig` and name `data_config`. We also use this in workflow run config validation to resolve string name references or auto insert input models. 
However, this functionality is limited. We can only add one `DataConfig` parameter with name `data_config` and single description. Currently, all of the passes are using the same parameter definition. 
We remove `_requires_user_config` class attribute from passes. DataConfig parameters must be defined along with other parameters in `_default_config`. Parameter names ending in `default_config` are reserved for such parameters. We use …
=> Remove `Pass._requires_data_config`, resolve using `endswith`, don't auto-insert input model dataset

olive/data/config.py
In `DataConfig.update_components`, we assign values for `components` from `default_components`. However, these are assigned by reference for objects and the default components get updated when we update components. 
We can see this behavior in the follow code snippet:
```python
from olive.data.config import DataConfig 
dc_dict = {
"name": "wikitext2_test",
"type": "HuggingfaceContainer",
"params_config": {
"model_name": "gpt2",
"task": "text-generation",
"data_name": "wikitext",
"subset": "wikitext-2-raw-v1",
"split": "test",
"input_cols": ["text"],
"seqlen": 2048
}
}
dc = DataConfig(**dc_dict)
dc_json = dc.to_json()
dc2 = DataConfig(**dc_json)
dc2_json = dc2.to_json()
import json
json.dump(dc_json, open("dc.json", "w"), indent=4)
json.dump(dc2_json, open("dc2.json", "w"), indent=4)
``` …
=> Bugfix: `deepcopy` default values in DataConfig

olive/common/utils.py, olive/model/hf_mappings.py, olive/model/hf_utils.py, olive/passes/pytorch/sparsegpt.py, olive/passes/pytorch/sparsegpt_utils.py, olive/passes/pytorch/torch_trt_conversion.py, test/unit_test/common/test_get_attr.py, test/unit_test/passes/pytorch/test_torch_trt_conversion.py
`sparsegpt_utils` has some mappings and helper functions that are useful in other parts of Olive too. This PR refactors it and puts the reusable code into `olive.common.utils` and `olive.model.hf_utils`. 
Also cleaned up the imports in `hf_utils` by moving `transformers` imports to top of file. `transformers` is an olive requirement so we don't need to lazy import it unless it is a version specific import.
=> Move reusable code from `sparsegpt_utils` to common and hf utils

olive/systems/azureml/aml_pass_runner.py
In onnxruntime, the following PRs will make the optimize_model save external data in the temporary folder
* https://github.com/microsoft/onnxruntime/pull/16531
* https://github.com/microsoft/onnxruntime/pull/16716
* https://github.com/microsoft/onnxruntime/pull/16912
So, in 1.16.0 afterwards, we don't need to copy the model to a temp directory
=> Don't copy the model for onnxruntime after 1.16.0

olive/data/component/dataset.py, test/unit_test/data_container/test_dataset.py
Add a method called `to_hf_dataset` which converts an olive Dataset to huggingface `datasets.Dataset`. This is useful if we want to use some huggingface related features such as `train_test_split` or easy indexing by feature/index.
=> Add `to_hf_dataset` method to `olive.data.component.dataset.Dataset`

docs/source/overview/options.md, olive/data/component/pre_process_data.py, olive/data/template.py, test/unit_test/workflows/mock_data/only_transformer_dataset.json
In some cases, the model output label is mismatched with original huggingface dataset.
E.g. the deberta-base-mnli output id2label is:
But the dataset label is:
This PR is used to fill this gap.
=> 🗺️ Align hf dataset label with model output

olive/passes/onnx/inc_quantization.py, olive/passes/onnx/quantization.py, olive/passes/openvino/quantization.py, olive/passes/snpe/quantization.py, test/unit_test/engine/test_engine.py
Some passes support both `dataloader_func` and `data_config`. We don't set them to required but most of the time, one is required. Check for this in the pass run so that the error is caught early and is clear to the user.
=> Assert that `dataloader_func` or `data_config` is present if required

examples/switch/config.json, examples/switch/inference.py, olive/evaluator/olive_evaluator.py, olive/passes/onnx/moe_experts_distributor.py
Task #18366: Remove hardcoded support for GPU in distributed inferencing
Distributed inferencing is supported only for GPU and that was hardcoded. Updated the code to use device and execution providers from config and also raised an exception for non-gpu input.
https://aiinfra.visualstudio.com/Model%20optimization%20Toolkit/_workitems/edit/18366
=> Task #18366: Remove hardcoded support for GPU in distributed inferencing

olive/model/__init__.py, olive/model/hf_utils.py, test/unit_test/model/test_hf_utils.py, test/unit_test/model/test_pytorch_model.py
Add a new field called `model_loading_args` to `HFConfig`. `transformers.PreTrainedConfig.from_pretrained` method can take many other keyword arguments. One such argument is `device_map` which can be used to load a large model to multiple gpus. This can be useful when evaluating accuracy metrics such as perplexity for large LLMs. 
New passes like QLoRA needs to save a hf model with quantization_config. The model is quantized during loading. 
Also added `load_model` and `load_model_config` methods to `HFConfig`. This way, we can use the hf_config directly instead of keep loading logic outside of it. I think we can also handle the point I brought up in [this discussion](https://github.com/microsoft/Olive/pull/518#discussion_r1309159989) in https://github.com/microsoft/Olive/pull/518 by …
=> Add `model_loading_args`, `load_model` and `load_model_config` to `HFConfig`

olive/cache.py, olive/engine/engine.py, olive/model/__init__.py, olive/resource_path.py, olive/systems/azureml/aml_evaluation_runner.py, olive/systems/azureml/aml_pass_runner.py, olive/systems/azureml/aml_system.py, olive/systems/docker/docker_system.py, olive/systems/docker/eval.py, olive/systems/docker/utils.py, olive/systems/utils.py, test/integ_test/aml_model_test/test_aml_model.py, test/unit_test/systems/azureml/test_aml_system.py, test/unit_test/systems/docker/test_docker_system.py, test/unit_test/test_cache.py
Some pytorch models such as huggingface models might have adapters, such as LoRA weights (https://huggingface.co/docs/peft/conceptual_guides/lora). This PR adds `adapter_path` to `PyTorchModel` which will be used to add the adapters to the model during load. Currently, we only support hugging face `peft` adapters. 
`adapter_path` can be a resource path like `model_path`. 
Updated the cache, docker system and azureml systems to handle adapter_path correctly. Refactored some of the code for `model_path` into helper methods so that we can reuse them for handling different resource path attributes. For now, we only have `model_path` and `adaptor_path`.
=> Add `adapter_path` to `PyTorchModel`

test/unit_test/passes/pytorch/test_torch_trt_conversion.py, test/unit_test/systems/python_environment/test_python_environment_system.py
Also corrected the order of paths in the torch_trt_conversion test.
=> Fix test_python_environment_system to correctly use `assert_called_once_with`

olive/common/config_utils.py, olive/model/hf_utils.py
This PR adds a new config base class called `ConfigWithExtraArgs` where the config values not defined in the class fields are collected in a field called `extra_args`. This behaves similar to `**kwargs` in functionality. It is useful for config classes where we expose some parameters but still want to accept extra arguments. The child classes can add their own validators on `extra_args` if needed.
=> Add `ConfigWithExtraArgs`

olive/common/config_utils.py
This is a follow up to https://github.com/microsoft/Olive/pull/534. The `gather_extra_args` validator did not consider the case where the value could be provided as None explicitly in the config (such as after serialization). In which case `values.pop("extra_args", {})` returns `None` which is not iterable.
=> ConfigWithExtraArgs: Handle cases where extra_args is provided as None

olive/model/__init__.py, test/requirements-test.txt
For version azureml-evaluate-mlflow<=0.0.7, the default flaver name for huggingface transformers model is `hftransformer`.
But after that(>=0.08, currently the latest one is 0.0.25), the default name goes to `hftransformerv2`.
Also when it >=0.0.14, the version of mlflow[-skinny] will be forced to 2.3.1.
This PR used to reduce the version range for azureml-evaluate-mlflow and mlflow which is strong rely on mlflow[-skinny]==2.3.1.
If not, the pip resolver is always try to go through all the version and raise the following error:
=> 🐛 Aml mlflow fix

olive/common/config_utils.py, olive/model/__init__.py, olive/passes/olive_pass.py
use typevar for validate_config so that typehints for the caller validate_config works in VSCode
=> use typevar for validate_config

olive/evaluator/olive_evaluator.py
From the time being, the ORT will automatically allow execution provider fallback. This behavior is not expected for Olive which targeted on the specific EP optimization. 
We explicitly check whether it is fallbacked or not. If yes, throw exception, otherwise, we will disable the fallback.
=> check whether the inference session is fallback after it is created

test/unit_test/passes/inc/test_inc_quantization.py, test/unit_test/passes/onnx/pipeline/test_step_utils.py, test/unit_test/passes/onnx/test_conversion.py, test/unit_test/passes/onnx/test_insert_beam_search.py, test/unit_test/passes/onnx/test_mixed_precision.py, test/unit_test/passes/onnx/test_model_optimizer.py, test/unit_test/passes/onnx/test_optimum_conversion.py, test/unit_test/passes/onnx/test_perf_tuning.py, test/unit_test/passes/onnx/test_pre_post_processing_op.py, test/unit_test/passes/onnx/test_transformer_optimization.py, test/unit_test/passes/openvino/test_openvino_conversion.py, test/unit_test/passes/openvino/test_openvino_quantization.py, test/unit_test/passes/pytorch/test_qlora.py, test/unit_test/passes/pytorch/test_quantization_aware_training.py, test/unit_test/passes/pytorch/test_sparsegpt.py, test/unit_test/passes/pytorch/test_torch_trt_conversion.py, test/unit_test/passes/vitis_ai/test_vitis_ai_quantization.py
This is a follow up to the discussion https://github.com/microsoft/Olive/pull/545#discussion_r1319314454 to simplify the pass unit tests. 
`LocalSystem` is not needed to run the pass since we can run the pass directly. 
Also use `tmpdir` that is automatically provided by pytest instead of creating our own temporary directory.
=> Use `pass.run` and automatic `tmpdir` in pass unit tests

test/unit_test/passes/inc/test_inc_quantization.py, test/unit_test/passes/onnx/pipeline/test_step_utils.py, test/unit_test/passes/onnx/test_conversion.py, test/unit_test/passes/onnx/test_insert_beam_search.py, test/unit_test/passes/onnx/test_mixed_precision.py, test/unit_test/passes/onnx/test_model_optimizer.py, test/unit_test/passes/onnx/test_optimum_conversion.py, test/unit_test/passes/onnx/test_perf_tuning.py, test/unit_test/passes/onnx/test_pre_post_processing_op.py, test/unit_test/passes/onnx/test_transformer_optimization.py, test/unit_test/passes/openvino/test_openvino_conversion.py, test/unit_test/passes/openvino/test_openvino_quantization.py, test/unit_test/passes/pytorch/test_qlora.py, test/unit_test/passes/pytorch/test_quantization_aware_training.py, test/unit_test/passes/pytorch/test_sparsegpt.py, test/unit_test/passes/pytorch/test_torch_trt_conversion.py, test/unit_test/passes/vitis_ai/test_vitis_ai_quantization.py
Follow up to https://github.com/microsoft/Olive/pull/549. 
`tmp_path` returns a `pathlib.Path` object which is more convienient. https://docs.pytest.org/en/7.1.x/how-to/tmp_path.html
=> Use `tmp_path` instead of `tmpdir` in pass unit tests

olive/model/__init__.py, test/unit_test/model/test_pytorch_model.py
PyTorchModel.to_json  will call resource.get_path. This would not work since the resource is just string now. The PR just to fix the bug.
=> fix model to_json bug since the resource is just string now

.azure_pipelines/formatting.yaml, examples/whisper/README.md, examples/whisper/prepare_whisper_configs.py, examples/whisper/test_transcription.py, examples/whisper/whisper_template.json, olive/workflows/run/run.py, setup.py
Officially drop python 3.7 since it has already reached end of life. Most olive dependencies have already dropped python 3.7 support so olive was probably incompatible with it. 
`onnxruntime` packages are distributed using different names but they are all installed under the same `onnxruntime` namespace.
So, we cannot check if the required package is installed using the `try: __import__` method. This PR uses `importlib.metadata` to check the local ort installations and log the required steps needed. We don't want to uninstall packages ourselves so we will just log the command for the user to run. 
Addresses the original issue in https://github.com/microsoft/Olive/issues/557 
Also update Whisper example to provide and use accelerator+ep correctly.
Added FAQ for common issues like …
=> Drop python 3.7, Fix `onnxruntime` dependency setup, Whisper: Add EP and FAQ

olive/engine/engine.py
Move the engine run for each accelerator to a dedicated method since it introduce a lot of indent in Python, which is hard to maintain. 
BTW, during the refactoring process, I found : 
https://github.com/microsoft/Olive/pull/419 introduce a behavior which is not consistent with original one. 
If there is no pass only the first accelerator will be used for evaluation input model. Not sure it is a bug.
=> refactor engine run for each accelerator

olive/engine/engine.py
This PR is used fix following issue where the same pass with different config appears in one olive run config.
https://github.com/microsoft/Olive/issues/573
[Root Cause]: 
Olive uses the pass's class name as key to identify the pass instance. When there are passes with same pass_class, the first one defined in olive run config will be picked always.
https://github.com/microsoft/Olive/blob/main/olive/engine/engine.py#L436
=> 🐛 Distinguish pass instance with name not cls name

olive/data/component/text_generation.py
`context` was computed incorrectly after the PR https://github.com/microsoft/Olive/pull/545. Fixed in this PR. 
The above PR changed the indexing from `:-context` to `:context`. So we need use the `seqlen - stride` instead of `stride` to get the correct length.
=> Bugfix: Correct context length for text-gen dataset

examples/open_llama/README.md, examples/open_llama/open_llama_qlora_tinycodes.json, examples/open_llama/open_llama_sparsegpt_gpu.json, examples/open_llama/qlora_user_script.py, olive/data/component/text_generation.py
Improve text-generation dataset preprocessing using the following updates:
- Allow user to provide f-string templates to combine multiple text columns. This enables templates such as `"### Question: {prompt} \n### Answer: {response}"` 
- Allow adding special tokens to each example before joining them in corpus join strategies. This enables data "packing" like huggingface sft trainer does (https://github.com/huggingface/trl/blob/main/trl/trainer/sft_trainer.py#L90, https://github.com/huggingface/trl/blob/main/trl/trainer/utils.py#L464) 
- Process the texts in batches instead of joining them and processing as a single string. Tokenizers might be optimized for batched tokenization so we should take advantage of it.
=> Text-generation: Support text templates, Special tokens in corpus join, Batched processing

examples/test/test_bert_cuda_gpu.py, examples/test/test_bert_ptq_cpu.py, examples/test/test_bert_ptq_cpu_aml.py, examples/test/test_bert_ptq_cpu_docker.py, examples/test/test_cifar10_openvino_intel_hw.py, examples/test/test_resnet_ptq_cpu.py, examples/test/test_resnet_qat.py, examples/test/test_resnet_vitis_ai_ptq_cpu.py, examples/test/test_whisper.py, examples/test/utils.py, olive/engine/engine.py, olive/engine/footprint.py, test/multiple_ep/test_aml_system.py, test/multiple_ep/test_docker_system.py, test/multiple_ep/test_python_env_system.py, test/unit_test/engine/test_engine.py, test/unit_test/engine/test_footprint.py
This PR is used to unify the returning of `run_no_search` and `run_search` with olive footprints.
More discussions here: https://github.com/microsoft/Olive/pull/572
=> 🥋 Unify engine run returning

.azure_pipelines/performance_check/configs/bert.json, .azure_pipelines/performance_check/configs/deberta.json, .azure_pipelines/performance_check/configs/distilbert.json, .azure_pipelines/performance_check/configs/roberta_large.json, examples/bert/bert_ptq_cpu.json, examples/bert/bert_ptq_cpu_aml.json
Enable quantization preprocess by default for bert model, as we know that would avoid some bad samples from olive optimization for bert cases.
=> ⏮️ Preprocess for quant as true for bert model

olive/systems/azureml/aml_system.py, olive/systems/local.py, test/unit_test/systems/azureml/test_aml_system.py
Get some of the code improvements from https://github.com/microsoft/Olive/pull/591. 
Duplicated code in AzureMLSystem for submitting and downloading aml jobs has been abstracted into a method `run_job`. 
Pipeline output is not hard-coded to "pipeline_output" anymore in `_create_step`
=> Abstract common code in AzureMLSystem 

olive/data/registry.py
Data component registration warns if a component has already been registered. However, this warning gets triggered every time a data config is initialized. This happens many times since data configs get converted to dict/json and back to object many times. 
There is nothing the user can do to prevent this so it should not be a warning. Changed to debug.
=> Don't warn for repeated data component registration

olive/model/__init__.py
Pytorch model adds values from the hf model config into model attributes to make them easily accessible. However, this makes the model json messy/confusing with values in model_attributes that are already in `model_config`. This PR removes information from model_attributes that is already in the hf_config.
=> Remove duplicate values from pytorch model json

examples/open_llama/README.md, examples/open_llama/open_llama_inc_woq.json, examples/open_llama/requirements-woq.txt, examples/open_llama/user_script.py, olive/passes/onnx/inc_quantization.py, test/unit_test/passes/inc/test_inc_quantization.py
Support 4-bits weight-only quantization with  Intel® Neural Compressor and add related example.
As large language models (LLMs) become more prevalent, there is a growing need for new and improved quantization methods that can meet the computational demands of these modern architectures while maintaining the accuracy. Compared to normal quantization like W8A8, weight only quantization (WOQ) is probably a better trade-off to balance the performance and the accuracy.
Two weight only algorithms are provided in this PR. Round-to-nearest (RTN) is the most straightforward way to quantize weight using scale maps. GPTQ algorithm provides more accurate quantization but requires more computational resources.
More detials please refer to this …
=> Enable Intel® Neural Compressor 4-bits weight-only quantization and add related example

.azure_pipelines/job_templates/olive-example-template.yaml, .azure_pipelines/job_templates/olive-test-template.yaml, test/unit_test/snpe/test_adb_run.py, test/unit_test/systems/python_environment/test_python_environment_system.py
Because of the `coverage run` command used to run unit and integrations tests, the `Test Olive` steps doesn't fail even when some tests fail. So we were not catching them. 
Set `failOnStandardError=True` for `PublishTestResults` tasks so that the test results task catches any failing tests. You can see this working as expected in this [test run](https://dev.azure.com/aiinfra/PublicPackages/_build/results?buildId=360973&view=results).
Also fixes failing tests caused by the recent lint related changes.
=> CI: Fail `PublishTestResults` when any test failed, Fix failing tests

olive/engine/engine.py
We currently use a hacky method to run `no_search` using `search_strategy`. This makes the logic confusing and unnecessarily complicated. 
Clean up the logic by just iterating over the pass flows directly.
=> Clean up `no_search` mode to not use `search_strategy`

examples/resnet/prepare_model_data.py
The default value for `num_epochs` in `prepare_model_data.py` is `0` so we are using a random model. The accuracy numbers and goals are meaningless for this. This also causes the resnet test to be flaky since the original accuracy ~10% and doen't have much freedom for movement.
Train it for atleast 1 epoch so that we are testing for a good model. 
 
=> Train original resnet for min 1 epoch

examples/resnet/prepare_model_data.py, examples/resnet/resnet_ptq_cpu.json, examples/resnet/resnet_ptq_cpu_aml_dataset.json
Updated the seed steps to make the model consistent accross runs. 
Update the accuracy goal in `resnet_ptq_cpu_aml_dataset.json` to increase the tolerance. This was not increased last time along with `r`resnet_ptq_cpu_aml_dataset.json`` and was causing the test to be flaky. Reduced the value for `resnet_ptq_cpu_aml_dataset.json` from `0.1` to `0.05` since the baseline is better now.
=> ResNet: Update seed_everything and accuracy goal

examples/resnet/resnet_vitis_ai_ptq_cpu.json, examples/test/test_resnet_vitis_ai_ptq_cpu.py, olive/passes/onnx/vitis_ai/quantize.py, olive/passes/onnx/vitis_ai/quantizer.py, olive/passes/onnx/vitis_ai_quantization.py, test/unit_test/passes/vitis_ai/test_vitis_ai_quantization.py
Update Vitis AI quantization to support ORT 1.16, support TensorData and QuantizationParams
https://github.com/microsoft/Olive/issues/629
=> Update Vitis AI quantization to support ORT 1.16, support TensorData and QuantizationParams

examples/open_llama/open_llama_qlora_tinycodes.json, examples/open_llama/qlora_user_script.py, olive/data/component/text_generation.py, olive/model/hf_utils.py, olive/passes/pytorch/qlora.py, test/unit_test/workflows/test_run_config.py
Some enhancements to the QLoRA pass and related components. 
Example use case scenario is for fine-tuning [microsoft/phi-1_5](https://huggingface.co/microsoft/phi-1_5). In order to load the model and config for this model non-interactively, we have to pass `trust_remote_code=True` to `model_loading_args`. However, the QLoRA pass and `get_hf_model_config` both ignore it.
There are also cases where we have to provide `token` for models like [meta-llama/Llama-2-7b](https://huggingface.co/meta-llama/Llama-2-7b). 
Both components have been updated to use the model_loading_args correctly. 
`microsoft/phi-1_5` gives a warning about `attention_mask` during training. Text-gen preprocessing is updated to make `attention_mask` optional (opt out if needed). 
Bug Fix: Check `pad_token_id` for `None` …
=> Text-gen: Optional attn mask. Loading args for hf model config. QLoRA: Update loading args 

examples/directml/stable_diffusion_xl/stable_diffusion_xl.py, examples/directml/stable_diffusion_xl/user_script.py
- The “unet_text_embeds_size” free dimension should always be overridden with a value of 1280 irrespective of image resolution - this value is same as the text_encoder_2 hidden dimension for both SD-XL base and refiner model. Currently using a resolution other than 1024 results in error.
- With the optimum pipeline, the right keyword to pass session options is “session_options” and not “sess_options”. This change improves perf by 40% for 512x512 resolution and about 10% for 1024x1024 resolution.
=> Fix bugs in how free dimension session options are set:

olive/engine/engine.py
In `no-search` mode, the `evaluate_input_model=True` case is only used if an evaluator is provided. Otherwise, it requires the user to explicitly set `evaluate_input_model=False`. 
Now the input model evaluation behavior is the same as for the output model: evaluate if evaluator provided. 
 
=> Optional `evaluate_input_model` in no-search mode

olive/evaluator/olive_evaluator.py, olive/passes/onnx/conversion.py, olive/passes/pytorch/qlora.py
In llamav2 tests, torch model occupied the gpu memory which leads to error when evaluate onnx model.
Release GPU memory for torch model evaluation
model.to("cpu") could not release gpu memory in time. Call torch.cuda.empty_cache() to cleanup.
=> 🆓 Release GPU memory for torch model evaluation

examples/bert/conda.yaml, olive/engine/engine.py, olive/exception/__init__.py, olive/passes/onnx/perf_tuning.py, test/unit_test/engine/test_engine.py, test/unit_test/passes/onnx/test_perf_tuning.py, test/unit_test/workflows/test_run_config.py
In perf-tuning, if the exception is known as ImportModuleError, we need not retry the next step. And we need throw the exception like in engine.
=> raise the known failure exceptions when do perf-tuning

olive/passes/onnx/transformer_optimization.py, test/unit_test/passes/onnx/test_transformer_optimization.py
=> raise ValueError if the model_type is None

olive/common/utils.py, olive/hardware/accelerator.py
As described in https://github.com/microsoft/Olive/issues/667, the name for rocm ep has a typo. onnxruntime uses `ROCMExecutionProvider` as the name.
=> Fix rocm ep name

examples/directml/stable_diffusion/config_safety_checker.json, examples/directml/stable_diffusion/config_text_encoder.json, examples/directml/stable_diffusion/config_text_encoder_2.json, examples/directml/stable_diffusion/config_unet.json, examples/directml/stable_diffusion/config_vae_decoder.json, examples/directml/stable_diffusion/config_vae_encoder.json, examples/directml/stable_diffusion_xl/config_text_encoder.json, examples/directml/stable_diffusion_xl/config_text_encoder_2.json, examples/directml/stable_diffusion_xl/config_unet.json, examples/directml/stable_diffusion_xl/config_vae_decoder.json, examples/directml/stable_diffusion_xl/config_vae_encoder.json, olive/passes/onnx/transformer_optimization.py
Update the description of the `fp16` related arguments in `OrtTransformersOptimization` pass to describe their relation to the `fp16` flag. 
The parameter orders have been updated to group the related parameters together. 
`force_fp16_inputs` has been moved from `optimization_options` into the pass config params. It is not part of `optimization_options` which are used for FusionOptions.
=> Update `fp16` related parameters in `OrtTransformersOptimization`

examples/llama2/llama2.py, olive/passes/onnx/quantization.py
`MatMul4BitsQuantizer` uses logging.basicConfig to set level to INFO and prints very verbose logs at INFO level. Suppress these logs by manually setting the loggers level to `ERROR`. 
Update ort version requirement to `>=1.16.2` since the quantizer will be added to 1.16.2.
Remove the save to tmp_dir -> load -> save steps since it is not needed. We only need to sort the model topologically before saving the model to file. Refer to this discussion for more context https://github.com/microsoft/Olive/pull/641#discussion_r1373793462. 
`llama.py`: Correct description for `--only_config` option. Create a new user_script file for the workflow instead of updating the original one.
=> OnnxMatMul4Quantizer: Suppress quantizer logs, no tmp_dir

olive/logging.py, olive/passes/onnx/quantization.py, olive/workflows/run/run.py
From the time being, all ORT Python logging is missing except the root logger. This PR enable it
Turn on quant_pre_process to detail logs and let the logging level control what should be shown.
=> Enable ORT Python logging

docs/source/conf.py
Reverting the qualcomm linkcheck change in https://github.com/microsoft/Olive/pull/682. 
Some of the qualcomm link checks are still flaky.
=> Disable qualcomm linkcheck

examples/phi/requirements.txt
The latest version of transformers (>= 4.35.0) is not compatible with the model. PRs:  https://github.com/huggingface/transformers/pull/27020, https://github.com/huggingface/transformers/pull/27073 change the expected signature of `_set_gradient_checkpointing` which now doesn't match the model's https://huggingface.co/microsoft/phi-1_5/blob/main/modeling_mixformer_sequential.py#L802
=> Pin `transformers` version in `phi` example

docs/source/overview/options.md, olive/passes/onnx/quantization.py, olive/workflows/run/config.py, olive/workflows/run/run.py
Add a new option called `ort_py_log_severity_level` for onnxruntime python logs. 
The levels used for onnxruntime python logs are not consistent across its modules. For example, MatMul4BitsQuantizer is very verbose at `INFO` level. 
Olive is not verbose at `INFO` level and only logs important high-level information. So, it is better to create a separate logging level control for ort python logs and set it at a higher default level.
=> Separate logging level for ort python logs

examples/phi/README.md, examples/phi/phi_qlora_tinycodes.json, olive/passes/pytorch/lora.py
These passes enabled gradient checkpointing without checking if the model supports it. 
Now, it not supported, they log a warning and force `gradient_checkpointing` to `False`.
Also set `gradient_checkpointing` in `phi` example to `False` since it doesn't actually do gradient checkpointing and the flag might be set to False in a future update. 
 
=> [LoRA/QLoRA] Check for gradient checkpointing support before enabling it

docs/source/api/models.rst, examples/llama2/tensor_parallel_config.json, examples/llama2/tensor_parallel_user_script.py, olive/evaluator/olive_evaluator.py, olive/model/__init__.py, olive/passes/pytorch/__init__.py, olive/passes/pytorch/tensor_parallel.py, olive/passes/pytorch/tensor_parallel_layers.py, olive/passes/pytorch/tensor_parallel_llama2.py, pyproject.toml
Implement DistributedPyTorchModel
DistributedPyTorchModel is parallel to DistributedOnnxModel for PyTorch models.
Also, introducing an example, Llama2, as an use case.
=> Implement DistributedPyTorchModel

olive/passes/onnx/perf_tuning.py, test/unit_test/passes/onnx/test_perf_tuning.py
This pull request includes changes to improve testing and mocking in `test/unit_test/passes/onnx/test_perf_tuning.py` and add support for specifying device and execution provider in the default configuration of the ONNX pass in `olive/passes/onnx/perf_tuning.py`.
Testing improvements:
* <a href="diffhunk://#diff-3c4b1c200e2ac992cd17d17e72a48402d7376e0dcc11d3c4a3728d630ec48097L14-R35">`test/unit_test/passes/onnx/test_perf_tuning.py`</a>: Added additional test cases and import statements to improve testing and mocking. <a href="diffhunk://#diff-3c4b1c200e2ac992cd17d17e72a48402d7376e0dcc11d3c4a3728d630ec48097L14-R35">[1]</a> <a href="diffhunk://#diff-3c4b1c200e2ac992cd17d17e72a48402d7376e0dcc11d3c4a3728d630ec48097R5">[2]</a>
Pass improvements:
* <a …
=> 📁 Fill Perf Tuning default config with accelerator spec

docs/source/overview/options.md, examples/llama2/.gitignore, examples/llama2/README.md, examples/llama2/llama2.py, examples/llama2/llama2_template.json, examples/llama2/user_script.py, olive/evaluator/metric_config.py, olive/evaluator/olive_evaluator.py, olive/passes/onnx/inc_quantization.py, olive/passes/onnx/perf_tuning.py, olive/passes/onnx/quantization.py, olive/passes/onnx/vitis_ai_quantization.py, olive/passes/openvino/quantization.py, olive/passes/snpe/quantization.py, test/unit_test/evaluator/test_olive_evaluator.py, test/unit_test/passes/onnx/test_perf_tuning.py, test/unit_test/systems/test_local.py, test/unit_test/utils.py
This PR makes the user script functions such as `dataloader_func` more flexible by allowing the user to provide `kwargs` for the functions. 
- In MetricConfig, the kwargs are provided as a dict of dicts. the outer dict is indexed by the name of the function param and the inner dict contains the kwargs for that func. 
- In passes, a new param called `dataloader_func_kwargs` is added to be used with the `dataloader_func` param. 
Docs have been updated to reflect the current state of the functions and their uses.
`llama` example has been updated to use kwargs for the `model_id` instead of hard-coding the values into the user_script. Now, the same user script works for all models. 
Users can now provide `kwargs` to user script functions such as `dataloader_func` and `evaluate_func`.
=> Option to provide kwargs to user_script functions

examples/llama2/README.md, examples/llama2/llama2_template.json, examples/llama2/user_script.py, olive/passes/onnx/transformer_optimization.py
onnxruntime 1.16.2 just got released. The llama example and `OrtTransformersOptimization._replace_mha_with_gqa` are updated to sync with it. 
The calibration dataloaders for Inc smooth quant are removed since we don't have use for them currently and they are out of date. 
**Note:** onnxruntime cpu package is only available for x64 python 3.10 right now. https://github.com/microsoft/onnxruntime/issues/18378
**gpu_mha**
**gpu_gqa (no shared kv buffer)**
**gpu_gqa (shared kv buffer)**
=> [LlaMA2] Sync with onnxruntime 1.16.2

examples/directml/llama_v2/config.py, examples/directml/llama_v2/llama_v2.py, examples/directml/llama_v2/run_llama_v2_dynamic_io_binding.py, examples/directml/llama_v2/run_llama_v2_io_binding.py, examples/directml/llama_v2/user_script.py
Being able to generate the model with few layers makes the ONNX conversion and optimization steps so much faster, which makes it easier to debug it.
=> Add option to generate fewer layers in DML llama 2 example

olive/evaluator/olive_evaluator.py, test/unit_test/evaluator/test_olive_evaluator.py
Use the joint metric key to ensure the uniqueness of metric set with priorities.
=> 🔑 Distinct metric priority with joint key

examples/llama2/llama2_qlora.json, examples/open_llama/README.md, examples/open_llama/open_llama_lora_tinycodes.json, examples/open_llama/open_llama_qlora_ort_tinycodes.json, examples/open_llama/open_llama_qlora_tinycodes.json, examples/open_llama/requirements-qlora-ort.txt, examples/phi/phi_qlora_tinycodes.json, olive/extra_dependencies.json, olive/passes/pytorch/lora.py, olive/workflows/run/run.py
Changes in this PR:
- Full `float16` training is unstable. Now the lora passes use mixed-precision training (`fp16=True` in the trainer) when `torch_dtype` is `float16`.
- `compute_dtype` for the quantized modules is a separate config parameter to allow for flexibility. If not provided, use the same dtype as `torch_dtype`
- Support for `onnxruntime-training`. 
Also adds an example for qlora with onnxruntime-training.
=> LoRA/QLoRA: Mixed precision for `torch_dtype=float16`, Support onnxruntime-training

examples/directml/llama_v2/run_llama_v2_dynamic_io_binding.py, examples/directml/llama_v2/run_llama_v2_io_binding.py
Adding a --model_dir argument allows users to easily point the example to their models that have already been pre-optimized.
=> Add a --model_dir argument to the DirectML LLaMA 2 example

examples/falcon/config.json, examples/llama2/llama2_qlora.json, examples/open_llama/llama_qlora.json, examples/open_llama/open_llama_lora_tinycodes.json, examples/open_llama/open_llama_qlora_ort_tinycodes.json, examples/open_llama/open_llama_qlora_tinycodes.json, examples/open_llama/open_llama_sparsegpt_gpu.json, examples/phi/phi_qlora_tinycodes.json, olive/data/component/load_dataset.py, olive/data/component/pre_process_data.py, olive/data/component/text_generation.py, olive/data/config.py, olive/model/__init__.py, olive/model/hf_utils.py, olive/passes/pytorch/lora.py, olive/workflows/run/config.py, test/unit_test/passes/pytorch/test_lora.py, test/unit_test/passes/pytorch/test_sparsegpt.py, test/unit_test/passes/pytorch/test_torch_trt_conversion.py, test/unit_test/workflows/mock_data/text_generation_dataset.json, test/unit_test/workflows/mock_data/text_generation_dataset_random.json, test/unit_test/workflows/test_run_config.py
This PR 
- exposes `trust_remote_code` arguments to huggingface data components that require user permission to run remote code. For input models with hf config model_loading_args, the value for `trust_remote_code` is auto inserted into the data configs without these specified. 
- makes the default value for `dataset_type` in `test_generation_pre_process` component to `corpus`. Previously, the data config set it to `None` if not given and this results in using `pair` strategy. 
- Casts attention mask to input_id's data type to ensure it has the expected data type. 
- Removes `"dataset_type":"corpus"` from the examples since it is the default and the most common type.
- Corrects the dataset config in falcon example. Dataset is also changed to `timdettmers/openassistant-guanaco` since the …
=> `trust_remote_code` for hf data components, Default text-gen corpus dataset_type

examples/directml/stable_diffusion/user_script.py
The `unet_inputs` function has `return_dict` as a direct member of `inputs`. 
When `unet_conversion_inputs` changes `inputs` into tuples, `return_dict` is set as the fourth positional argument. But, it is not the fourth positional argument for the `forward` function of the model https://github.com/huggingface/diffusers/blob/4e54dfe985293df9e6e86828d7a2763d076879f5/src/diffusers/models/unet_2d_condition.py#L797. 
Torch exporter incorrectly assumes it is the value for the actual fourth argument `class_labels` and `return_dict` just uses it's default value `True`.
It appears the value of `return_dict` doesn't affect the exported model since the xl example doesn't set it. 
`class_labels` is unused so it didn't catch it too.
But this issue becomes more relevant when we want to add other …
=> Use keyword argument for `return_dict` in unet dummy input

examples/directml/dolly_v2/config_dolly_v2.json, examples/directml/llama_v2/config_llama_v2.json, examples/directml/stable_diffusion/config_safety_checker.json, examples/directml/stable_diffusion/config_text_encoder.json, examples/directml/stable_diffusion/config_text_encoder_2.json, examples/directml/stable_diffusion/config_unet.json, examples/directml/stable_diffusion/config_vae_decoder.json, examples/directml/stable_diffusion/config_vae_encoder.json, examples/directml/stable_diffusion_xl/config_text_encoder.json, examples/directml/stable_diffusion_xl/config_text_encoder_2.json, examples/directml/stable_diffusion_xl/config_unet.json, examples/directml/stable_diffusion_xl/config_vae_decoder.json, examples/directml/stable_diffusion_xl/config_vae_encoder.json
`opt_level` isn't used for DML since we don't use the `optimize_by_onnxruntime` pass and instead specify each fusion manually. But if we set an opt_level higher than 0, we get some non-fatal error that confuses users and makes them think that the models didn't get optimized.
=> Set an opt_level of 0 for the DML examples

docs/source/overview/options.md, olive/logging.py, olive/workflows/run/config.py, olive/workflows/run/run.py
This pull request to the `olive` package introduces changes related to logging. It enable logging to file.
Summary of changes:
* <a href="diffhunk://#diff-a827196271eab94264068963f45451a73f0c526598f07be943152a189fee81b1R41">`olive/workflows/run/config.py`</a>: Added a new `log_to_file` attribute to the `RunEngineConfig` class to control logging to a file in the `run` function.
=> enable file logging

olive/passes/onnx/optimum_conversion.py, olive/passes/onnx/optimum_merging.py, test/unit_test/passes/onnx/test_optimum_conversion.py
Complete optimum conversion/merge configs.
Take conversion as example, the `fp16=True` means to load the torch model with float16 from huggingface model hub. Then the fp16 torch model is converted to onnx model. 
That is different the fp16 in transformer optimization.
=> 🌵 Complete optimum conversion/merge configs

olive/passes/onnx/transformer_optimization.py
Fix output path for ranked models generated by transformer optimization pass
Ranked model includes the model suffix name i.e. model_XX.onnx and the pass should avoid appending it again.
=> Fix output path for ranked models generated by transformer optimization pass

olive/workflows/run/config.py
`log_to_file` is a field of `RunEngineConfig` but it is not used to instantiate the engine. Remove it from the config dict before creating the engine. 
Otherwise it triggers the following warning:
```
[WARNING] [config_utils.py:308:validate_config] Keys {'log_to_file'} are not part of EngineConfig. Ignoring them.
```
=> Remove `log_to_file` from RunEngineConfig.create_engine

olive/model/__init__.py, olive/passes/olive_pass.py, olive/passes/onnx/append_pre_post_processing_ops.py, olive/passes/onnx/bnb_quantization.py, olive/passes/onnx/conversion.py, olive/passes/onnx/float16_conversion.py, olive/passes/onnx/inc_quantization.py, olive/passes/onnx/insert_beam_search.py, olive/passes/onnx/mixed_precision.py, olive/passes/onnx/model_optimizer.py, olive/passes/onnx/optimum_merging.py, olive/passes/onnx/quantization.py, olive/passes/onnx/transformer_optimization.py, olive/passes/onnx/vitis_ai_quantization.py
For example in the case of onnx model components optimization workflow: conversion -> optimization -> mixed_precision -> etc.
Some passes like mixed_precision will forget the original model name(decoder.onnx, encoder.onnx etc) and use the default `main.onnx`.
This PR is used to unify the output cache model name.
Previous:
Now:
=> 🧇 Unify the cache model name

examples/llama2/llama2_tensor_parallel.json, examples/llama2/tensor_parallel_inference.py, examples/llama2/user_script.py, olive/model/__init__.py, olive/passes/onnx/conversion.py, olive/passes/onnx/transformer_optimization.py, olive/passes/pytorch/__init__.py, olive/passes/pytorch/tensor_parallel.py, olive/passes/pytorch/tensor_parallel_layers.py, olive/passes/pytorch/tensor_parallel_llama2.py
Fix pytorch tensor parallel implementation
* Previous verification was a false positive. The process was loading the entire model during the OnnxConversion pass resulting in exporting the same model i.e. the entire model for reach rank. The issue was found when attempting to export the Llama 70b model which kept running out of memory and the number of parameters reflected the error.
* Swap out of use of MPI in favor of multiprocessing since the latter is much easier to work with and debug. Important finding is that TensorParallel & OnnxConversion pass doesn't require MPI to succeed.
* Refactored the TensorParallel pass to work with multiprocessing jobs to speed up the process.
* Added OrtTransformersOptimization to Llama2 tensor parallel config
* Fixed Llama2 user script to account for …
=> Fix pytorch tensor parallel implementation

olive/passes/onnx/quantization.py
For some uses, they still want to try S8S8 with QOperator quantization config. But Olive directly prune it.
This PR is used to warn the S8S8 QOperator quantization but not pruning.
=> 🧇 Warn the S8S8 QOperator quantization but not pruning

olive/extra_dependencies.json
Fix bug https://dev.azure.com/aiinfra/Model%20optimization%20Toolkit/_workitems/edit/20033 
This security bug is about pydash used by azure-ai-ml less than 1.11.1, which use pydash 5.1.2. PR https://github.com/Azure/azure-sdk-for-python/pull/32433 fix the security issue. 
In this PR, we just upgrade azure-ai-ml dependency to use that fix.
=> fix security bug 20033

docs/source/overview/options.md, olive/common/ort_inference.py
Add the inference_settings options to turn on the ORT profiling when there are perf issues.
=> add enable_profiling options to collect ORT perf data in Olive

examples/open_llama/README.md, examples/open_llama/open_llama_qlora_ort_tinycodes.json, examples/open_llama/requirements-qlora-ort.txt, olive/extra_dependencies.json, olive/passes/onnx/conversion.py, olive/passes/pytorch/lora.py, olive/workflows/run/run.py, test/unit_test/passes/pytorch/test_lora.py
ONNX Runtime training now supports `bfloat16` for lora and qlora.
This PR
- Enables ort-training + bfloat16 by setting `ORTMODULE_ONNX_OPSET_VERSION` environment variable. Default value is 16 which is required for models with operators such as Where.
- Adds unit test for the environment variable.
- Improves dependency checks in the lora passes.
- Better organizes the extras for lora/qlora. Workflow setup allows assigning multiple extras to a single pass.
LoRA/QLoRA support `bfloat16` with ort-training.
=> LoRA/QLoRA: Add `bfloat16` support for ort-training

docs/source/overview/options.md, olive/azureml/azureml_client.py, olive/common/utils.py, olive/extra_dependencies.json, olive/systems/azureml/aml_evaluation_runner.py, olive/systems/azureml/aml_pass_runner.py, olive/systems/azureml/aml_system.py, olive/systems/docker/docker_system.py, olive/systems/docker/eval.py, olive/systems/local.py, olive/systems/olive_system.py, olive/systems/python_environment/python_environment_system.py, olive/systems/system_config.py, test/unit_test/systems/azureml/test_aml_system.py
Add hf_token support for olive systems.
- For local system, Docker system, and PythonEnvironment system, Olive will get the token from local.
- For AzureML system, Olive will retrieve the token from user keyvault secret. Olive will reserve `HF_TOKEN` secret name specifically for hf token fetch.
I'll send another PR to update [huggingface doc](https://microsoft.github.io/Olive/features/huggingface_model_optimization.html) for the keyvault detailed use case.
=> Add hf_token support for olive systems

olive/passes/onnx/perf_tuning.py
Simplify perf tuning logging output
Before:
After:
=> 🦺 Simplify perf tuning logging output

examples/directml/stable_diffusion/README.md, examples/directml/stable_diffusion/config_safety_checker.json, examples/directml/stable_diffusion/config_text_encoder.json, examples/directml/stable_diffusion/config_text_encoder_2.json, examples/directml/stable_diffusion/config_unet.json, examples/directml/stable_diffusion/config_vae_decoder.json, examples/directml/stable_diffusion/config_vae_encoder.json, examples/directml/stable_diffusion/requirements-common.txt, examples/directml/stable_diffusion/requirements.txt, examples/directml/stable_diffusion/stable_diffusion.py, examples/directml/stable_diffusion_xl/README.md, examples/directml/stable_diffusion_xl/config_text_encoder.json, examples/directml/stable_diffusion_xl/config_text_encoder_2.json, examples/directml/stable_diffusion_xl/config_unet.json, examples/directml/stable_diffusion_xl/config_vae_decoder.json, examples/directml/stable_diffusion_xl/config_vae_encoder.json, examples/directml/stable_diffusion_xl/requirements-common.txt, examples/directml/stable_diffusion_xl/requirements.txt, examples/directml/stable_diffusion_xl/stable_diffusion_xl.py
This PR adds `--provider` option to the stable diffusion example so that the user can optimize the model for cuda ep instead if desired. 
The directml ep and settings are still the default so the interface and outputs does not change at all for it. 
In a follow-up PR, I will add an example test for the cuda ep if the memory and time requirements for the stable diffusion (not xl) example fits on our gpu pool. 
Stable Diffusion and Stable Diffusion XL models can now be optimized for CUDA EP using `--provider cuda` option.
=> Add CUDA EP optimization option to Stable Diffusion examples

olive/common/utils.py, olive/engine/packaging/packaging_generator.py, olive/model/__init__.py, olive/resource_path.py, olive/systems/azureml/aml_pass_runner.py, olive/systems/azureml/aml_system.py, olive/systems/docker/utils.py, test/unit_test/common/test_copy_dir.py
As described in https://github.com/microsoft/Olive/issues/777, `shutil.copytree` fails with `shutil.Error` even though all files are copied. 
https://bugs.python.org/issue36823
This PR adds a new utils function `copy_dir` that wraps `shutil.copytree` to handle the above case. As a heuristic, we check that all required file names exist in the destination directory in the event of an error. 
 
=> Handle `shutil.Error` from `shutil.copytree`

docs/source/overview/options.md, examples/phi/phi_qlora_tinycodes.json, olive/model/hf_utils.py, olive/passes/onnx/conversion.py, olive/passes/pytorch/lora.py, olive/workflows/run/config.py, test/unit_test/model/test_hf_utils.py, test/unit_test/model/test_pytorch_model.py, test/unit_test/passes/pytorch/test_lora.py, test/unit_test/workflows/test_run_config.py
Rename `HFModelLoadingArgs` to `HFFromPretrainedArgs`.
###
User interface change:
In model config, the `model_loading_args` should be `from_pretrained_args` instead:
```
"input_model":{
"type": "PyTorchModel",
"config": {
"hf_config": {
"model_name": "microsoft/phi-1_5",
"task": "text-generation",
"model_loading_args" -> "from_pretrained_args": {
"trust_remote_code": true
}
}
}
}
```
=> Rename HFModelLoadingArgs to HFFromPretrainedArgs

olive/passes/onnx/vitis_ai/quant_utils.py, olive/passes/onnx/vitis_ai/quantizer.py
https://github.com/microsoft/onnxruntime/pull/18465 made some changes that make the vitis ai quantizer incompatible with the latest ort code. 
This PR updates the vitis ai code to add `quant_type` to `QuantizationParams` if the ORT version >= 1.17.0.
=> Make VitisAI quantization compatible with latest ORT-nightly

olive/model/handler/mixin/json.py, olive/model/handler/onnx.py, olive/model/handler/optimum.py, olive/model/handler/pytorch.py
Most model handler classes update the `to_json` method in the same way. This PR makes it unnecessary by allowing a handler class to specify what attributes should be added during json serialization through `jsonify_config_keys` attribute.
=> Add `jsonify_config_keys` to `JsonMixin` to abstract model handler json serialization

examples/whisper/prepare_whisper_configs.py, test/unit_test/workflows/test_whisper_workflow.py
Fix the whisper failure for new released transformers 4.36.0
error info:
> ValueError: Attention using SDPA can not be traced with torch.jit.trace when no attention_mask is provided. To solve this issue, please either load your model with the argument `attn_implementation="eager"` or pass an attention_mask input when tracing the model.
=> 🏑 Tests fix for transformers 4.36.0

.azure_pipelines/job_templates/olive-build-template.yaml, .azure_pipelines/job_templates/olive-test-template.yaml, .azure_pipelines/olive-ci.yaml, .azure_pipelines/olive-ort-last.yaml, .azure_pipelines/olive-ort-nightly.yaml, .azure_pipelines/performance.yaml, test/requirements-test-gpu.txt, test/unit_test/passes/onnx/test_bnb_quantization.py, test/unit_test/passes/onnx/test_conversion.py, test/unit_test/passes/pytorch/test_lora.py, test/unit_test/passes/pytorch/test_torch_trt_conversion.py
- Add a new Linux GPU unit test to the CI, nightly and last stable pipelines
- Tests that mocked bitsandbytes and torch cuda devices are now made gpu only. Some are linux gpu only if they require bitsandbytes. 
- The above also fixes the inconsistent lora and qlora tests. 
- `OLIVE_POOL_UBUNTU2004_GPU_V100` uses a `Standard_NC6s_v3` agent (1 V100 GPU, 16GB vram, 112 ram).
=> Add Linux GPU unit test to pipelines

examples/directml/stable_diffusion/README.md, examples/directml/stable_diffusion/requirements-common.txt, examples/directml/stable_diffusion_xl/README.md, examples/directml/stable_diffusion_xl/requirements-common.txt, examples/stable_diffusion/README.md
- Remove torchvision from the requirements since it is not used at all. It also caused torch to be pinned to 1.13.1 unnecessarily.
- Move CUDA EP instructions to the readme under `examples/stable_diffusion`.
=> SD/SDXL: Remove torchvision from requirements, CUDA instructions under main README

.azure_pipelines/job_templates/olive-example-template.yaml, .azure_pipelines/olive-ci.yaml, .azure_pipelines/olive-ort-last.yaml, .azure_pipelines/olive-ort-nightly.yaml, examples/directml/stable_diffusion/stable_diffusion.py, examples/directml/stable_diffusion/user_script.py, examples/directml/stable_diffusion_xl/stable_diffusion_xl.py, examples/test/test_bert_cuda_gpu.py, examples/test/test_stable_diffusion_cuda_gpu.py
**Stable Diffusion**
- Add test script that parameterizes over three models: base, turbo and lora finetuned.
- Make GUI related imports lazy since the pipeline agents are not configured for tkinter
- Allow onnxruntime 1.16.2/1.16.3 with warning. Disable skip_group_norm fusion which causes the invalid model issue. This lets us test the example with onnxruntime-gpu and ort-nightly-gpu
**Bert**
- Add local_system test case for bert cuda
Will add a similar stable_diffusion_xl example test later if the pipeline resources are enough.
=> CI: Local CUDA test for Stable Diffusion and Bert

examples/whisper/code/user_script.py, examples/whisper/code/whisper_dataset.py, examples/whisper/prepare_whisper_configs.py, examples/whisper/test_transcription.py, examples/whisper/whisper_template.json, olive/passes/utils/whisper_prepost.py
Whisper example doesn't work with `openai/whisper-large-v3` since `N_MELS` is hardcoded to `80` in both olive and onnxruntime-extensions but the v3 model uses `128`.
In this PR:
- Use whisper config/processor to get the correct number of mel bins
- for onnxruntime-extensions, we update the constant used by it in the append pre/post processing utils. This is a temporary workaround until ort-extensions also supports dynamic value for `N_MELS`. 
- Dataloader updated to accept `model_name`
Fixes:
https://github.com/microsoft/Olive/issues/823
=> Whisper: Support `openai/whisper-large-v3` using dynamic `N_MELS`

examples/directml/stable_diffusion_xl/config_text_encoder_2.json
The second dimension for `text_embeds` output in `text_encoder_2` is `1280` and not dynamic. We can also see it in the same of `text_embeds` passed to the unet https://github.com/microsoft/Olive/blob/1344ff16b7cbf272a2e727ae9ba1ed7a20d51d2e/examples/directml/stable_diffusion_xl/user_script.py#L86
We remove the incorrect dynamic axis for this output. The hufggingface converted onnx text_encoder_2 also has the same incorrect shape. https://huggingface.co/stabilityai/stable-diffusion-xl-base-1.0/tree/main/text_encoder_2
=> SDXL: Remove incorrect dynamic axis for text_encoder_2

examples/directml/stable_diffusion_xl/stable_diffusion_xl.py, examples/directml/stable_diffusion_xl/user_script.py, examples/stable_diffusion/README.md
[madebyollin/sdxl-vae-fp16-fix](https://huggingface.co/madebyollin/sdxl-vae-fp16-fix) is a modified SDXL vae that can run in fp16 without generating NaNs. 
This PR:
- Adds `--use_fp16_fixed_vae` option to use this vae instead. With this, the whole model can be in fp16 without need for fp32 io. 
- Only enabled for cuda currently. Will be enabled for dml in a separate PR after validating the model. 
The default stable diffusion watermarker doesn't support fp16 models and there is no option in the `from_pretrained` method to disbable it. I already have PR with a potential fix on the optimum repo https://github.com/huggingface/optimum/pull/1603. For now, we can manually set the watermarker to `None`.
=> SDXL: Allow using fp16 fixed vae for CUDA provider

examples/phi/phi_qlora_tinycodes.json, examples/phi/requirements.txt
The transformers version in the phi example is unpinned since the gradient checkpointing issue has already been addressed in Olive. This also resolves the security issue from transformers < 4.36.0. 
Plus some config fixes.
=> Phi: Unpin transformers version

examples/whisper/README.md, examples/whisper/code/user_script.py, examples/whisper/code/whisper_dataset.py, examples/whisper/prepare_whisper_configs.py, examples/whisper/test_transcription.py, examples/whisper/whisper_template.json, olive/passes/onnx/insert_beam_search.py, olive/passes/utils/whisper_prepost.py
- Expose missing beam search options `use_vocab_mask`, `use_prefix_vocab_mask` and `use_logits_processor` that were added in ORT 1.16 along with `use_forced_decoder_ids`.
- Expose `skip_special_tokens` option in whisper pre-post-processing
- `use_logits_processor` enables timestamps in the whisper output. The output text looks something like 
```
"...<|3.00|> The ache of his overstrained eyes,<|6.00|><|6.00|> even the soaring arena around him with thousands of spectators,<|10.00|><|10.00|> which revealed he's not worth thinking about.<|13.00|>"
```
- Add transformers optimization pass to `gpu,int8` workflow. It was originally omitted due to some bug in ort but was corrected a while ago. I had forgotten to add it back since we never used the gpu workflow until the fp16 workflow was recent …
=> Whisper: Expose missing options, Enable timestamps, Transformers opt in `gpu_int8`

docs/source/features/passes/onnx.md, olive/common/ort_inference.py, olive/evaluator/metric_config.py, olive/evaluator/olive_evaluator.py, olive/hardware/accelerator.py, olive/model/handler/onnx.py, olive/model/utils/onnx_utils.py, olive/passes/onnx/perf_tuning.py, test/unit_test/evaluator/test_olive_evaluator.py, test/unit_test/model/test_onnx_model.py, test/unit_test/passes/onnx/test_perf_tuning.py
* Change the execution provider priority to use the parameters instead of that one in inference_settings. 
Bug description: In DLIS scenarios, the inferenece_settings is something like:
{'execution_provider': [('MIGraphXExecutionProvider', {})]} and the provider_lists specified in perf_tuning is: ['ROCMExecutionProvider', 'MIGraphXExecutionProvider'].
Originally, the inference_settings priority is higher than the execution_providers specified in arguments. As the result, when calling OnnxEvaluator.evaluate with the provider_list in baseline evaluation, the execution provider will be used as ["MIGraphXExecutionProvider"]. Later, the OnnxEvaluator.disable_ort_fallback(session, execution_providers) will check whether the underlying session's providers(MIGraphXExecutionProvider, …
=> Fix perftuning to meet DLIS integration requirements

examples/directml/dolly_v2/config_dolly_v2.json, examples/open_llama/open_llama_arc.json, examples/open_llama/open_llama_config.json, examples/open_llama/open_llama_inc_woq.json, examples/open_llama/requirements-woq.txt, examples/open_llama/user_script.py, examples/red_pajama/config.json, olive/passes/onnx/optimum_conversion.py, test/unit_test/passes/onnx/test_optimum_conversion.py, test/unit_test/utils.py
The `OptimumConversion` pass adds the following config parameters:
- `components`: #833 deprecated the `OptimumModelHandler` but uses a pytorch model with components. However, the components in the pytorch model handler doesn't make sense since conceptually, the pytorch model has no components and also causes #847. They are only used by the optimum conversion pass. So, making this a config parameter of the pass makes more sense.
Some other changes:
- Check the version of optimum and log a warning message about the different behavior of optimum for <1.14.0. 
- `legacy` and `no_post_process` must be passed as part of `extra_args`. The examples are still on legacy model but could be updated in the future to the latest single model.
- all external data config parameters are removed since they …
=> OptimumConversion: `components` option, version check

examples/snpe/inception_snpe_qualcomm_npu/README.md, examples/snpe/inception_snpe_qualcomm_npu/inception_config.json, examples/snpe/vgg_snpe_qualcomm_npu/README.md, examples/snpe/vgg_snpe_qualcomm_npu/debug.py, examples/snpe/vgg_snpe_qualcomm_npu/vgg_config.json, examples/stable_diffusion/openvino/stable_diffusion.py, olive/evaluator/olive_evaluator.py, olive/snpe/configure.py, olive/snpe/create_python36_env.sh, olive/snpe/create_python_env.sh, olive/snpe/utils/local.py, setup.py
There are a few issues for current SNPE examples:
1. The libxx.so under customized `python3.6` need to be put visible for system for SNPE cmd running
- put `str(Path(f"{snpe_root}/python36-env/lib"))` under `LD_LIBRARY_PATH` can fix.
2. SNPE evaluation extent the logits wrongly, 
- fixed in this PR.
3. We did not support tensorflow model evaluation.
- update examples without input model evaluation.
4. Wrong metrics config for inception examples
5. Importing issue for vgg, tell that in README.md to let user update it manually as a workaround.
6. Python3.6 seems a bit outdated for latest SNPE updates. The vgg example failed to be run. Updated the python env to 3.8 can fix.
=> 🐌 SNPE env and example fix

test/integ_test/evaluator/azureml_eval/test_aml_evaluation.py, test/integ_test/evaluator/docker_eval/test_docker_evaluation.py, test/integ_test/evaluator/local_eval/test_local_evaluation.py, test/unit_test/evaluator/test_metric_backend.py, test/unit_test/evaluator/test_olive_evaluator.py, test/unit_test/systems/azureml/test_aml_system.py, test/unit_test/systems/test_local.py
The purpose of this PR is to make the local UT discovery doesn't depends on the OLIVEWHEELS_STORAGE_CONNECTION_STRING used by integration test download model from azure blob
=> Make test discovery lazy call functions

docs/source/api/passes.rst, docs/source/features/passes/pytorch.md, examples/open_llama/README.md, examples/open_llama/open_llama_loftq_tinycodes.json, examples/open_llama/requirements-lora.txt, olive/passes/pytorch/__init__.py, olive/passes/pytorch/lora.py, test/unit_test/passes/pytorch/test_lora.py
This PR adds a new pass `LoftQ` which is based on the paper https://arxiv.org/abs/2310.08659. 
It adds on the qlora fine tuning approach by initializing the quantization and lora adapters together. This "alleviates the discrepancy between the quantized and full-precision model and significantly improves generalization in downstream tasks". 
Since most of the fine-tuning steps are the same as `QLoRA`, the common code has been abstracted into a new base class called `QLoRABase`. `LoftQ` is a separate pass and not an option for `QLoRA` so that we don't conflate it too much and make the configuration confusing for the user. They can just switch the pass type instead.
 
Introduced a new pass `LoftQ` which performs model fine-tuning using the LoftQ initialization proposed in …
=> Add `LoftQ` pass

olive/passes/onnx/conversion.py, test/unit_test/passes/onnx/test_conversion.py
* allow onnx conversion to support both past_key_values.index.key/value (normal case like llama2) and past_key_value.index (phi2 case)
* remove the buggy flag opset_version when invoking dynamo_export.
=> Allow onnx conversion support past_key_values.index pattern for phi2

examples/mobilenet_qnn_qualcomm_npu/download_files.py, olive/platform_sdk/qualcomm/runner.py
1. Update mobilenet_archive_url: onnx/model updated model structure recently. The original link to mobilenet is invalid. 
2. remove useless arguments from runner.
=> 🧮 Update mobilenet_archive_url

olive/evaluator/metric.py, olive/evaluator/olive_evaluator.py, olive/systems/python_environment/python_environment_system.py
refactor get_inference_settings to make it could contains the settings used by next perf tuning feature
=> move metric get_inference_settings method to metric class

examples/bert/user_script.py
Fix bug of  `TypeError: Accuracy.__new__() missing 1 required positional argument: 'task'` in bert example
=> Fix accuracy eval func in bert example

olive/passes/onnx/vitis_ai/quant_utils.py, olive/passes/onnx/vitis_ai/quantizer.py, test/unit_test/passes/vitis_ai/test_vitis_ai_quantization.py
PR https://github.com/microsoft/onnxruntime/pull/18043 (onnxruntime) extends onnxruntime quantization tools to support float16 weights. To do so, it enforces scale and zerop_point to be strongly typed (as `numpy.array(single_value, dtype=dtype)`). scale type should always be the weight type, and zero_point type the quantized weight type. That convention is checked all along the quantization tools to make sure there is loss of information. This change was made to avoid adding new arguments in many functions to carry this information.
=> Fix quantization dtypes after ORT PR #18043

test/unit_test/passes/onnx/test_quantization.py
The UT is used to cover the calibration signature changes in ORT. After the PR is merged, the CI pipelines with ort-nightly would fail with the following error message.
```txt
C:\Users\myguo\.conda\envs\ortnightly\lib\site-packages\onnxruntime\quantization\quantize.py:497: in quantize_static
tensors_range = calibrator.compute_data()
C:\Users\myguo\.conda\envs\ortnightly\lib\site-packages\onnxruntime\quantization\calibrate.py:523: in compute_data
return TensorsData(cal, self.collector.compute_collection_result())
C:\Users\myguo\.conda\envs\ortnightly\lib\site-packages\onnxruntime\quantization\calibrate.py:64: in __init__
self.data[k] = TensorData(lowest=v[0], highest=v[1], hist=v[2], bins=v[3])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
self = …
```
=> add quantization UT for calibration bug in ort-nightly build

olive/evaluator/olive_evaluator.py, olive/hardware/accelerator.py, olive/model/handler/onnx.py, olive/model/utils/onnx_utils.py, olive/passes/onnx/perf_tuning.py, test/unit_test/evaluator/test_olive_evaluator.py, test/unit_test/model/test_onnx_model.py, test/unit_test/passes/onnx/test_perf_tuning.py
allow `tunable_op_enable` and `tunable_op_tuning_enable` for ROCM ep to speed up the performance.
The two flags need to be set to True for ROCMExecutionProvider to speed up the performance when running in AMD hardware.
This PR enable the support of ROCM ep speed up in perf tuning.
This PR also fix a bug when both metrics and model has inference settings by merging them. The metric.inference_settings has higher priority.
=> add tuning op support for ROCM ep

.azure_pipelines/olive-ort-last.yaml
Use variable to specify last ort version to avoid changing the yaml whenever new ort is released.
=> use pipeline variable for last ort version

examples/bert/bert_ptq_cpu.json, olive/engine/engine.py, olive/engine/footprint.py, test/unit_test/engine/test_engine.py, test/unit_test/engine/test_footprint.py
1. Allow pareto_frontier footprint be empty.
2. Adjust the metric goal for bert cpu to mitigate this kind of issue: https://dev.azure.com/aiinfra/PublicPackages/_build/results?buildId=402365&view=logs&j=dbbdd4d8-ffd3-515a-31fd-659375dbdff8&t=13dad60e-7187-5e88-dbc0-776ed0850a3f
=> ⏰ Allow pareto_frontier footprint be empty

.azure_pipelines/job_templates/olive-example-template.yaml, .azure_pipelines/olive-ci.yaml, examples/test/test_qnn_tooklit.py, olive/platform_sdk/qualcomm/configure.py, olive/platform_sdk/qualcomm/create_python_env.ps1, setup.py
1. Enable windows QNN e2e test
2. Added use conda path into windows ci test if it is for qnn. This is a workaround for this kind of issue only ci pipeline: https://community.anaconda.cloud/t/cant-install-failed-to-extract-packages-error/62687
3. Update pwsh Join-path to back-compat the version of pwsh <= 5.x,
=> 🌗 Enable windows QNN e2e test

olive/passes/onnx/transformer_optimization.py, test/unit_test/passes/onnx/test_transformer_optimization.py
If we create InferenceSession by using TRT and TRT not in the available EP, the following error will be raised.
This PR just add working around code. we can consider remove the code later.
=> work around TRT register_tensorrt_plugins_as_custom_ops AttributeError

docs/source/tutorials/configure_data.rst, test/unit_test/model/test_pytorch_model.py, test/unit_test/systems/azureml/test_aml_system.py
The correct parameter name is `task` and not `task_type`.
=> `task` instead of `task_type` in HF container config

examples/bert/npu/README.md, examples/bert/npu/bert_snpe.json, examples/bert/npu/user_script.py, examples/inception/user_script.py, examples/mobilenet/raw_qnn_sdk_template.json, examples/mobilenet/user_script.py, olive/data/component/pre_process_data.py, olive/evaluator/olive_evaluator.py, olive/platform_sdk/qualcomm/snpe/tools/inference.py, olive/platform_sdk/qualcomm/utils/data_loader.py
1. Add Bert SNPE conversion & evaluation case
2. Fix bugs in raw dataloder and snpe evaluator
3. Expose max_length for huggingface pre_process_data
=> 🏂 Bert SNPE conversion & evaluation case

.azure_pipelines/job_templates/olive-example-template.yaml, .azure_pipelines/job_templates/olive-test-template.yaml, .azure_pipelines/olive-ci.yaml, examples/mobilenet/requirements.txt, examples/test/test_snpe_toolkit.py
Inception linux snpe e2e tests
=> 🏂 Inception linux snpe e2e tests

.azure_pipelines/olive-ci.yaml, examples/inception/README.md, examples/inception/prepare_config.py, examples/phi2/requirements.txt, examples/test/test_snpe_toolkit.py, examples/vgg/README.md, examples/vgg/prepare_config.py, olive/platform_sdk/qualcomm/runner.py, olive/platform_sdk/qualcomm/snpe/env.py, olive/platform_sdk/qualcomm/snpe/tools/dev.py, test/unit_test/snpe/test_adb_run.py
To complete the SNPE support in windows. 
Previously Olive only support to run SNPE toolkit in windows. In this PR, I tried to:
1. Test the SNPE toolkit in windows and add the required env variables for SNPE to run. Several differences between run in windows and linux:
- In windows, only the executable file can be find if it's parent folder in system PATH. That need olive to resolve the full file path to run for those snpe-tools which are python file but not .exe.
- In windows, to ensure Python.exe can be initialized successfully, olive need to copy the SYSTEMROOT and other env variables to run the cmd. https://stackoverflow.com/questions/58997105/fatal-python-error-failed-to-get-random-numbers-to-initialize-python
2. Enable windows snpe toolkit e2e tests case with Inception model.
=> 🪟 snpe windows case

docs/source/tutorials/advanced_users.md, olive/common/utils.py, olive/engine/engine.py, olive/hardware/accelerator.py, olive/model/utils/onnx_utils.py, olive/passes/onnx/perf_tuning.py, olive/systems/azureml/aml_system.py, olive/systems/common.py, olive/systems/docker/Dockerfile.cpu, olive/systems/docker/Dockerfile.gpu, olive/systems/docker/Dockerfile.openvino, olive/systems/docker/docker_system.py, olive/systems/system_config.py, olive/systems/utils.py, olive/workflows/run/run.py, test/multiple_ep/test_aml_system.py, test/multiple_ep/test_docker_system.py, test/multiple_ep/test_python_env_system.py, test/unit_test/engine/test_engine.py, test/unit_test/passes/onnx/test_perf_tuning.py, test/unit_test/systems/azureml/test_aml_system.py, test/unit_test/systems/docker/test_docker_system.py, test/unit_test/systems/python_environment/test_python_environment_system.py
* The PR just do code refactoring to facilitate the ep refactor work item to put it into system.
* In this PR, we deliberately delay the OliveSystem creation only when execution. When create accelerator spec, we will use system config to create the accelerator specs
* This PR also fix the multiple EPs evaluation bug when the host is local but target is DockerSystem. If the target is DockerSystem and host is local. the perftuning run pass need to be run in target instead of like other pass. From the time being, I choose a hack way to set the target for perf tuning pass. We need consider more better way to handle the case after this PR.
* For managed AzureMLSystem, we will first query the azureml env. If it doesn't exist, a new one will be created.
* simplify the logic of DockerSystem.
* …
=> Refactor engine to use SystemConfig instead of OliveSystem to create the accelerator specs

examples/llama2/llama2_qlora.json, examples/llama2/llama2_template.json
Latest version of transformers has different attention implementation. Onnx conversion requires `eager` attention implementation to work.
=> [Llama2] Use eager attention implementation

olive/common/utils.py, olive/platform_sdk/qualcomm/runner.py, olive/platform_sdk/qualcomm/snpe/tools/inference.py
1. Remove env from run_subprocess's debug logging to avoid potential l[ogging bug.](https://aiinfra.visualstudio.com/PublicPackages/_build/results?buildId=415082&view=logs&j=04f3f8bd-f6ad-546f-a3e7-a621004c3b55&t=a3ec9bd6-ecbf-5027-baca-9daffad9c3e0) The bug is caused by multitudinous path info which may trigger the UnicodeEncodeError.
2. Ignore the missed diag log files and just throw a error log, as the diag logs are used only for latencies measurement. And sometimes, the SNPEDiag_\d+.log cannot match the value of `runs`. For example:
- if `runs` is 3, the diag log may be `SNPEDiag_0.log, SNPEDiag_3.log, SNPEDiag_4.log`. or  missed one of the log.
=> 🏷️  Simplify run_subprocess log to avoid potential logging bug

olive/evaluator/olive_evaluator.py
- Fix type hint for dataloader from `torch.utils.data.Dataset` to `torch.utils.data.DataLoader`
- Also moved some of the model handler imports to `TYPE_CHECKING` block. 
- Remove the redundant `__init__` redefinitions in the evaluator sub-classes since they are just calling `super().__init__`
=> Fix type hints in `olive_evaluator`

docs/source/api/passes.rst, docs/source/features/passes/onnx.md, docs/source/overview/options.md, examples/llama2/README.md, examples/llama2/llama2_genai.json, olive/passes/onnx/__init__.py, olive/passes/onnx/genai_model_exporter.py
Pass to export a PyTorch model using GenAI exporter
=> Pass to export a PyTorch model using GenAI exporter

.azure_pipelines/olive-ci.yaml
Docker pass run has been moved inside the docker system. So the environment running the engine doesn't have any restrictions on the ort version.
=> Re-enable bert cpu docker test in CI

examples/mobilenet/README.md
Fixes the following errors in the mobilenet README instructions:
- Rename `QNN_EP_ENV` to `QNN_ENV_PATH`
- Rename `--only_config` to `--config_only`
=> Fix mobilenet README

olive/engine/engine.py, olive/model/utils/hf_utils.py
For some models, like microsoft/trocr-base-handwritten, the onnx_config can be got from hf_transformers, but there is not input. 
But it can be converted by OptimumConversion. This PR is used to postpone the error raising even if no hf_io_config is available.
=> ▶️ Postpone the error raising even if no hf_io_config is available

olive/passes/onnx/inc_quantization.py, test/unit_test/passes/inc/test_inc_quantization.py
Inc quantization's calibration dataloader input requires (input, label) which is data_config's data_loader.
This PR is used to fix the bug when user provide data_config bug not dataloader_func.
=> 🍨 Inc quanti dataloader fix

examples/whisper/whisper_template.json, olive/passes/onnx/insert_beam_search.py
ORT 1.17.1 made some changes to the beam search ops. For version 1.17.1, the beam search op used will be `WhisperBeamSearch`. 
Fixes:
#1014
=> Whisper: Support ORT 1.17.1

olive/engine/packaging/packaging_generator.py, olive/platform_sdk/qualcomm/runner.py, olive/systems/isolated_ort/isolated_ort_system.py, olive/systems/python_environment/python_environment_system.py, olive/systems/system_config.py, olive/systems/utils/misc.py, test/unit_test/systems/isolated_ort/test_isolated_ort_system.py, test/unit_test/systems/python_environment/test_python_environment_system.py
* according to the best practice https://docs.python.org/3/library/subprocess.html#popen-constructor, we should use sys.executable instead of python to specify the full path of executable.
* for other program, prefer specify the full path by calling `[shutil.which()](https://docs.python.org/3/library/shutil.html#shutil.which) to expand the full path of the program.
=> use sys.executable instead of python

olive/cache.py, olive/engine/engine.py, olive/engine/packaging/packaging_generator.py, test/unit_test/engine/test_engine.py, test/unit_test/utils.py
The case of run_no_search, if the final model output is composite model, the model_config will be None which leads the error output packing.
```json
{
"input_model":{
"type": "PyTorchModel",
"config": {
"hf_config": {
"model_name": "microsoft/trocr-base-handwritten",
"task": "image-to-text"
}
}
},
"passes": {
"conversion": {
"type": "OptimumConversion"
}
},
"engine": {
"cache_dir": "cache",
"packaging_config": {
"type": "Zipfile", <---- should be removed
"name": "OutputModels" <---- should be removed
},
"output_dir" : "models"
}
}
```
Basically, Olive did not support pack composite model and we should add log to tell user when they encounter similar issues.
This PR is used to fix above issue.
=> 📤 Output model config fix in run_no_search

examples/phi2/generate.py, examples/phi2/phi2.py
1. For phi2 optimization, the transformer optimization keep_io_bytes is False. That means, the input/output of kv should be float16. Update the generation example to fix.
2. optimum conversion does not require ort >=1.18. Update the condition in this PR.
=> 🔑  Update kv cache input type

olive/model/config/hf_config.py, olive/passes/pytorch/lora.py
- Provide `save_embedding_layers=False` to saving the peft model. Otherwise, it defaults to "auto" which checks if the vocab size changed. For models with no pad token, we add a dummy token and increase the embedding size but these are not trained at all. The fine-tuned model can be used without these extra dummy weights and tokens so we don't save them.
- Update the `extra_keys` logic in quant config validation since some attributes were made private and causes incorrect warning log.
=> LoRA: Don't save embedding weights

olive/auto_optimizer/regulate_mixins.py, olive/workflows/run/config.py, olive/workflows/run/run.py, test/unit_test/auto_optimizer/test_auto_optimizer.py
This PR is used for:
1. If there no passes given, enable AutoOpt be default.
2. If the evaluation config is given, in AutoOpt case, we should set disable_search as True.
=> 🅰️ AutoOpt disable search when no evaluator

olive/hardware/accelerator.py, test/unit_test/hardware/test_accelerator.py
* Refactor accelerator normalization logic so that the host system could reuse it when we introduce host device later.
* If user specify EP and device explicitly, the EP will always be override by the available EPs. This PR also fix the bug.
=> refactor accelerator normalization

.azure_pipelines/job_templates/olive-example-template.yaml, .azure_pipelines/job_templates/olive-test-template.yaml, examples/test/utils.py, olive/cache.py, olive/resource_path.py, test/integ_test/utils.py
Our pipeline agents have their own managed identities which take precedence over the AzureCLI task's own credentials. However, these managed identities don't have permissions to run jobs on our workspace. 
Exclude managed identity for credential so that we don't have to use the workaround with environment variables.
=> CI: Exclude managed identity from azureml client credentials

olive/passes/onnx/genai_model_exporter.py
The arguments passed to the model builder tool is not up to date with the released version. It is only on par with a pre-release commit.
#1042
=> GenAIModelExporter: Update arguments to `create_model`

olive/passes/snpe/quantization.py, olive/workflows/run/run.py
1. Make `data_config` optional for SNPE quantization as it can accept `dataloder_func` or `data_config`
2. Update run logs to let it output `package_config, run_config` only if they are str or path. Output the object will let the logs look a bit messy.
=> ☂️ Make `data_config` optional for SNPE quantization

examples/test/utils.py, olive/azureml/azureml_client.py, olive/passes/pytorch/torch_trt_conversion.py
in TorchTRTConversion, use host_device for conversion instead of target device.
The TorchTRTConversion need move the pytorch model to cuda by using https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.to at https://github.com/microsoft/Olive/blob/main/olive/passes/pytorch/torch_trt_conversion.py#L110.
Therefore, we need use host_device instead of target device for conversion
=> use host_device for TorchTRTConversion

.azure_pipelines/job_templates/olive-example-template.yaml, .azure_pipelines/job_templates/olive-test-template.yaml, examples/test/utils.py, test/integ_test/utils.py
The workload federated identity from the service connection is only [valid for 10 minutes](https://learn.microsoft.com/en-us/azure/devops/pipelines/release/troubleshoot-workload-identity?view=azure-devops#error-messages). This is not enough for long running jobs. 
- Instead use user assigned managed identity from the 1es pool agent for authentication.
- Change `AzureCLI` task to `script` since we don't need the az login using the service connection anymore.
=> CI: Use managed identity for Azure authentication

olive/systems/azureml/aml_system.py
When create aml job, the node name need to be lowercase. Otherwise, the following waring will be emitted.
* Changing node name OnnxQuantization to lower case: onnxquantization since upper case is not allowed node name.
=> change node name to lowercase to avoid warning

examples/llama2/README.md, examples/phi2/README.md, examples/phi2/phi2.py, examples/phi2/phi2_genai.json, olive/passes/onnx/genai_model_exporter.py
1. With the latest onnxruntime-genai, there are a few bugs:
a. `precision` can only accept string value(int4, fp16, fp32) but not the 
b. `execution_provider` accept ep value but not device value
c. the pass of `GenAIModelExporter` is not EP agnostic. For cuda int4, the input shape is changed to fp16, but for cpu int4, it is still fp32.
2. Add phi2 example.
- CUDA: v100
- CPU:  Intel(R) Xeon(R) CPU E5-2698
4. Update genai generation example in README of llama2/phi2.
=> 🧞 Fix genai exporter arguments bug and add Genai phi2 example

examples/phi2/phi2_genai.json, olive/passes/onnx/genai_model_exporter.py
Use system's temp dir to set genai exporter cache folder as in windows, the length of cache folder may exceed file path max_length limitation.
https://learn.microsoft.com/en-us/windows/win32/fileio/maximum-file-path-limitation?tabs=registry
=> 🍵 Use system's temp dir to set genai exporter cache folder

.azure_pipelines/olive-ci.yaml, .azure_pipelines/olive-ort-last.yaml, .azure_pipelines/olive-ort-nightly.yaml, examples/mobilenet/mobilenet_qnn_ep.py, examples/mobilenet/mobilenet_qnn_ep_template.json, examples/test/test_mobilenet_qnn_ep.py, olive/hardware/accelerator.py, olive/workflows/run/run.py
- Added doc and comment for `skip_supported_eps_check`.
- The value provided to `skip_supported_eps_check` is updated so that we also check that there are no passes that need to run on target.
- Mobilenet QNN EP example is fixed so that it only runs for qnn ep. #998 had made the example incorrect when running with no evaluation. Since no target was provided, it would run for all installed eps but it is only supposed to run for qnn ep.
- Added test for the example with no evaluation. Evaluation requires ARM64 Windows which we don't have in our agent pools.
=> Update `skip_supported_eps_check`, Fix Mobilenet QNN EP example

olive/passes/onnx/extract_adapters.py, olive/scripts/export_adapters.py, test/unit_test/passes/onnx/test_extract_adapters.py
- `ExtractAdapters` pass supports int4 quantized models. 
- Previously output models were always saved with external data. External data config options are exposed to the user.
- `export_adapters` script also supports quantizing the weights to int4.
=> ExtractAdapters: Support int4 models and external data config

.github/workflows/codeql.yml, examples/directml/llama_v2/llama_v2.py, examples/gptj/user_script.py, examples/inception/download_files.py, examples/mobilenet/download_files.py, examples/open_llama/user_script.py, examples/resnet/prepare_model_data.py, examples/stable_diffusion/stable_diffusion.py, examples/whisper/test_transcription.py, olive/passes/onnx/vitis_ai/refine.py, olive/passes/pytorch/lora.py, olive/platform_sdk/qualcomm/configure.py, olive/platform_sdk/qualcomm/snpe/tools/inference.py, test/unit_test/systems/isolated_ort/test_isolated_ort_system.py
Fix partial issues from code ql scanning
=> 🇶🇦 Fix Errors from code ql scanning

olive/platform_sdk/qualcomm/utils/data_loader.py
The subclasses override `load_data` method which generates the following warning 
Fixed by the loading the data beforehand and passing the required data parameters to super init.
=> CodeQL: Fix `FileListDataLoader`

olive/model/handler/mixin/hf_config.py, olive/model/utils/hf_utils.py, olive/passes/onnx/conversion.py
For generative models using GenAI model builder, when using ONNX model as input configs (config.json, generation_config.json & tokenizer) are required inputs. So, write out these files as outputs from the conversion pass.
=> Write configs as part of conversion pass

olive/passes/pytorch/gptq_utils.py
fix unused bug in gptq_utils, this bug only exists when GEMM weights need padding which is not common.
=> Fix unused bug in gptq_utils

docs/source/features/packaging_output_models.md, examples/llama2/README.md, examples/llama2/llama2_genai.py, examples/llama2/llama2_genai_template.json, olive/cache.py, olive/engine/packaging/packaging_config.py, olive/engine/packaging/packaging_generator.py, olive/model/handler/mixin/hf_config.py, olive/passes/olive_pass.py, olive/passes/onnx/genai_model_exporter.py, test/unit_test/passes/test_pass.py
* Added support for packaging models (and additional files) generated by the GenAIModelExporter. Also, updated the pass configuration to include search parameters that are forwarded to the generated genai_config file.
* Added support for carrying "additional files" from one pass to next. These files will end up in the generated models output folder and will be packaged.
* Two new packaging configuration options -
* include_sample_code
* inlcude_runtime_packages
Packaging config include two new options -
* include_sample_code - whether or not to include sample code in zip archive. Defaults to true.
* include_runtime_packages - whether or not to include runtime packages (like onnxruntime) in zip archive. Defaults to true.
=> onnxruntime-genai based metadata and packaging

docs/source/tutorials/configure_systems.rst
There were a couple of typos in the "how to configure systems" doc where `system` was used in the JSON rather than `systems`.
=> fix typos in configure_systems.rst

olive/model/config/hf_config.py, olive/model/handler/mixin/hf_config.py
When creating a tokenizer using `AutoTokenizer.from_pretrained`, it saves the kwargs and tries to serialize them during `save_pretrained`. The model loading args contains kwargs that are not related to tokenizer and cannot be serialized like torch.dtype and BitsAndBytesConfig. 
Don't pass any kwargs when getting tokenizer. If needed, we can filter the keys in the future.
=> HFConfig: don't pass kwargs to get tokenizer

examples/open_llama/llama_qlora.json, examples/open_llama/open_llama_loftq_tinycodes.json, examples/open_llama/open_llama_lora_tinycodes.json, examples/open_llama/open_llama_qlora_ort_tinycodes.json, examples/open_llama/open_llama_qlora_tinycodes.json, examples/phi/phi_qlora_tinycodes.json, olive/hardware/accelerator.py, olive/systems/docker/utils.py, olive/systems/utils/misc.py, olive/workflows/run/run.py, test/unit_test/hardware/test_accelerator.py, test/unit_test/workflows/test_run_config.py, test/unit_test/workflows/test_workfow_run.py
* Originally, the execution_providers in accelerator spec is required regardless whether it is used or not. Even if user doesn't specify them, the local system will infer and get the available EPs to autofill the EPs. This is painful for passes that doesn't use the EP. 
* In this PR, if there is no pass that belongs to onnx techniques, we will not infer the EP based on the device. 
* On the other hand, if the device is not specified, we will choose cpu by default.
=> Make the accelerator EP optional for non-onnx pass

examples/directml/llm/chat_templates.py, examples/directml/llm/llm.py, examples/directml/llm/model_type_mapping.py, examples/directml/llm/phi3.py, examples/directml/llm/run_llm_io_binding.py, examples/directml/llm/user_script.py
=> Add DirectML LLM sample

olive/passes/onnx/model_builder.py
Adding the following new options for model builder pass
+ int4_block_size
+ int4_accuracy_level
+ exclude_embeds
+ exclude_lm_head
+ enable_cuda_graph
=> Additional ModelBuilder pass options

docs/source/features/huggingface_model_optimization.md, docs/source/tutorials/configure_data.rst, examples/bert/npu/bert_snpe.json, examples/inception/inception_config.json, examples/llama2/llama2_qlora.json, examples/llama2/llama2_template.json, examples/llama2/notebook/llama2/config.json, examples/open_llama/llama_qlora.json, examples/open_llama/open_llama_loftq_tinycodes.json, examples/open_llama/open_llama_lora_tinycodes.json, examples/open_llama/open_llama_qlora_ort_tinycodes.json, examples/open_llama/open_llama_qlora_tinycodes.json, examples/open_llama/open_llama_sparsegpt_gpu.json, examples/phi/phi_qlora_tinycodes.json, examples/phi2/phi2_optimize_template.json, examples/vgg/vgg_config.json, olive/auto_optimizer/__init__.py, olive/data/config.py, olive/workflows/run/config.py, test/unit_test/data_container/test_config.py, test/unit_test/data_container/test_data_container.py, test/unit_test/passes/inc/test_inc_quantization.py, test/unit_test/passes/openvino/test_openvino_quantization.py, test/unit_test/test_data_root.py, test/unit_test/utils.py, test/unit_test/workflows/test_run_config.py
Dataset configuration i.e. data_configs are represeneted as objects in config and so have two name entries -
- the key of the object itself
- DataConfig::name field
Use cases around the code use either/or and expect both these names to be identifical with no enforcement during validation. Removing the duplication by making the data_configs a list of objects so the key isn't required anymore. Updated the code to use DataConfig::name for all look-ups.
Note: Pending document update.
=> Remove name ambiguity in dataset configuration

olive/hardware/accelerator.py, olive/model/handler/mixin/dummy_inputs.py, olive/model/handler/pytorch.py, olive/model/utils/hf_utils.py, olive/systems/azureml/aml_pass_runner.py, olive/systems/azureml/aml_system.py, test/unit_test/systems/azureml/test_aml_system.py
This fixes some bugs introduced by some recent PRs:
- #1091
- made `model.io_config` a property which calls `get_hf_model_io_config` if the conditions meet. 
- However, this function fails if the model is not supported. Now it doesn't fail and logs when unsupported.
- `PytorchModelHandler.to_json` uses `_io_config` for `"io_config"` so that the serialized model is the same as the one that was initialized. 
- #1072
- execution_provider is optional for non-onnx pass but `to_json` still has the key. Which doesn't match the signature for https://github.com/microsoft/Olive/blob/91c4c20e324fbc47dcbbea20bf89035ec94fa4a6/olive/passes/olive_pass.py#L459
- Only add when not None
- Also removed `pass_accelerator_type` and `pass_execution_provider` from the aml_pass_runner command line inputs. These …
=> Bug fix: Don't fail `get_hf_model_io_config`, Optional Accelerator execution_provider

olive/passes/pytorch/lora.py
There is a bug in accelerate where it assumes that bnb (loaded_in_4bit) models on multiple gpus cannot be trained but this is not the case. On AML computes with multiple GPUs, the model doesn't have any weights on device 0 which is the default device for accelerator and catches the bug https://github.com/huggingface/accelerate/blob/e82de1215ae701b6bf567eb705615c656e7f55c7/src/accelerate/accelerator.py#L1374. This has been fixed on main by https://github.com/huggingface/accelerate/pull/2714 but is not in a release yet. 
We workaround this bug for current stable releases of accelerate by setting `ACCELERATE_TORCH_DEVICE` to the same device as the first device the model is on. 
`
=> LoRA/QLoRA: Workaround accelerate bug for multi-gpu bnb model

olive/passes/onnx/model_builder.py
GenAI model builder's extra_args works based on existence of a key rather then the value of the key itself. So, Olive cannot pass a key with a value of true/false. The key has to explicitly be added/removed based on the value of the key itself in the user config.
=> Fix handling of extra_args for ModelBuilder pass

olive/passes/onnx/vitis_ai/quant_utils.py, test/unit_test/passes/vitis_ai/test_vitis_ai_quantization.py
* Disable Vitis technique for ORT 1.18 and above since of the API signature is changed. Please re-enable the CI when Amd fix the issue
=> disable Vitis in ORT 1.18

.github/workflows/lint.yml
Update actions/setup-python@v5 to use node20
> Warning: Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/setup-python@v4. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/
advanced-security/dismiss-alerts is not updated recently to fix nodejs 20 issue. We just keep it and wait for community to fix.
> Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: advanced-security/dismiss-alerts@v1. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
=> 📦 Update actions/setup-python@v5 to use node20

olive/passes/onnx/extract_adapters.py, olive/scripts/export_adapters.py
Fixes https://github.com/microsoft/Olive/security/code-scanning/10748 and https://github.com/microsoft/Olive/security/code-scanning/10747.
=> CodeQL: use `str.isdigit` instead of `try/except`

olive/cache.py, olive/common/utils.py, olive/engine/engine.py, olive/passes/onnx/quantization.py, olive/passes/onnx/vitis_ai_quantization.py, test/unit_test/engine/test_engine.py
* fix https://github.com/microsoft/Olive/security/code-scanning/10844
=> fix codeql md5 error

docs/source/features/packaging_output_models.md, docs/source/features/passes/onnx.md, docs/source/features/passes/pytorch.md, docs/source/features/passes/qnn.md, olive/data/component/dataset.py, olive/passes/pytorch/lora.py
1. Use resolve_torch_dtype instead of maintain a mapping to torch dtype instance
2. Fix a few typos in docs.
=> 🗡️ Use resolve_torch_dtype instead of maintain a mapping to torch dtype instance

test/unit_test/common/test_retry.py
* Fix https://github.com/microsoft/Olive/security/code-scanning/10629
=> Codeql: fix global variable warning

olive/passes/onnx/model_builder.py
=> Add support for DML execution provider

docs/source/features/passes/onnx.md, olive/olive_config.json, olive/passes/onnx/conversion.py, olive/passes/onnx/float16_conversion.py, olive/passes/onnx/transformer_optimization.py, test/unit_test/passes/onnx/test_float16_conversion.py
- `onnxconverter-common`'s float16 converter tool is not regularly maintained and it also cannot large models (>2GB). Use the float16 converted from onnxruntime which is a modified version of the previous tool and has more features.
- Added unit test for pass.
=> `OnnxFloatToFloat16`: Use ort float16 converter

examples/directml/llm/config.py, examples/directml/llm/config_llm.json, examples/directml/llm/decoder_model.py, examples/directml/llm/llm.py, examples/directml/llm/model_type_mapping.py, examples/directml/llm/user_script.py
=> Add Gemma to DML LLM sample

olive/passes/onnx/model_builder.py
model_build `search` config might be None
=> 🐛 bugfix: model_builder `search` config might be None

examples/bert/README.md, examples/bert/bert_nvmo_ptq.json, examples/bert/nv_user_script.py, olive/auto_optimizer/config_template/pass_capability.yaml, olive/olive_config.json, olive/passes/onnx/nvmo_quantization.py, test/requirements-test.txt, test/unit_test/passes/onnx/test_nvmo_quantization.py
- Unit test: `pytest test/unit_test/passes/onnx/test_nvmo_quantization.py`
- Example: `python -m olive.workflows.run --config bert_nvmo_ptq.json`
=> NV-ModelOPT INT4 quantization

examples/phi2/phi2.py, examples/phi2/phi2_optimize_template.json, olive/passes/pytorch/slicegpt.py, test/unit_test/passes/pytorch/test_slicegpt.py
Implementation of SliceGPT supported only a handful of specific datasets. Widen the support for any generic dataset via the data_config configuration.
=> Add support for generic data sets to SliceGPT pass

olive/passes/onnx/model_builder.py
This option doesn't exist anymore. GQA is enabled by default for CPU.
=> ModelBuilder: remove `enable_GQA_on_CPU` option

olive/model/utils/hf_utils.py, test/unit_test/model/test_hf_utils.py
`load_hf_model_from_task` catches `OSError,ValueError` to allow iterating over potentially multiple candidate classes. However, for most cases, there is only one model class to try and there are valid errors like device OOM, unsupported kwargs, that need to be rethrown. 
Currently, the model loading silently fails and the caller gets `None` as the model. This is unexpected behavior and makes it hard to debug without error logs or failure with traceback.
 
=> Fix exception handling in `load_hf_model_from_task`

olive/model/handler/mixin/__init__.py, olive/model/handler/mixin/hf_config.py, olive/model/handler/mixin/mlflow.py, olive/model/handler/pytorch.py, olive/passes/onnx/model_builder.py, olive/resource_path.py, test/unit_test/model/test_pytorch_model.py
For transformers model like phi2/phi3 in aml model cataklog, it is hosted with mlflow model format. 
But Genai require the input model format is standard transformers structure.
This pr is used to fill this gap to let model builder can convert aml mlflow-transformers models.
=> [azureml model catalog]MLflow-transformer model path 

examples/directml/llm/llm.py
fix `config.head_dim` to `int` type. The changes in #1138 made the head_dim param to type `float`.
=> fix dtype of config.head_dim to int for directml llm example

olive/common/utils.py, olive/systems/azureml/aml_system.py
Recently we started getting aml test failures due to `JobException` with `message: Service invocation timed out.`. This failure appears to be random so just catch it in the `retry_func`.
=> AzureMLSystem: catch `JobException` and retry job creation

examples/test/test_qnn_tooklit.py, examples/test/test_snpe_toolkit.py
inception_snpe_toolkit started randomly failing due to mismatched sha between downloaded wheel and expected wheel. Looking at the failure logs, it appears to be due to incomplete download of the wheels. 
- retry the configure sdk command
- set log verbosity to debug so that we get logs for the test setup too
=> Qualcomm SDK tests: retry configure sdk

olive/platform_sdk/qualcomm/create_python_env.ps1
Conda and python commands in the `.ps1` do not exit when they fail even though `$ErrorActionPreference = "Stop"`. This leads the script to succeed even though there might have been issues during the conda environment creation or pip installs. 
Added a function to check the status of last command and exit if it failed.
=> Check last command status in Qualcomm SDK configure PowerShell script

docs/architecture.md, docs/source/tutorials/configure_data.rst, olive/data/config.py, test/unit_test/passes/openvino/test_openvino_quantization.py, test/unit_test/test_data_root.py, test/unit_test/utils.py
Removed the unused field and related references across the codebase. Also, updated the relevant documentation.
=> Deprecate unused field DataComponentConfig::name

test/unit_test/passes/onnx/test_extract_adapters.py
The CI test on Windows fails occasionally during import of `peft`. The test is disabled temporarily to unblock other PRs while I find a solution for it.
=> Skip `test_extract_adapters` on windows temporarily

olive/passes/onnx/quantization.py, test/unit_test/passes/onnx/test_quantization.py
Support ORT 1.18 QNN Preprocess by adding configs:
- init_overrides
- add_qtype_converts
- activation_symmetric
- weight_symmetric
=> 🎃 Support ORT 1.18 QNN Preprocess

test/requirements-test.txt, test/unit_test/passes/onnx/test_extract_adapters.py
- The CI test on Windows fails occasionally during import of peft. At https://github.com/huggingface/peft/blob/e7b75070c72a88f0f7926cc6872858a2c5f0090d/src/peft/tuners/boft/layer.py#L30, the error is `OSError: [WinError 122] The data area passed to a system call is too small`. This code was added in https://github.com/huggingface/peft/commit/811169939ff466199cdd48767a10ca48497e03f7 which is part of peft version 0.11.0+.
- Revert #1180 since more tests are affected by the same issue. Will just pin peft version to the previous stable version 0.10.0 until the issue is fully investigated and resolved.
=> UT: Pin `peft` to `0.10.0`

docs/source/overview/options.md, olive/common/constants.py, olive/engine/engine.py, olive/workflows/run/config.py, olive/workflows/run/run.py
Workflow id feature is a prerequisite for running workflow on a remote vm feature.
By adding this feature:
- Cache dir will become `<cache_dir>/<workflow_id>`
- OLive config will be automatically saved to cache dir.
- User can specify `workflow_id` in config file.
- The default workflow_id is `default_workflow`.
=> Add workflow id to Olive

.azure_pipelines/job_templates/olive-build-doc-template.yaml, docs/Makefile, docs/make.bat, docs/source/conf.py, docs/source/dump_schema.py, docs/source/overview/options.md, olive/azureml/azureml_client.py, olive/model/config/model_config.py, olive/passes/__init__.py, olive/passes/olive_pass.py, olive/workflows/run/config.py, pyproject.toml
- Add olive workflow schema to doc website. This schema file can be used in IDEs when writing workflow configs.
- Config objects related to workflow are updated to use `Field` with descriptions. 
Schema for olive workflow config json can be found at https://microsoft.github.io/Olive/schema.json.
=> Add workflow schema to doc website

.azure_pipelines/job_templates/olive-build-doc-template.yaml, .azure_pipelines/job_templates/olive-example-template.yaml, .azure_pipelines/job_templates/olive-performance-template.yaml, .azure_pipelines/job_templates/olive-test-template.yaml, examples/bert/docker/Dockerfile, olive/olive_config.json, olive/systems/docker/Dockerfile.openvino, olive/systems/python_environment/common_requirements.txt, olive/workflows/run/config.py, requirements.txt, test/unit_test/passes/pytorch/test_lora.py, test/unit_test/passes/pytorch/test_slicegpt.py, test/unit_test/passes/pytorch/test_sparsegpt.py, test/unit_test/passes/pytorch/test_torch_trt_conversion.py, test/unit_test/workflows/mock_data/text_generation_dataset.json, test/unit_test/workflows/mock_data/text_generation_dataset_random.json, test/unit_test/workflows/test_run_config.py
- Same changes in https://github.com/microsoft/Olive/pull/1199: `load_dataset` also requires `trust_remote_code` now
- Set `PIP_CACHE_DIR` and `HF_HOME` to use the workspace directory in ci pipelines. This directory has enough space where as the default cache directories are under `/` which doesn't have much space for the `OLIVE_POOL_UBUNTU2004` pools. This leads to out of disk sometimes. From test runs, the pip cache takes 3G+. The hf cache depends on the models and datasets being tested.
=> `trust_remote_code` for `load_dataset` config, CI: set pip and hf cache dirs

docs/source/overview/options.md, examples/llama2/llama2_multilora.ipynb, examples/llama2/llama2_qlora.json, examples/llama2/user_script.py, examples/phi2/phi2_optimize_template.json, olive/data/component/pre_process_data.py, olive/model/config/kv_cache_config.py, olive/workflows/run/run.py, test/unit_test/model/test_kv_cache_config.py, test/unit_test/model/test_pytorch_model.py
- The default input-output names are changed to `past_key_values.<id>.key/value` and `present.<id>.key/value` since this is the most commonly used template (by both genai and optimum)
- Ignore `onnxruntime-genai` package when checking for `onnxruntime` dependency
- `llama2_multilora` notebook now has example generation for different lora adapters using genai.
=> Llama2: Multi-lora generate using genai, Update default kv cache io names

examples/bert/user_script.py, examples/directml/squeezenet/user_script.py, examples/directml/stable_diffusion_xl/user_script.py, examples/mistral/user_script.py, examples/resnet/user_script.py, examples/stable_diffusion/user_script.py, test/unit_test/passes/inc/test_inc_quantization.py, test/unit_test/passes/openvino/test_openvino_quantization.py, test/unit_test/test_data_root.py, test/unit_test/utils.py
Renamed batchsize to batch_size
Renamed datadir to data_dir
With transition to use more of DataConfig and keyword args, parameter naming consistency becomes important.
=> Few renames to prevent user errors

docs/source/tutorials/configure_data.rst, examples/llama2/notebook/llama2/user_script.py, examples/llama2/notebook/llama2_multiep/user_script.py, examples/llama2/user_script.py, examples/open_llama/lora_user_script.py, examples/phi/user_script.py, examples/phi2/user_script.py, examples/phi3/user_script.py, olive/data/component/pre_process_data.py, olive/data/container/huggingface_container.py
#1199 enabled `trust_remote_code` for huggingface container in `load_dataset` and `pre_process` components. That will pass  `trust_remote_code` to the  function into `load_dataset_config` if `trust_remote_code` is in `hf_config.from_pretrained_args`.
But last PR did not update the customized user_script.py.
=> 🐛 Fix arguments error for trust_remote_code in customized data component

examples/test/test_qnn_tooklit.py, examples/test/test_snpe_toolkit.py, examples/test/utils.py, olive/platform_sdk/qualcomm/create_python_env.ps1, olive/platform_sdk/qualcomm/create_python_env.sh
The environment setup scripts currently download the conda installer each time. We are seeing rate limits for the downloads recently.
Now, the user can set `CONDA_INSTALLER` environment variables to use a local copy of the installer.
=> Allow local conda installer for QC sdk configure

docs/source/tutorials/configure_data.rst, olive/data/component/dataloader.py, olive/data/component/dataset.py, olive/data/component/load_dataset.py, olive/data/container/dummy_data_container.py, olive/evaluator/olive_evaluator.py, olive/passes/pytorch/qat_utils.py, test/integ_test/utils.py, test/unit_test/data_container/test_dataset.py, test/unit_test/data_container/test_template.py, test/unit_test/evaluator/test_olive_evaluator.py, test/unit_test/passes/onnx/test_perf_tuning.py, test/unit_test/passes/pytorch/test_quantization_aware_training.py, test/unit_test/systems/isolated_ort/test_isolated_ort_system.py, test/unit_test/test_data_root.py, test/unit_test/utils.py, test/unit_test/workflows/test_workflow_run.py
* Deprecate skip_dataloader because it ignores forced treating Dataset as Dataloader and we have no more use case for it.
* Updated DummyDataset
* to generate random data instead of constant ones 
* to accept a seed for randomness and a size
* to avoid generating the data until explicitly requested
* Removed clones, yet slightly different, implementations of DummyDataset. Used primarily to tests.
* Renamed global create_dataloader to create_dummy_dataloader to be explicit. Used only in tests.
=> Use DummyDataLoader instead of declaring new types for tests

olive/data/registry.py, olive/systems/docker/docker_system.py, test/unit_test/passes/onnx/test_transformer_optimization.py, test/unit_test/test_data_root.py
Duplicate registration causes undesirable results and hard to debug errors.
=> Report duplicate DataComponentType registration as fatal

.azure_pipelines/olive-ci.yaml, docs/source/tutorials/configure_systems.rst, examples/bert/bert_cuda_gpu.json, examples/bert/conda.yaml, examples/bert/conda_gpu.yaml, examples/test/test_bert_cuda_gpu_aml.py, examples/test/utils.py
- Separate the bert cuda example test into local and aml tests
- AML test:
- doesn't require to be run on a GPU pipeline agent. 
- Reduced the cases since we only want to test CUDA EP on aml. No need to test the pass_flows or search strategies. Saves test time since the aml gpu cluster is small and has longer queue times.
- Updated base image with cuda 11.8. Both torch and ort don't support 11.6 anymore
- Updated the conda yamls
=> CI: Separate Bert CUDA local and aml test

examples/test/test_resnet_ptq_cpu.py, examples/test/utils.py, olive/common/config_utils.py, olive/common/utils.py, olive/resource_path.py, olive/systems/azureml/aml_evaluation_runner.py, olive/systems/azureml/aml_pass_runner.py, olive/systems/azureml/aml_system.py, olive/systems/utils/__init__.py, olive/systems/utils/arg_parser.py, test/integ_test/utils.py, test/unit_test/resource_path/test_resource_path.py, test/unit_test/systems/azureml/test_aml_system.py, test/unit_test/utils.py
- Implemented a `resource_path` utils called `find_all_resources` which traverses a config dictionary and returns all resources (local files/folders, aml resources)
- Instead of hard coding expected resource params or inferring them from `ParamCategory`, the AMLSystem now uses automatically finds the resources and mounts them. It also keeps tracks of the dict keys to update them in the runners.
- Removed the ort version check in aml pass runner since 1.16 is too old so we don't need to officially support it.
In follow up PRs:
- the DockerSystem will also be updated to use the same logic. 
- Migrate the `_prepare_non_local_model` logic from engine into the DockerSystem and LocalSystem so that the engine is agnostic to resources completely.
=> AzureMLSystem: Generalize resource mount

olive/systems/azureml/aml_evaluation_runner.py, olive/systems/azureml/aml_pass_runner.py, olive/systems/azureml/aml_system.py, olive/systems/utils/arg_parser.py, test/unit_test/systems/azureml/test_aml_system.py
- When the same AzureML model resource is provided as input to a command multiple times, it leads to an invalid job (interestingly, this is not the case for a local resource).
- AzureML system is updated so that a particular resource is provided as input only once. The resources are now referenced using names of format `resource__{i}`. AML runners use the `num_resources` and resource maps to reconstruct the configs.
=> AzureMLSystem: Unique input resources

.azure_pipelines/build-doc.yaml, .azure_pipelines/job_templates/olive-example-template.yaml, .azure_pipelines/job_templates/olive-performance-template.yaml, .azure_pipelines/job_templates/olive-test-template.yaml, .azure_pipelines/olive-ci.yaml, .azure_pipelines/olive-ort-last.yaml, .azure_pipelines/olive-ort-nightly.yaml, .azure_pipelines/package_publish.yaml, .azure_pipelines/performance.yaml
- Remove component governance step from the test pipelines. We don't publish anything in these pipelines, so it is not necessary. This task is flaky sometimes and fails due to out of disk error. There is no option to set a different directory to fix this.
- Added the step to the `package_publish` pipeline which is used to generate the wheel for pypi release. Ignore the docs and examples directories since those are not part of the package.
- Added the pipeline specific variables in the pipeline yamls instead of the job templates for easier maintenance.
 
=> CI: Only run component governance in package publish pipeline

.azure_pipelines/job_templates/olive-build-doc-template.yaml, .azure_pipelines/job_templates/olive-build-template.yaml, .azure_pipelines/job_templates/olive-example-template.yaml, .azure_pipelines/job_templates/olive-setup-template.yaml, .azure_pipelines/job_templates/olive-test-template.yaml, .azure_pipelines/olive-ci.yaml, .azure_pipelines/olive-ort-last.yaml, .azure_pipelines/olive-ort-nightly.yaml, examples/directml/stable_diffusion_xl/requirements-common.txt, examples/stable_diffusion/requirements-common.txt
CI:
- Based on the cuda setup on the test machine, there might be incompatibilities between the cuda related dependencies between torch and ort-gpu. Allow CI jobs to specify the version of torch they want to run with.
- torch, olive and ort installation steps abstracted into a template.
SD:
- `transformers>=4.43.0` added sdpa and flash attention support to clip models which can be disabled by providing `"attn_implementation" : false` as load kwargs. However, `diffusers` hasn't been updated yet to use this option yet. 
- Pin the version until the issue is resolved.
- Issue tracking this: https://github.com/huggingface/diffusers/issues/8957
=> CI: Configurable `torch` version, SD: Pin `transformers` version

olive/systems/azureml/aml_system.py
For some of configs, the sort of keys matters. Since now we add olive configs here, no need to sort the passes.
=> Remove sort for aml config map

docs/source/features/huggingface_model_optimization.md, examples/falcon/config.json, examples/llama2/notebook/llama2_multiep/config_multi_ep.json, examples/open_llama/llama_qlora.json, olive/data/component/pre_process_data.py, olive/data/component/text_generation.py, test/unit_test/passes/pytorch/test_lora.py, test/unit_test/passes/pytorch/test_slicegpt.py, test/unit_test/passes/pytorch/test_sparsegpt.py, test/unit_test/passes/pytorch/test_torch_trt_conversion.py
- The `pair` dataset type was originally added to replicate the original qlora implementation's dataprocessing options. However, it is not used and is has limited use case. Drop support for this dataset type and only keep the common `corpus` type.
- Since pair is not a concept anymore, `source_max_len` is renamed to `max_seq_len` to align the parameter name to how it's commonly known as (such as in hf trl, etc).
`pair` dataset type has been removed. `source_max_len` renamed to `max_seq_len`.
=> Text-gen: Remove `pair` dataset_type, `source_max_len` -> `max_seq_len`

docs/source/exts/auto_config_doc/__init__.py, olive/common/config_utils.py, olive/data/config.py, olive/data/registry.py, olive/engine/packaging/packaging_config.py, olive/model/config/model_config.py, olive/model/config/registry.py, olive/package_config.py, olive/passes/olive_pass.py, olive/resource_path.py, olive/systems/common.py, olive/workflows/run/run.py, test/unit_test/systems/azureml/test_aml_system.py, test/unit_test/test_package_config.py
Make the `type` fields in configs case insensitive.
- `str` types are all stored in lowercase and indexed using the same.
- `str,Enum` types inherit `CaseInsensitiveEnum` which can accept any case value.
=> Make config types case insensitive

.pre-commit-config.yaml
=> 🫥 [Linter fix] Remove absolute-imports since it is superseded by ruff TID252

docs/source/_static/css/header.css, docs/source/conf.py
Use custom cuss for header tags for between contrast between levels. Especially between h3 and h4 which are used in the cli command auto docs.
=> Docs: Custom CSS for header tags

examples/utils/generator.py, olive/auto_optimizer/__init__.py, olive/common/config_utils.py, olive/common/constants.py, olive/common/utils.py, olive/constants.py, olive/data/component/text_generation.py, olive/data/constants.py, olive/engine/packaging/packaging_config.py, olive/evaluator/metric.py, olive/hardware/accelerator.py, olive/passes/onnx/model_builder.py, olive/passes/onnx/nvmo_quantization.py, olive/passes/onnx/onnx_dag.py, olive/passes/onnx/vitis_ai/quant_utils.py, olive/passes/openvino/quantization.py, olive/passes/pass_config.py, olive/passes/pytorch/autoawq.py, olive/passes/pytorch/quarot.py, olive/platform_sdk/qualcomm/constants.py, olive/strategy/search_parameter.py
https://github.com/python/cpython/issues/100458
Quarot require python>=3.11 where the mixin usage of (str, Enum) did not work. This PR is used to create olive strEnum based on python version.
=> 📽️  Olive StrEnumBase IntEnumBase

olive/cli/finetune.py, olive/package_config.py, olive/workflows/run/run.py, test/unit_test/cli/test_cli.py
Add remote config support to `finetune` cli. 
- cloud cache is not supported yet since it only works for huggingface-id models. It does not work for locally saved models or azureml registry models (which to the aml workflow host appears as local model). Will be added later
 
**Example usage:**
```bash
olive finetune -m azureml-meta:Llama-2-7b:22 --method qlora \
-d json --data_files data/phrase_classification_dataset.json \
--text_template "<|user|>\n{phrase}<|end|>\n<|assistant|>\n{tone}<|end|>" \
--train_split "train[:70%]" --eval_split "train[70%:]" \
--per_device_train_batch_size 4 --per_device_eval_batch_size 4 \
--max_steps 200 --logging_steps 50 \
--learning_rate 0.0001 \
--azureml_config aml-workspace.json --azureml_cluster gpu-cluster
```
=> Finetune: Add remote workflow support

examples/whisper/requirements.txt, examples/whisper/test_transcription.py
`transformers>=4.33.0` produces an invalid model that outputs empty strings. The exported model doesn't appear to be compatible with the workflow anymore. 
Fixed the whisper example test to catch empty strings.
Fixes #1291
=> Whisper: pin `transformers` version

olive/systems/azureml/aml_system.py
priority works across metrics, however, aml evaluation works only a single metric at a time. So, metric validation was failing.
=> Handle metric priority correctly so validation can pass

examples/mistral/mistral_int4_optimize.json, olive/passes/onnx/inc_quantization.py
`diagnosis` option is no longer supported by `neural-compressor>=3.0`. It was not being used before either so there is no regression. It only prints the quantization summary using neural-insights (which has been deprecated from inc) so should not affect the quantized model.
=> INC: Remove `diagnosis` config param

olive/common/hf/utils.py, olive/data/component/text_generation.py, olive/passes/pytorch/lora.py
- Remove `smart_tokenizer_and_embedding_resize` which was used to add a pad_token if not present. This was copied from the original qlora implementation, but it is unnecessary and not efficient. Most training scripts use the eos_token as pad_token. This is fine as long as the attention mask and labels are correctly masked.
=> LoRA: Remove `smart_tokenizer_and_embedding_resize`, Use `eos_token` as `pad_token`

olive/auto_optimizer/template_mapping.py, olive/auto_optimizer/workflow_template/ort_perf_tuning.yaml, olive/cli/launcher.py, olive/cli/perf_tuning.py, setup.py, test/unit_test/cli/test_cli.py
Perf tuning cli.
E.g. for phi2-int4-cpu got from model builder, user can directly tuning the session parameters in cpu and cuda ep with:
`olive tune-session-params --model model.onnx --device gpu --providers_list CUDA CPU --hf_model_name microsoft/phi-2`
Also, user can provide their customized data_config:
`olive tune-session-params --model  model.onnx --device gpu --providers_list CUDA CPU  --data_config_path data_config.json`
where the data config json looks like
```json
{
"name": "gpu_cpu",
"type": "TransformersTokenDummyDataContainer",
"load_dataset_config": {
"model_name": "microsoft/phi-2"
}
}
```
=> 🧗 perf tuning cli

.azure_pipelines/olive-ci.yaml, examples/AST/ast.json, examples/bert/bert_ptq_cpu_aml.json, examples/resnet/resnet_multiple_ep.json, examples/resnet/resnet_ptq_cpu.json, examples/resnet/resnet_ptq_cpu_aml_dataset.json, test/unit_test/passes/onnx/test_quantization.py, test/unit_test/snpe/test_adb_run.py, test/unit_test/systems/docker/test_docker_system.py, test/unit_test/workflows/test_run_config.py, test/unit_test/workflows/test_setup.py
- After ort 1.19.0, the histogram collector in onnxruntime static quantization calibration hits errors with Nan ("ValueError: supplied range of [nan, nan] is not finite"). There is no ETA for an investigation or fix for this issue so we will only test static quantization with MinMax calibration method.
- Remove config params for no-search configs that are set to defaults
- Use latest torch in cuda examples test since ort-gpu 1.19.0 is compatible with it now. (needs cudnn 9.x)
Some lint fixes for new ruff version.
=> CI: Make compatible with `ort>=1.19.0`

olive/cli/export_adapters.py, olive/common/hf/model_io.py, olive/common/hf/peft.py, olive/common/hf/utils.py, olive/passes/onnx/conversion.py, olive/passes/onnx/extract_adapters.py
LoRA has a scaling factor that is computed based on `lora_alpha` and `r`. These get multiplied with the output of the lora matmuls which results in an additional `Mul` node with the scaling float. However, this mul node is hard to keep track of during subsequent optimization steps (for example, it might get removed if scaling is 1). We also want to be able to use different sets of adapters which might not share the same scaling factor. 
To overcome this, we implement a context manager which finds all lora linear layers and wraps it with a custom module class that already has the scaling multiplied into the lora_B weights. This way, we can just ship the scaled weights.
Also moved other peft related model transformations into the context manager.
=> Conversion: Absorb lora scaling into lora_B weights

olive/model/handler/onnx.py, olive/passes/olive_pass.py, olive/passes/onnx/conversion.py, olive/passes/onnx/extract_adapters.py, olive/passes/onnx/onnx_dag.py, test/unit_test/passes/test_pass.py
ONNXModelHandler:
- New `change_model_path_to_dir` method. Currently, there are two different places where this logic is implemented manually. In onnx conversion, it doesn't update the model_file_name which leads to warning when resolving the onnx model file path 
ExtractAdapter:
-  `dynamic_lora_r`: Option to make the dimension for LoRA r static or dynamic.
- `optional_inputs`: Onnx and ort allow the same name to be used for graph initializers and inputs. When this happens, the input behaves like an optional input where the initializer is used if the input is not provided. https://github.com/onnx/onnx/blob/main/docs/IR.md#nodes 
Using this behavior, we can set the default initializer for the lora weights to be empty tensors with shapes `[in_dim, 0]` and `[0, out_dim]`. When the lora …
=> ExtractAdapters: `dynamic_lora_r` and `optional_inputs`

examples/llama2/llama2_multilora.ipynb, olive/cli/finetune.py, requirements-dev.txt, test/unit_test/cli/test_cli.py
Generate genai metadata only if ORT generate() API is used
=> Generate genai metadata only if ORT generate() API is used

examples/llama2/README.md, examples/opt_125m/README.md, examples/opt_125m/awq.json, examples/opt_125m/gptq.json, examples/opt_125m/gptq_onnx.json, examples/opt_125m/requirements-awq.txt, examples/opt_125m/requirements-gptq.txt, examples/opt_125m/requirements.txt, examples/phi3/README.md, examples/phi3/phi3.py, examples/phi3/phi3_template.json, olive/cli/finetune.py, olive/common/utils.py, olive/passes/pytorch/autoawq.py, olive/passes/pytorch/gptq.py, olive/passes/pytorch/merge_adapter_weights.py, test/unit_test/passes/pytorch/test_autoawq.py, test/unit_test/passes/pytorch/test_gptq.py
Follow up to #1337 
- GptqQuantizer now supports saving hf input model in hf model format.
- Fix for bugs related to `load_kwargs` that were introduced when dealing with `use_safetensors` in the previous PR. 
- Improvements to the readmes and example script.
- GPTQ option not added to phi3 example since the model type is not natively supported by auto-gptq and I was not able to make it work with config values for the model details. Will need further investigation if this support is needed.
=> GptqQuantizer: Option to save in hf format

olive/passes/onnx/model_builder.py
We currently try to infer the transformers cache from environment variables but those are not set most of the time. `transformers.utils` has a variable which handles this logic internally so we can just use that instead. 
Also added some exception handling to remove the intermediate files that the model builder adds to the cache dir. Ideally, the transformers cache and intermediate cache should be dealt separately in order to not pollute the transformers cache.
=> ModelBuilder: Use `TRANSFORMERS_CACHE` as `cache_dir`

olive/engine/engine.py, olive/passes/onnx/transformer_optimization.py
No need to have opt_level searchable in OrtTransformersOptimization pass
=> No need to have opt_level searchable in OrtTransformersOptimization pass

olive/passes/onnx/conversion.py
This PR adds the `dynamo=True` usage to leverage the improved dynamo exporter available since PyTorch 2.5. Since PyTorch 2.5 is not yet released, it also supports development/nightly builds of PyTorch.
=> Leverage the new `dynamo=True` API for PyTorch model export

olive/common/hf/mappings.py, olive/passes/pytorch/gptq.py
This is to avoid hardcoding these paramters in config files for models that aren't (like phi3) yet officially supported by auto-gptq.
- [ x Lint and apply fixes to your code by running `lintrunner -a`
=> Make certain gptq options customizable via model specific mapping

olive/cli/auto_opt.py, olive/cli/base.py, olive/cli/capture_onnx.py, olive/cli/finetune.py, olive/cli/generate_adapter.py, olive/cli/launcher.py, olive/cli/manage_aml_compute.py, olive/cli/perf_tuning.py, olive/cli/quantize.py, test/unit_test/cli/test_cli.py
Usage:
```bash
olive quantize                      \
--model_name_or_path <model-name> \
--trust_remote_code               \
--device <cpu|gpu|npu>            \
--algorithms <awq,gptq>           \
--data_name <data-name>           \
--subset <subset-name>            \
--split <split-name>              \
--batch_size <batch-size>         \
--output_path <output-dir>
```
=> Quantize: CLI command to quantize input model

README.md, docs/source/getstarted/installation.md, examples/README.md, olive/data/component/pre_process_data.py, olive/data/template.py, olive/engine/footprint.py, olive/workflows/run/run.py
Config can list any number of passes, but the ones that are actually run are the ones listed in pass_flows. This avoids the case where a pass may not be able to successfully be initialized which shouldn't matter because its not going to be run unless it is explicitly called out in the pass_flows.
=> Restrict initialization of passes to what's called out in pass_flows

docs/source/features/lora.md, olive/cli/export_adapters.py, olive/passes/onnx/conversion.py, olive/passes/onnx/extract_adapters.py, test/unit_test/passes/onnx/test_extract_adapters.py
Remove the `pack_weights` option from the `ExtractAdapters` pass. It is not used and requires lora specific information (lora target modules) to do the packing. Also makes the logic unnecessarily complicated.
 
=> ExtractAdapters: remove `pack_weights` option

olive/cli/auto_opt.py, olive/cli/export_adapters.py
Cleanup auto-opt options. 
No need to present excluded_passes option to the users. 
Disable session parameter tuning for this command.
=> Cleanup auto-opt options

olive/cli/base.py, olive/cli/quantize.py, olive/workflows/run/config.py, test/unit_test/cli/test_base.py, test/unit_test/cli/test_cli.py
Supported algorithms include bnb4, MatMul4, nvmo, dynamic onnx
and dynamic INC.
NOTE: Static quantization is not yet supported.
=> Add support to quantize onnx models

docs/source/api/passes.rst, docs/source/conf.py, examples/llama2/requirements-qlora.txt, olive/cli/quantize.py, olive/common/hf/quant.py, olive/olive_config.json, olive/passes/onnx/extract_adapters.py, olive/passes/onnx/mnb_to_qdq.py, olive/passes/onnx/onnx_dag.py, test/unit_test/cli/test_cli.py, test/unit_test/passes/onnx/test_mnb_to_qdq.py
- Onnxruntime originally only support sub-4bit quantization using the `MatMulNBits` contrib operator. But int4/uint4 are now officially supported by onnx using the standard QDQ operators and is used by EPs such as DirectML and QNN.
- This pass converts a MatMulNBits node into a sequence of `DequantizeLinear`->`Transpose`(optional)->`MatMul` nodes. This way, existing quantization tools don't need to be modified to export in QDQ format.
- Updated the `quantize` CLI to use QDQ encoding by default. There is an option to use `MatMulNBits` if they pefer.
New `MatMulNBitsToQDQ` pass to convert `MatMulNBits` to `DQ->MatMul`.
=> MatMulNBitsToQDQ: Pass to convert MatMulNBits contrib op to standard QDQ

olive/common/hf/mappings.py, olive/model/config/model_config.py, olive/passes/pytorch/autoawq.py, olive/passes/pytorch/gptq.py, olive/passes/pytorch/lora.py
**LoRA**
- `phi3` is not in the `peft` model type mapping https://github.com/huggingface/peft/blob/431c0e2d5ca56fa512dc4c96876c4145bb538f62/src/peft/utils/constants.py#L85 so user needs to provide the `target_modules` manually. 
- Added mapping for the additional model types.
**GPTQ/AWQ**
- Use the original adapter path if present instead of copying the adapter to the new output directory
- This way it is general and can support non-local adapters as well. In the cache, it doesn't matter if the one of the resources points to an existing resource as long as we don't modify the resource contents.
adapter copy fix for gptq and awq passes.
=> LoRA: phi3 target_modules mapping, GPTQ/AWQ: keep original adapters

examples/llama2/llama2_multilora.ipynb, olive/cli/capture_onnx.py, olive/cli/finetune.py, olive/cli/generate_adapter.py, olive/passes/onnx/conversion.py
- `generate-adapter` command only accepts ONNX model as input. The finetuned pytorch model must be converted to ONNX beforehand.
- Currently, only `capture-onnx-graph` path has been validated. Some checks and validations for `auto-opt` path are in progress.
- Update `capture-onnx-graph` to correctly handle genai metadata only mode and fp16 models.
=> CLI: `generate-adapter` only accepts ONNX model

olive/passes/onnx/common.py, olive/passes/onnx/extract_adapters.py, olive/passes/onnx/inc_quantization.py, olive/passes/onnx/mnb_to_qdq.py, olive/passes/onnx/quantization.py, olive/passes/onnx/vitis_ai_quantization.py, test/unit_test/passes/onnx/test_common.py, test/unit_test/passes/onnx/test_extract_adapters.py
If a model has unmerged adapters, we expect it to be used for MultiLoRA where the lora adapters can be switched. Quantization techniques that require calibration change the base weights as well as adapter weights together so we cannot just switch these quantized adapters. 
More work/research is needed to make a fully quantized model work with multi lora so we will skip any quantization that might break adapter switching.
=> Skip quantization that require calibration if model has adapters

examples/bert/requirements.txt, test/requirements-test.txt
- 4.46.0 is not compatible with python 3.8 even though it officially supports the python version. 
- Pin the test requirements until the issue is fixed or we move our CI to python 3.9+
https://github.com/huggingface/transformers/issues/34370
=> CI: Pin transformers<4.46.0

olive/cli/auto_opt.py, olive/cli/base.py, olive/hardware/constants.py, olive/olive_config.json, olive/passes/pass_config.py, test/unit_test/hardware/test_accelerator.py
* Implement providers, accelerators and precisions for pass in olive_config.json.
Each pass module config now also requires listing supported providers, accelerators
and precisions.
* Update auto-opt cli to use a pre-defined order of passes when search is disabled.
The list of passes is selected based on the user's choice of precision for
the output model.
=> Update olive_config and auto-opt to use precision, providers and accelerators

examples/test/local/test_llama2.py
Use `openlm-research/open_llama_7b_v2` instead of `meta-llama/Llama-2-7b-hf` since the meta-llama model is gated and requires login. We don't have login secrets on fork builds but still want to test this example. 
 
=> CI: Use open_llama model in llama2 test

.azure_pipelines/job_templates/olive-test-template.yaml
PublishCodeCoverageResults@1 is deprecated and produces lots of warning in the run page.
=> CI: Use PublishCodeCoverageResults@2

olive/cli/auto_opt.py
The pass and MB aren't compatible.
Fixes: #1460
=> Issue #1460: Don't run transformer optimizer pass when using MB

olive/cli/auto_opt.py, olive/cli/base.py, olive/olive_config.json, olive/passes/onnx/extract_adapters.py, olive/passes/onnx/float32_conversion.py, olive/passes/onnx/transformer_optimization.py, olive/passes/pytorch/capture_split_info.py
- Add new options to enable model splitting in `auto-opt` command. Only used for no-search model since model evaluation for split model is undefined.
Some other rule changes:
- Add `--use_qdq_encoding` option to make this optional
- Remove pytorch and model splitting passes when input model is onnx model
- Remove optimizer and matmul4 passes when model builder is used since the model is already optimized and in the expected precision
- Keep/remove passes that are only needed for specific EPs.
- Onnx conversion is always in fp32 since fp16 conversion doesn't work for all models. We instead use the transformers optimizer pass to do the conversion to fp16 afterwards.
Fixes #1464
=> `auto-opt`: Add model splitting options, Update no-search rules

olive/cli/auto_opt.py, olive/cli/base.py, olive/engine/engine.py, olive/hardware/accelerator.py, olive/passes/pytorch/capture_split_info.py, olive/systems/accelerator_creator.py, olive/systems/common.py, test/unit_test/hardware/test_accelerator.py, test/unit_test/passes/onnx/test_split_model.py, test/unit_test/passes/pytorch/test_capture_split_info.py, test/unit_test/systems/azureml/test_alias_system.py
- Expose `memory` in `AcceleratorSpec` and `AcceleratorConfig`.
- Removed the unused fields in accelerator spec to avoid confusion.
- CaptureSplitInfo pass now uses this field instead of a config parameter.
=> Expose accelerator memory and use in `CaptureSplitInfo`

examples/test/azureml/test_llama2.py, examples/test/local/test_llama2.py, olive/cli/auto_opt.py, olive/cli/capture_onnx.py, olive/passes/onnx/extract_adapters.py
- Use ONNX adapter format as the default format
- Provide --use_ort_genai option to generate genai config via auto-opt CLI
- Correct the fp16 parameter in transformers optimizer config from `use_fp16` to `float16`
=> auto-opt: `--use_ort_genai` option, fix fp16 transformers optimizer

olive/common/hf/utils.py, test/unit_test/common/test_hf.py
The default value for `use_exllama` in transformers is `True`. However, exllama model cannot be loaded on cpu (for model export) and doesn't have a backward pass implemented for finetuning. 
Since the main use for gptq quantized model in Olive is for export and finetuning, we should disable `use_exllama` by default. User can provide `use_exllama=True` as part of the loading args if they want to enable exllama for inference, etc.
=> HfModel: Disable `use_exllama` by default for GPTQ models

olive/common/hf/quant.py, olive/passes/onnx/mnb_to_qdq.py, test/unit_test/passes/onnx/test_mnb_to_qdq.py
- `use_int4` parameter added to use `INT4` elem type instead of `UINT4`. Quantized data is converted to int4 by first casting from uint8 to int8 and then subtracting 8.
- We expect INT4 to only be used for symmetric quantized models but it appears to work fine for assymetric quantized models so there is no restriction on it.
- `add_zero_point` parameter to force adding zero points to the DQ node even though they are all zeros.
- If the number of K-blocks is 1, we assume it to be per-axis quantization and create the DQ node as such:
- no `block_size` attribute
- scales and zero points are 1-D
- `axis` is opposite that of block-wise quantization
=> MatMulNBitsToQDQ: Support `INT4` elem type, per-axis quantization

docs/source/api/passes.rst, docs/source/features/passes/onnx.md, docs/source/overview/options.md, examples/bert/bert_qat_customized_train_loop_cpu.json, olive/cli/auto_opt.py, olive/olive_config.json, olive/passes/onnx/peephole_optimizer.py, test/unit_test/passes/onnx/test_peephole_optimizer.py
OnnxModelOptimizer:
- Rename pass to `OnnxPeepholeOptimizer`
- Cleaned up the logic to separate the different optimizer steps inside it.
- Added a comment to migrate this Pass to OnnxDAG or onnx-rewriter eventually since these are all node pattern matching and replacement steps
- Handle failed shape inference in argmax patch step. There is nothing we can do if the shape inference fails. Try to make do with the original model and skip nodes if there is no elem type info.
auto-opt:
- Fix a bug where the workflow config provided to `_get_passes_config` did not have the input model information
 
=> OnnxModelOptimizer: Rename to OnnxPeepholeOptimizer, handle failed shape inference

olive/passes/pytorch/autoawq.py
In transformers>4.43 which is required for models such as llama-3.1 and phi-3.5, there is an open issue related to device mismatch in the rotary embedding module https://github.com/huggingface/transformers/issues/32420
There is no fix yet in either transformers or autoawq so we patch the model adapter in Olive based on the package versions. This unblocks quantization using newer transformers version for llama like models. Fix is based on https://github.com/casper-hansen/AutoAWQ/pull/630
AutoGPTQ has the same issue but is already fixed in main so users can install from source. Also there is no straigtforward way to do a similar patch with it. Tried adding `model.rotary_embed` to `outside_layer_modules` but it fails with `get_device` since the module has no parameters.
=> AWQ: Patch for mismatched devices in RotaryEmbedding

olive/passes/onnx/conversion.py
For the Olive release, in the ONNX export pass, since when `dynamo=True` the dynamic_shapes argument is not provided properly, we temporarily change the check to require torch 2.6 to enable the new `dynamo=True` logic pass. This way when a user has torch 2.5 Olive will still use the old `dynamo_export` logic and function without errors.
- https://github.com/microsoft/Olive/issues/1478
=> Set to use `dynamo=True` only with PyTorch 2.6 temporarily

olive/cli/quantize.py
`static` quantization is not supported by cli now. Removing `static` key from template. Otherwise, cli doc will have this option.
=> Remove static key from quantize cli

.azure_pipelines/olive-examples.yaml, examples/bert/bert_inc_smoothquant_ptq_cpu.json, examples/bert/requirements.txt, examples/bert/user_script.py, examples/test/local/test_bert_inc.py, olive/passes/pytorch/quantization_aware_training.py, olive/workflows/run/config.py
Fix Olive bugs & Add Bert inc examples to example pipeline.
- `batch_size` is needed for Inc dataloader. Set default size to 1.
- Custom eval func doesn't have batch_size as input.
- For `QuantizationAwareTraining` pass, `train_data_config` is not required if user provides `training_loop_func`.
- Latest transformers package will automatically save trained model as safetensors format. Add `save_safetensors` as false to train argument.
- Some passes may have nested data_config in its config. Update auto-fill data_config logic to achieve this.
=> Fix several bugs & add Bert inc example to pipeline

olive/cli/base.py, olive/cli/capture_onnx.py, olive/cli/finetune.py, olive/cli/generate_adapter.py, olive/cli/quantize.py, olive/common/utils.py, olive/workflows/run/config.py
CLI:
- For command arguments like `task`, `adapter_path`, and `trust_remote_code`, use `getattr` to avoid `AttributeError` in case the handler type is not supported. 
- Add assertions in the commands to ensure the expected model handler type is provided
utils:
- `get_attr` logs a debug message instead of a warning message. This util is used to find optional submodules so we should not log as warning.
workflow.run:
- default passes to an empty dict. Otherwise, some other code tries to use dict methods on None.
 
=> CLI: Use getattr on conditional args, Check handler type. Debug log in `get_attr`

olive/passes/onnx/split.py, test/requirements-test.txt, test/unit_test/passes/onnx/test_split_model.py
Static quantized models have graphs of the pattern `input -> Q -> DQ -> op -> Q -> DQ -> ...`.  To be compatible with QNN Ep, the `DQ -> op -> Q` operators need stay in the same split.
SplitModel pass updated to handle this correctly:
- Q is assigned to the same split as the parent node.
- DQ is copied an assigned to the split of all child nodes.
- Some logic updates to generalize the assignment code.
 
=> SplitModel: Keep QDQ nodes together

examples/getting_started/olive-awq-ft-llama.ipynb
This example notebook demonstrates how to do the following tasks with the Olive CLI:
- AWQ 
- Fine-tuning
- Auto Optimizer
The notebook shows how to consume the model with the Generate API, and how to use the adapter to compare the results.
=> Add a notebook example of AWQ->FT->AutoOpt

docs/source/how-to/cli/cli-finetune.md
Fixed typo in fine-tune (CLI) doc, which resolves #1531
=> fixed typo in finetuning doc

docs/source/how-to/configure-workflows/model-opt-and-transform/onnx.md
Add `onnxscript` and `onnxoptimizer` optimize API details to the document.
=> Update OnnxPeepholeOptimizer pass doc

pyproject.toml
Disable checks for modules that use the same names as Python standard-library modules.
=> Disable ruff warning "stdlib-module-shadowing"

olive/engine/engine.py, olive/olive_config.json, olive/package_config.py, olive/passes/olive_pass.py, olive/passes/onnx/inc_quantization.py, olive/passes/onnx/optimum_merging.py, olive/passes/onnx/session_params_tuning.py, olive/passes/onnx/vitis_ai_quantization.py, olive/passes/pass_config.py, olive/workflows/run/config.py, olive/workflows/run/run.py, pyproject.toml
This prevents loading the module pre-emptively even when it isn't intended to be used. Also, after module gets imported, set the variable back on the class so rest of the implementation doesn't get impacted.
TODO: Pass::run_on_target should be removed but code paths in tests circumvent loading the olive package config. Follow up change to implement pass search will fix the issue.
=> Move module class variables from implementation to olive_config.json

olive/strategy/utils.py, pyproject.toml
Previous implementation returned vertices in reverse order even when there are no dependencies in the graph. Iterate the vertices in reverse order so input order can be retained.
=> Fix graph vertex ordering during topological ordering

olive/passes/__init__.py, olive/passes/olive_pass.py, olive/passes/pass_config.py, olive/workflows/run/config.py, pyproject.toml
Move AbstractPassConfig into pass_config.py and rename PassConfigBase to BasePassConfig.
=> Consolidate pass configs

olive/olive_config.json, olive/passes/onnx/graph_surgeries.py
- Add pass to olive_config.json
- Resolve the output path, otherwise, it uses the original path which is a directory. We need to create a .onnx filename inside it. Came across a permissions issue on Windows with the directory path.
- Expose external data config like other onnx passes.
=> GraphSurgeries: Add pass to olive_config.json, Resolve output_model_path

olive/engine/engine.py
=> Fix: Use correct cache directory for file logging

olive/passes/onnx/quantization.py
`quant_preprocess` was originally set to `False` by default because I thought it might not be compatible with QNN EP. However, it is needed for most models for the quantization to work properly:
- The quantizer needs a shape inferred model to quantize some tensors.
- Model quality is bad if constants are not made into initializers (see #1552).
=> OnnxStaticQuantization: Remove `quant_preprocess=False` default for qnn ep

olive/cli/auto_opt.py, olive/cli/base.py, olive/cli/capture_onnx.py, olive/cli/finetune.py, olive/cli/generate_adapter.py, olive/cli/quantize.py, olive/cli/session_params_tuning.py
Add generate_config_file option to cli.
=> Add generate_config_file option to cli

test/integ_test/aml_model_test/test_aml_model.py, test/unit_test/passes/onnx/test_nvmo_quantization.py, test/unit_test/systems/isolated_ort/test_isolated_ort_system.py
- Fix some tests.
- Update test failure reason.
=> Fix some tests

docs/source/how-to/configure-workflows/pass/quantization-pytorch.md, docs/source/reference/pass.rst, olive/olive_config.json, olive/passes/pytorch/lora.py, olive/passes/pytorch/rotate.py, olive/passes/pytorch/sgdg.py, olive/passes/pytorch/train_utils.py, test/unit_test/passes/pytorch/test_rotate.py
Add a new pass do weight rotation using SpinQuant. 
- Similar to QuaRot, this pass also only performs offline weight rotation.
- The concept is similar to QuaRot but the rotation weights are trained on a calibration dataset to improve activation quantization quality. 
- Only per_token and per_tensor activation quantization are supported. Groupwise quatization is not supported yet since we don't expect it to be used in subsequent QDQ models.
- Common training utils have been abstracted from the lora passes.
=> Add SpinQuant pass

olive/cli/quantize.py, olive/passes/pytorch/autoawq.py, olive/passes/pytorch/gptq.py, test/unit_test/passes/pytorch/test_gptq.py
Use wikitest train dataset by default for `GPTQQuantizer`. It uses 2048 as the sequence length.
=> GPTQ: Default wikitest calibration dataset

olive/cli/base.py
Provide `--use_chat_template` option in the CLI to use the default chat template instead of text_template or text_field.
=> CLI: Expose chat template in data options

olive/engine/engine.py, olive/search/samplers/optuna_sampler.py, olive/search/samplers/random_sampler.py, olive/search/samplers/search_sampler.py, olive/search/samplers/sequential_sampler.py, olive/search/search_results.py, olive/search/search_strategy.py, test/unit_test/search/samplers/test_tpe_sampler.py, test/unit_test/search/test_search_results.py, test/unit_test/search/test_search_strategy.py
Olive allows multiple passes under the "passes" key in config where each entry can have dictate its own evaluator config i.e. the evaluation config to use for that specific pass. However, with pass search, this becomes an issue because each pass within the group can dictate conflicting objectives and goals. Circumventing the issue by collecting all the objectives across the group with the last one in the list winning if named the same. Also, handle the case where not all objectives are generated as part of the
post evaluation signal.
=> Resolving objectives issue introduced with introduction of pass search

docs/source/how-to/configure-workflows/onnx-graph-surgeon.md, olive/passes/onnx/graph_surgeries.py, olive/passes/onnx/onnx_dag.py, test/unit_test/passes/onnx/test_graph_surgeries.py
New graph surgeon to simplify RMSNorm subgraph using L2Norm subgraph.
`rmsnorm = x/sqrt(mean(x**2)) = x/sqrt(1/N*sum(x**2)) = sqrt(N)*x/sqrt(sum(x**2)) = sqrt(N)*L2Norm`
This is useful when quantizing the model for NPU since there are fewer activations to quantize.
=> Add `RMSNormToL2Norm` graph surgeon

docs/source/reference/options.md, docs/source/reference/pass.rst, olive/olive_config.json, olive/passes/pytorch/lora.py, test/unit_test/passes/pytorch/test_lora.py
- Add DoRA pass.
- Add DoRA unit test.
- Add DoRA example.
- Update documents.
=> Add DoRA pass

olive/olive_config.json
Fix AutoAWQQuantizer GptqQuantizer supported ep and device.
=> Fix AutoAWQQuantizer GptqQuantizer supported ep and device

olive/passes/onnx/dynamic_to_fixed_shape.py, test/unit_test/passes/onnx/test_dynamic_to_fixed_shape.py
- `onnxruntime.tools.onnx_model_utils.fix_output_shapes` cannot handle large models (#1595), so we use the ort shape infer helper and handle the logic ourselves. This also means it can now handle models with contrib operators too.
- allow passing 0 as dim_value. this case is possible when creating a prompt processing model from a dynamic shaped llm where we want to make the past kv cache empty.
=> DynamicToFixedShape: use ort shape infer tool, accept 0 as dim_value

examples/test/local/test_bert_ptq_cpu.py, test/unit_test/passes/onnx/test_graph_surgeries.py
Some tests have been flaky recently:
- bert_ptq_cpu: Remove latency goal since the optimized onnx model is not always faster than the torch model on CI. The latest torch might be faster than it used to be.
- test_rmsnorm_to_l2norm: Increase the tolerance on all close check. The tolerance is not met for some random data but the graph is correct.
=> CI: fix flaky tests

olive/passes/onnx/mnb_to_qdq.py, test/unit_test/passes/onnx/test_mnb_to_qdq.py
Add an option to give a list of nodes to exclude from the operator conversion. This is useful when the model is already fully WOQ using matmul4quantizer but we want to keep some nodes like the lmheads as `MatMulNBits`.
=> MatMulNBitsToQDQ: add `nodes_to_exclude` option

olive/data/component/pre_process_data.py, olive/data/component/text_generation.py
- filter out empty text during huggingface data preprocessing
- Set default padding side in text-gen data preprocessing to left. Previously, we just used the default padding side of the tokenizer which is left for llms like llama/phi. However, right padding is more useful since it is commonly used during finetuning + GQA operator also assumes right padding.
- The padding side is only relevant for line-by-line strategy with padding enabled.
=> Hf preprocess: filter empty text, default text-gen `padding_side=right`

olive/passes/onnx/mnb_to_qdq.py
- #1613 was merged before #1567 so some code was still using the old dictionary logic.
- Not caught by CI since the unit tests jobs pin ort to 1.19.2 which skipped the tests.
Fixes #1625
=> MatMulNBitsToQDQ: Fix `nodes_to_exclude` access

.azure_pipelines/olive-ci.yaml
onnxruntime version was originally pinned due to incompatibilities with some pass dependencies. These tests were skipped with version check in #1554 but the CI yaml was not updated.
=> CI: Use latest stable ort in unit tests

.azure_pipelines/dockerfiles/linux-cpu.dockerfile, .azure_pipelines/dockerfiles/linux-gpu.dockerfile, .azure_pipelines/scripts/run_test.sh
- The docker image uses system python with older version setuptools. The GPU CI pipeline started failing due to mismatch between the required setuptools and install version. The installed setuptools cannot be upgrade using pip since it's a system package.
- Use venv which is separate from the system python environment.
- Upgrade setuptools
- Note: If pip is upgraded also, autoawq installation fails. It cannot find torch for some reason although it is already installed. Not sure what the cause is. If needed, we could instead use conda instead of venv in the future.
=> CI: Use venv in docker

olive/passes/onnx/conversion.py, test/unit_test/passes/onnx/test_conversion.py
Sorry! Follow up #1639, found a bug from the benchmark that makes regression on static shapes.
When it was static shape (io_config.dynamic_shapes is None), `_validate_dynamic_shapes` returned only one value, which crashed the benchmark with static shapes.
=> [dynamo exporter] Fix a bug in dynamic_shapes related processing that makes regression on the benchmark

examples/adetailer/face_yolo_qnn.json, olive/common/ort_inference.py, olive/passes/onnx/quantization.py, test/unit_test/passes/onnx/test_quantization.py
- Only support onnxruntime 1.18+ so that we don't have to maintain conditional logic for older versions.
- Simplify the config parameter descriptions. Just point to the ort tool file since it's hard to maintain the long descriptions that might become outdated.
- Expose `calibration_providers` option introduced in version 1.21
- Add a new option `op_types_to_exclude`. ort quantizer tool doesn't have this option but the effect can be achieved by excluding all nodes of the desired op types.
- Removed `append_first_op_types_to_quantize_list` which is not used at all and is confusing. The same effect can be achieved by using `get_qnn_qdq_config` or `get_qdq_config`. `get_qdq_config` support will be added later as we work on the other NPU providers.
=> OnnxQuantization: Update to latest ort

test/unit_test/passes/onnx/test_mnb_to_qdq.py
This test has become flaky recently and is not rasing the expected assertion error. Decreasing the tolerance.
=> CI: Fix flaky `test_mnb_to_qdq`

examples/whisper/test_transcription.py, olive/common/utils.py, olive/data/component/dataloader.py, olive/data/container/data_container.py, olive/evaluator/olive_evaluator.py, olive/logging.py, olive/passes/onnx/quantization.py, olive/systems/isolated_ort/isolated_ort_system.py, test/unit_test/data_container/test_dataloader.py, test/unit_test/passes/onnx/test_model_builder.py, test/unit_test/passes/pytorch/test_rotate.py, test/unit_test/utils.py
- Augment the data loader for llms with kv cache and other missing inputs.
- This augmentation is only done for quantization calibration dataloader for now since it requires model specific information. If needed, we could generalize this to the regular dataloader.
- There are two cases:
- Models with GQA: kv cache with empty tensors provided. This assumes that GQA nodes won't be calibrated.
- Models without GQA: Each sample leads to two calibration samples. first one with dummy single past length kv cache. second one with the present outputs from the model run. This way the calibration data sees real world kv cache data.
=> LLM Augmented data loader

olive/auto_optimizer/__init__.py, olive/constants.py, olive/evaluator/olive_evaluator.py, olive/passes/pass_config.py, test/unit_test/evaluator/test_olive_evaluator.py
Also, fix spelling/grammar in function name.
=> Move Precision enum declaration to global space

olive/passes/onnx/conversion.py, test/unit_test/passes/onnx/test_conversion.py
- Re-enable torch export test that was skipped during the pipeline migration
- Dynamo export test skip on Windows. Not sure why it fails. We can investigate later if the issue is present with torch 2.7 + torch.export.export.
- Change the quant model export test to use a gptq quantized model. 
- Exporting bnb quantized model is not used anymore. Loading bnb quant model is broken in the version of transformers used in our CI (4.44.2) so it is not worth keeping.
=> UT: Re-enable onnx conversion test, update quant model test

.azure_pipelines/job_templates/olive-example-linux-template.yaml, .azure_pipelines/job_templates/olive-example-win-template.yaml, .azure_pipelines/job_templates/olive-test-linux-gpu-template.yaml, .azure_pipelines/olive-ci.yaml, .azure_pipelines/olive-examples.yaml, .azure_pipelines/olive-ort-nightly.yaml
Forks build have issues after the migration to docker.
- Use mcr images since dockerhub is rate limiting. Use cuda 12.4 instead of 12.6 image since mcr doesn't have a mirror for 12.6 image yet.
- Remove `HF_TOKEN` env from pipeline yamls so it's not used and is a pipeline secret unavailable to fork builds.
=> CI: Enable fork builds

docs/source/reference/pass.rst, olive/olive_config.json, olive/passes/onnx/common.py, olive/passes/onnx/context_binary.py, test/unit_test/passes/onnx/test_context_binary.py
New pass `EPContextBinaryGenerator` added to generate context binary onnx models for NPU EPs.
- Only tested with QNN Execution Provider currently
- The options and behaviors for other EPs are expected to be the same. New eps will be enabled once validated.
- Accepts:
- single onnx model
- composite onnx model
- with/without weight sharing. Spill fill buffer not supported yet (only works on linux + needs extra model processing)
- special handling for static llm models through the `llm_pipeline` model attribute passed down between passes
=> EPContextBinaryGenerator: Pass to create EP specific context binary onnx models

docs/source/features/peft-adapters.md, docs/source/how-to/cli/cli-quantize.md, docs/source/how-to/index.rst, olive/passes/onnx/conversion.py, olive/passes/pytorch/autoawq.py, olive/passes/pytorch/gptq.py, test/requirements-test-gpu.txt, test/requirements-test.txt, test/unit_test/passes/onnx/test_split_model.py, test/unit_test/passes/pytorch/test_gptq.py
- Update `GptqQuantizer` with a patch to support newer versions of transformers.
- we previously asked users to install auto-gptq from source but that is inconvenient.
- new patch avoids the issue with the rotary embedding module not being on the expected device
- 0.7.1 validated for transformers 4.42-4.49
- `AutoAWQQuantizer`:
- 0.2.8 validated 4.43-4.47 (although package req is 4.45-4.47)
- Test requirements
- remove transformers version pin
- pin auto-gptq and autoawq versions
- remove transformercompression installation since the slicegpt test is skipped and it has `datasets` dependency conflict with autoawq
- Some doc fixes
=> GPTQ: latest transformers support, CI: unpin transformers version

docs/source/reference/pass.rst, olive/olive_config.json, olive/passes/onnx/common.py, olive/passes/onnx/compose.py, olive/passes/onnx/context_binary.py, olive/passes/onnx/onnx_dag.py, test/unit_test/passes/onnx/test_compose.py
New pass `ComposeOnnxModels` added to compose split onnx models. This is useful in cases where a large model is split into components for processing such as context binary generation, quantization, etc due to resource or compiler limitations.
It handles both regular composite models and llm pipeline models with/without context binaries.
Also fixes #1605
=> ComposeOnnxModels: Pass to compose split onnx models

olive/cli/quantize.py
Use int8 as the default precision in quantize CLI
=> Use int8 as default precision in quantize CLI

olive/common/hf/model_io.py, test/unit_test/common/test_hf.py
Based on the task and `use_cache` load kwargs, there are four scenairos for text gen models:
- `text-generation-with-past`
- `use_cache = True`: kv cache inputs, kv cache outputs
- `use_cache = False`: kv cache inputs
- `test-generation`
- `use_cache = True`: kv cache outputs
- `use_cache = False`: None
=> HfModel: fix kv cache io for no past and no cache

docs/source/features/onnx-transformations.md, examples/phi3_5/README.md, examples/phi3_5/phi3_5_config.json, examples/phi3_5/requirements.txt, examples/utils/generator.py, olive/data/component/dataloader.py, olive/olive_config.json, olive/passes/onnx/common.py, olive/passes/onnx/context_binary.py, olive/passes/onnx/graph_surgeries.py, olive/passes/onnx/model_builder.py, olive/passes/onnx/onnx_dag.py, olive/passes/onnx/split.py, olive/passes/pytorch/capture_split_info.py, olive/systems/accelerator_creator.py, pyproject.toml, test/unit_test/data_container/test_dataloader.py, test/unit_test/passes/onnx/test_context_binary.py, test/unit_test/passes/onnx/test_graph_surgeries.py, test/unit_test/passes/pytorch/test_capture_split_info.py
New example for preparing llm for NPU. The example uses `phi-3.5-mini-instruct` but the model path can be replaced with other models such as llama, phi-4, qwen2 and deepseek distilled models.
Changes made to enable this:
- New graph surgeries to remove rope multi cache and attention graph to make the quantization simpler.
- New graph surgery to convert (Skip)SimplifiedLayerNormalization nodes to L2Norm subgraph so it can run on NPU.
- Clean up context binary generator logic by removing the tempdir which is not necessary.
- Replace `exclude_embeds` and `exclude_lm_head` options in `CaptureSplitInfo` pass with `unique_embeds_lm_head_splits` which assigns the embedding layer and lm head layers to their own splits.
- Fixed a bug in the accelerator creator where it allowed a workflow to run …
=> Phi3.5 example for NPU

olive/__init__.py, setup.py
- Update dev version to 0.9.0dev0
- Updated python in package metadata to 3.10-3.11. Most dependencies like onnxruntime don't support 3.8 and 3.9 which are too old now.
=> Update dev version, python metadata

olive/cli/auto_opt.py, olive/passes/onnx/peephole_optimizer.py
- `onnxscript` optimizer in peephole optimizer fails with shape/type inference failure if the model has contrib ops. Run again with shape inference turned off in such cases to apply other optimizations.
- `auto-opt`: Run peephole optimizer right after onnx conversion
Fixes #1692
=> OnnxPeepholeOptimizer: Catch shape inference failure, run right after conversion in auto-opt

docs/source/examples.md, examples/sentence_transformers/eval_stsb.py, examples/sentence_transformers/readme.md, examples/sentence_transformers/sentence_transformer_config.json
Add Sentence Transformer (https://huggingface.co/sentence-transformers/all-MiniLM-L6-v2) QNN example.
Original model on CPU:
{
"Pearson Correlation": 0.8274,
"Spearman Correlation": 0.8203,
"latency-avg": 0.1457s
}
Quantized model on NPU:
{
"Pearson Correlation": 0.8272,
"Spearman Correlation": 0.8198,
"latency-avg": 0.0289s
}
=> Add Sentence Transformer QNN example

olive/systems/accelerator_creator.py, test/unit_test/hardware/test_accelerator.py
- Update the behavior of the accelerator normalizer to choose cpu and cpu-ep as the default accelerator if the target accelerator is not specified.
- CPU EP is the default EP used when creating an ort session. It is also the most generic EP.
- Otherwise, the workflow cycles through all EPs installed in the target system. This behavior might have been desirable when multi-ep and automatic accelerator+model selection was the focus but it's not anymore. This behavior is confusing and requires the user to install the correct ort package in the target system.
=> Default accelerator is cpu is not specified

examples/bge/bge-small-en-v1.5_ptq_qnn.json, examples/llama2/llama2_template.json, examples/phi3_5/config.json, examples/resnet/resnet_ptq_qnn.json, examples/sentence_transformers/sentence_transformer_config.json, examples/table_transformer_detection/ttd_config.json, examples/vit/vit_qnn_config.json, olive/passes/onnx/quantization.py, test/unit_test/passes/onnx/test_quantization.py, test/unit_test/search/samplers/test_tpe_sampler.py
- Static quantization now uses `get_qdq_config` by default in order to get a fully quantized qdq model.
- get_qnn_qdq_config is used instead if the target EP is QNN EP. So, the pass is now not EP agnositic.
- Required ort 1.21+ for eps other than QNN.
- `prepare_qnn_config` and `qnn_extra_options` options have been replaced with `prepare_qdq_config`. This option can be set to False if the old behavior of only quantizing some operators is desired. 
- The names for exposed extra options have been updated to match the qdq config params. Don't expect backward compatibility issues since we did not use them much before. But I expected the activation/weight symmetric options to be used more going forward so it's better to standardize the names.
- WeightSymmetric -> weight_symmetric
- …
=> Quantization: Prepare qdq config, new quantization parameters

examples/utils/generator.py, olive/common/hf/quant.py
Bugfix in quantized model export. Bias weight was not set correctly before.
=> GPTQ/AWQ: set bias correctly during export

README.md, examples/deepseek/README.md, examples/llama3/README.md, examples/phi3_5/README.md, examples/phi3_5/config.json, examples/qwen2_5/README.md, olive/common/hf/wrapper.py, olive/model/handler/composite.py, olive/passes/olive_pass.py, olive/passes/onnx/common.py, olive/passes/onnx/compose.py, olive/passes/onnx/context_binary.py, olive/passes/onnx/graph_surgeries.py, olive/passes/onnx/optimum_conversion.py, olive/passes/onnx/optimum_merging.py, olive/passes/onnx/split.py, olive/passes/onnx/static_llm.py, olive/passes/pytorch/rotate.py, test/unit_test/passes/onnx/test_compose.py, test/unit_test/passes/onnx/test_context_binary.py, test/unit_test/passes/onnx/test_static_llm.py
Fixes and updates:
- `CompositeModelHandler` now has an optional `model_path` resource to store additional files. In practice, most of the composite models that are output of passes use the same directory for the component models. 
- Abstracted out the common llm-pipeline logic from the passes. It also automatically updates the genai config with the correct model io and session options.
- Fixed untie word embedding implementation in hf model wrapper.
- Fixed the data type of the layernorm weight in the rms norm graph surgeries. In numpy 2.0+, the data type after multiplication with `sqrt_n` gets promoted to double. but we want float.
- Additional files carry over now supports composite models as well. Removed unnecessary check for input model dir. It was a remnant from the original …
=> Create genai_config for NPU llms, inference example

olive/common/hf/quant.py, olive/passes/pytorch/tensor_parallel_layers.py, test/unit_test/passes/onnx/test_conversion.py
The ability to create onnx ops directly with the new `torch.export` api is added in the latest torch-nightly (https://pytorch.org/docs/main/onnx_ops.html#torch.onnx.ops.symbolic). This PR updates the two places where `symbolic` is used for the modules to be compatible with the new `torch.onnx.export(..., dynamo=True)` API.
=> [export] Use torch.onnx.ops to implement symbolic ops

olive/model/handler/hf.py
Same fix as #1682. When the dummy inputs is a single tensor, `if dummy_inputs` is ambiguous and leads to an error. Check for `not None` instead.
=> HfModelHandler: fix condition for no dummy inputs

olive/passes/onnx/common.py, test/unit_test/passes/onnx/test_common.py
`resave_model` has a bug where the model after saving had zero length since the `raw_data` field was still present with `b""` and it unintentionally triggered this code path in `onnx.save_model` https://github.com/onnx/onnx/blob/1854a08c9daab2666b1dc0096afe3930659fcff1/onnx/external_data_helper.py#L326.
Fixed by clearing `raw_data` field after the external data file is renamed.
Fixes #1722
=> Fix resave_model bug

olive/passes/onnx/onnxscript_fusion.py
`ort_fusion` had an internal bug that has been fixed in https://github.com/microsoft/onnxscript/pull/2159. Olive needs to align with the new return values.
=> [exporter] Align to ort_fusion updates

examples/bert/bert_ptq_qdq_vitis_ai.json, examples/bert/google_bert_qdq_vitis_ai.json, examples/clip/laion_CLIP-ViT-B-32-laion2B-s34B-b79K_ptq_qdq_vitis_ai.json, examples/clip/openai_clip-vit-base-patch16_ptq_qdq_vitis_ai.json, examples/clip/openai_clip-vit-base-patch32_ptq_qdq_vitis_ai.json, examples/phi3_5/qdq_config_vitis_ai.json, examples/vit/vit_qdq_vitis_ai.json, olive/passes/onnx/transformer_optimization.py
Adds recipes for
- Intel BERT
- Google BERT
- OpenAI Clip (16 and 32)
- Laion Clip
- Google VIT
- Phi3.5
contributor: VishalX https://github.com/VishalX/Olive/tree/vitis_ai_recipes
=> [VitisAI] Add QDQ recipes for VitisAI EP

olive/evaluator/lmeval_onnx_model.py
=> Fix lmeval evaluator logic to handle context length larger than max length

.azure_pipelines/job_templates/olive-test-cpu-template.yaml, examples/directml/llm/requirements.txt, examples/directml/stable_diffusion_xl/requirements-common.txt, examples/directml/stable_diffusion_xl/stable_diffusion_xl.py, examples/llama2/requirements.txt, examples/stable_diffusion/requirements-common.txt, examples/stable_diffusion/stable_diffusion.py, olive/systems/python_environment/common_requirements.txt, requirements.txt, test/requirements-test.txt
ONNX 1.18 is starting to require protobuf >4 (https://github.com/onnx/onnx/blob/e82b8a37c3251d0d66f695130a3e311d951ede62/requirements.txt#L2). Remove protobuf from requirements because we get it from onnx.
=> Remove limitation on protobuf version

olive/passes/onnx/graph_surgeries.py
Use ONNX IR in graph surgeries to replace some proto manipulation. This PR adds a `call_ir` in the base class that is called when `__call__` is not overriden. This way the changes can be incremental and compatible with existing usages of the `Surgeon` class.
Refactoring:
- Renamed the Surgeon class that operates on proto to ProtoSurgeon to make the intention clear. Developers can subclass ProtoSurgeon to operate on proto and subclass Surgion to transform graphs directly with IR.
=> Use ONNX IR in graph surgeries

docs/source/features/huggingface-integration.md, docs/source/features/ihv-integration/openvino.md, docs/source/reference/options.md, docs/source/reference/pass.rst, olive/olive_config.json, olive/passes/openvino/encapsulation.py, olive/passes/openvino/io_update.py, olive/passes/openvino/optimum_intel.py, olive/passes/openvino/quantization.py, test/requirements-test.txt, test/unit_test/passes/openvino/test_openvino_optimum_conversion.py, test/unit_test/utils.py
The changes in this PR are for creating an optimum Intel® pass for converting a Huggingface Model to an OpenVINO model, along with the ability to perform weight compression or quantization if necessary.
The aim is to add in the functionality offered by the [optimum-cli export openvino](https://huggingface.co/docs/optimum/main/en/intel/openvino/export) command within Olive.
The changes include the addition of a new pass, unit tests for the pass, a few updates to the other OpenVINO passes, and updates to the documentation files as well.
=> Add optimum Intel® pass for converting a Huggingface Model to an OpenVINO Model

pyproject.toml
Currently in CI the pytest errors return full functions in the error stack, which I think is overly verbose and not readable. I updated the ini options taken from https://github.com/microsoft/onnxscript/blob/main/pyproject.toml to make the pytest errors more readable.
=> Update pytest config for readability

olive/passes/onnx/common.py, olive/passes/onnx/onnxscript_fusion.py
Implement ir_model_to_olive_model for improved ONNX IR support. Users can now use the function directly to create an Olive model from an ir.Model without having to go through onnx protobuf methods.
=> Implement ir_model_to_olive_model

examples/clip/laion_CLIP-ViT-B-32-laion2B-s34B-b79K_ptq_qnn_qdq.json, examples/clip/laion_CLIP-ViT-B-32-laion2B-s34B-b79K_ptq_qnn_qdq_ctx.json, examples/clip/openai_clip-vit-base-patch16_ptq_qnn_qdq.json, examples/clip/openai_clip-vit-base-patch16_ptq_qnn_qdq_ctx.json, examples/clip/openai_clip-vit-base-patch32_ptq_qnn_qdq.json, examples/clip/openai_clip-vit-base-patch32_ptq_qnn_qdq_ctx.json, olive/passes/onnx/graph_surgeries.py, test/unit_test/passes/onnx/test_graph_surgeries.py
- Attention mask surgery is generalized to all tensors. 
- Some filters on the consumer type to avoid checking large weights
- clip models can now quantize all ops without accuracy issues
=> QNN: Attention mask surgery for more tensors, Clip example update

olive/passes/pytorch/lora.py, olive/passes/pytorch/train_utils.py, test/unit_test/passes/pytorch/test_lora.py
- Compatibility with transformers 4.51 by replacing `evaluation_strategy` with `eval_strategy`. `eval_strategy` was added and preferred since 4.41. 
- Only make `paged_adamw_32bit` the default optimizer for QLoRA/LoftQ passes since it's part of the bitsandbytes package.
=> LoRA/QLoRA: `evaluation_strategy` -> `eval_strategy`, Default `paged_adamw_32bit` optim only for QLoRA

olive/cli/base.py, olive/cli/quantize.py, olive/passes/onnx/conversion.py, olive/workflows/run/config.py
1. Print CLI output model save path (not sure why this was removed before).
2. Add `input_cols` option to dataset for cli for text-classification task.
3. Update error message when missing dataset, otherwise it will say the precision is not supported.
4. Save `hf_task` to `model_attributes` from Conversion pass, this will be used for later pass.
5. Correct model name and task for dataset config when input model is `onnxmodel`.
=> Allow cli to take capture-onnx-graph output model

olive/evaluator/lmeval_onnx_model.py, olive/evaluator/olive_evaluator.py
Device isn't used for generative ONNX model so set it to None and be ignored. Setup search options (to pass down max_length) for GenAI generator.
=> Handle device and search options for lm evaluator

olive/passes/pytorch/gptq.py, olive/passes/pytorch/rotate.py
- QuaRot: The model was loaded with `torch_dtype=None` which loads the model in `float32` precision. Most hf models are originally saved in `bfloat16` or `float16` precision. Use `torch_dtype="auto"` if the model handler doesn't provide, to keep the model in its original precision.
- GPTQ: Remove unused user script pass params that were part of dataloader option that was replaced with data config before.
=> QuaRot: Keep model in original precision

docs/source/extending/index.rst, docs/source/features/quantization.md, docs/source/how-to/cli/cli-quantize.md, docs/source/how-to/index.rst, olive/cli/quantize.py, olive/olive_config.json
Add hqq to quantize cli & update docs. Quantize cli works with `olive quantize --algorithm hqq --precision int4 -m <model_name>`
=> Add hqq to quantize cli & update docs

.azure_pipelines/olive-ci.yaml
Disable Win integ test in pipeline. Re-enable this when the cluster is ready.
=> Disable Win integ test in pipeline

olive/common/ort_inference.py, olive/model/handler/mixin/onnx_ep.py, olive/model/handler/onnx.py, olive/passes/onnx/context_binary.py, olive/passes/onnx/optimum_merging.py, olive/systems/isolated_ort/inference_runner.py, test/unit_test/systems/isolated_ort/test_isolated_ort_system.py
=> Basic support for ONNX auto EP selection introduced in onnxruntime v1.22.0

examples/bert/README.md, examples/bert/bert_trtrtx_gpu.json, examples/bert/google_bert_trtrtx.json, examples/clip/README.md, examples/clip/laion_CLIP-ViT-B-32-laion2B-s34B-b79K_trtrtx.json, examples/clip/openai_clip-vit-base-patch16_trtrtx.json, examples/clip/openai_clip-vit-base-patch32_trtrtx.json, examples/vit/README.md, examples/vit/vit_trtrtx.json
All recipes use OnnxFloatToFloat16 pass to convert fp32 model to fp16. Confirmed that accuracy for all these models is same as original fp32 models.
=> Add Nvidia TensorRT-RTX Olive recipe for vit, clip and bert examples

.azure_pipelines/olive-ci.yaml, olive/common/ort_inference.py, olive/passes/onnx/context_binary.py, olive/passes/onnx/optimum_merging.py, olive/workflows/run/run.py, test/requirements-test-cpu.txt, test/requirements-test.txt
ORT WinML is ORTv1.22.0 + a few cherry picked PRs and so version check alone can't be used for auto registering the execution providers (required for auto ep selection feature in WinML).
=> Temporary patch for WinML support to auto register execution providers

olive/systems/accelerator_creator.py, test/unit_test/hardware/test_accelerator.py
Set default ep for devices if no ep specified. CPU -> CPUExecutionProvider. GPU -> CUDAExecutionProvider
=> Set default ep for devices if no ep specified

.azure_pipelines/job_templates/olive-example-win-template.yaml, .azure_pipelines/olive-ci.yaml
Remove ort version pin as ort-genai has released new version. It is compatible with onnxruntime 1.22.0 now.
=> Remove ort version pin

test/unit_test/passes/onnx/test_onnxscript_fusion.py, test/unit_test/passes/onnx/test_quantization.py
- Skip matmul4bits quantizer tests that require neural-compressor. neural compressor calls `wmic` in a subprocess but this executable is not available in newer windows versions.
- onnxscript fusion test fails on windows because of export failure.
=> Skip windows incompatible tests

olive/cli/quantize.py
- We have multiple examples doing w8a16 static quantization. Exposing this option in the quantize cli
=> quantize: expose act precision

olive/cli/base.py, olive/engine/packaging/packaging_config.py, olive/model/handler/hf.py, olive/model/handler/pytorch.py, olive/passes/pytorch/common.py, test/unit_test/cli/test_base.py, test/unit_test/cli/test_cli.py
Remove "generative" flag from input_model and "is_generative" command line option.
Check GenerationConfig to see if HF model is generative or not.
=> Remove "generative" flag from input_model and "is_generative" command line option

README.md, docs/source/getting-started/getting-started.md, examples/getting_started/olive_quickstart.ipynb, examples/opt_125m/requirements.txt, examples/phi3/requirements-awq.txt, examples/phi3/requirements-nvmo-awq.txt, test/integ_test/aml_model_test/conda.yaml
- transformers pin to 4.44.2 is not required anymore
- autoawq now supports newer transformers versions as well
- this resolved dependabot issues due to security risks with old packages
=> Remove torch and transformers version pins

olive/model/handler/mixin/hf.py
- In transformers 4.52+, when trying to load tokenizer from a directory with no tokenizer files, it raises `TypeError` instead of `OSError`
=> Hf: Catch type error in tokenizer save

olive/common/ort_inference.py, olive/model/handler/mixin/onnx_ep.py, olive/passes/onnx/context_binary.py, olive/passes/onnx/optimum_merging.py, test/unit_test/model/test_onnx_model.py
Olive doesn't explicitly support AutoEP features but WinML does. ORT v1.22+ requires EPs to be pre-registered and use alternative API to query for supported EPs. Branching the logic based on version instead to keep things independent of package releases that embed Olive as a dependent module.
=> Rollback WinML specific changes and make the logic depend on ORT version

examples/phi3_5/README.md
Pin the onnxruntime-genai version for NPU llm examples to 0.7.1. There are some issues (such as #1912) with 0.8.x releases which need more investigation. 
Fixes #1912
=> Phi3.5: pin ort-genai to 0.7.1

olive/passes/onnx/onnx_dag.py
When composing split models, there are some DequantizeLinear nodes that are duplicated between splits to maintain QDQ structure. This causes failure due to duplicate value info when composing split models.
=> OnnxDAG: Allow duplicate vi addition

olive/cli/quantize.py, olive/constants.py, olive/passes/onnx/quantization.py
Fix quantize CLI bits issue. precision bit map was deleted in https://github.com/microsoft/Olive/pull/1808. Add precision bit map back and make the precision definition different from bits.
https://github.com/microsoft/Olive/issues/1942
=> Fix quantize CLI bits issue

olive/model/config/model_config.py
Fix input model cache issue by including model_path in the hash calculation, to handle cases where multiple config files share the same model script.
https://github.com/microsoft/Olive/issues/1936
=> Fix input model cache issue

test/unit_test/passes/pytorch/test_lora.py, test/unit_test/passes/pytorch/test_sparsegpt.py, test/unit_test/passes/pytorch/test_torch_trt_conversion.py, test/unit_test/utils.py
`ptb_text_only` dataset uses a script to generate the data. `datasets>=4.0.0` doesn't support that anymore.
=> UT: Replace ptb_text_only with wikitext dataset

olive/common/ort_inference.py
We observed that when connecting remotely to a device with a GPU, the `ort.get_ep_devices()` function returns duplicate GPU EP devices.
Execute the following code.
```
import onnxruntime as ort
ep_devices = ort.get_ep_devices()
for ep_device in ep_devices:
print(f"{id(ep_device.device)} {ep_device.ep_name} {ep_device.device.type} {ep_device.device.device_id} {ep_device.device.vendor_id} {ep_device.device.vendor}")
```
The output contains duplicate GPU EP devices.
```
2157111435568 CPUExecutionProvider OrtHardwareDeviceType.CPU 0 32902 GenuineIntel
2157111435568 DmlExecutionProvider OrtHardwareDeviceType.GPU 9988 4318 NVIDIA
2157111435568 DmlExecutionProvider OrtHardwareDeviceType.GPU 9988 4318 NVIDIA
2157111435568 NvTensorRTRTXExecutionProvider OrtHardwareDeviceType.GPU 9988 4318 NVIDIA …
```
=> Fix "Provider xxx has already been registered."

olive/passes/onnx/add_metadata.py, olive/passes/onnx/common.py, test/unit_test/passes/onnx/test_add_metadata.py
Refactored the AddOliveMetadata ONNX pass to ensure all external data files (e.g., .bin, .xml) are preserved when adding metadata to ONNX models.
Key changes:
- Always copy entire input directory to output location to preserve all external files alongside the main ONNX model
- Simplified pass logic by treating all models as directory-based
- Load ONNX models without external data to preserve file structure
- Return directory-based ONNXModelHandler for consistent behavior
Added unit tests:
- test_add_metadata_with_external_data_files: Verifies external file preservation for directory-based models with mock .bin/.xml
- test_add_metadata_single_file_to_directory_conversion: Ensures correct metadata handling for single-file ONNX models
This fix addresses issues where external data files were …
=> Fix AddOliveMetadata pass to preserve external data files

olive/passes/onnx/rtn_quantization.py, test/unit_test/passes/onnx/test_rtn_quantization.py
Add is_symmetric support to OnnxBlockWiseRtnQuantization.
=> Add is_symmetric support to OnnxBlockWiseRtnQuantization

olive/passes/onnx/model_builder.py
- Currently, only "default" algo is picked up when running GenAI Model-Builder through Olive's Model-Builder pass.
- With this change, hooking up the int4-algo-config and int4-is-symmetric model-builder options in Olive's Model-Builder pass. 
- This should enable different quantization recipes through "Olive->GenAI-Model-Builder" workflow.
=> Support int4-is-symmetric and int4-algo-config extra-options in model-builder pass

examples/phi3_5/qnn_config.json, examples/phi3_5/qnn_docker.json, olive/passes/onnx/mnb_to_qdq.py
- `desc_act=True` is compatible with per-channel quantization since there is only one group. No need to worry about non-trivial `g_idx`. Emperically found to improve MMLU score for phi-3.5
- Updated data configs
- Fix bug in `MatMulNBitsToQDQ` where the incorrect input was taken as the bias. Was not caught since no model so far has used bias.
=> QNN: Use `desc_act` in gptq, MatMulNBitsToQDQ: Use correct bias input

olive/passes/pytorch/gptq.py
- Enable act-order scheme for per-channel cases (`group_size=-1`).
- Blockwise quantization with act-order requires g_idx. It is not compatible with QDQ. Supported my MatMulNBits but the kernel is not as efficient.
=> Gptq: Enable `desc_act` for per-channel quantization

docs/source/features/onnx-transformations.md, olive/passes/onnx/graph_surgeries.py, test/unit_test/passes/onnx/test_graph_surgeries.py
Unify the naming convention for graph surgery by using the combination of Decompose and contrib op names to identify lowering operations.
=> Rename QuickGeluToSigmoid to DecomposeQuickGelu

examples/phi3/qnn/phi3_mini_128k_instruct_qnn_config.json, examples/phi3/qnn/phi3_mini_4k_instruct_qnn_config.json, examples/phi3_5/README.md, examples/phi4/qnn/phi4_mini_instruct_qnn_config.json, examples/qwen2_5/qnn/qwen_2.5_1.5b_instruct_qnn_config.json
Added gptqmodel pass for following llms:
1> Qwen 2.5 1.5b instruct
2> Phi3 mini 4k instruct
3> Phi3 mini 128k instruct
4> Phi4 mini instruct
=> Add GPTQModel pass for LLMs on QNN

olive/common/hf/model_io.py
Optimum 1.27.0 now registers the onnx export configs using a decorator. Need to import the relevant submodule to trigger the import.
=> Hf: Trigger registration of optimum onnx configs for model io

examples/clip/qnn/laion_CLIP-ViT-B-32-laion2B-s34B-b79K_ptq_qnn_fp32.json, examples/clip/qnn/laion_CLIP-ViT-B-32-laion2B-s34B-b79K_ptq_qnn_fp32_ctx.json, examples/clip/qnn/laion_CLIP-ViT-B-32-laion2B-s34B-b79K_ptq_qnn_qdq.json, examples/clip/qnn/laion_CLIP-ViT-B-32-laion2B-s34B-b79K_ptq_qnn_qdq_ctx.json, examples/clip/qnn/openai_clip-vit-base-patch16_ptq_qnn_fp32.json, examples/clip/qnn/openai_clip-vit-base-patch16_ptq_qnn_fp32_ctx.json, examples/clip/qnn/openai_clip-vit-base-patch16_ptq_qnn_qdq.json, examples/clip/qnn/openai_clip-vit-base-patch16_ptq_qnn_qdq_ctx.json, examples/clip/qnn/openai_clip-vit-base-patch32_ptq_qnn_fp32.json, examples/clip/qnn/openai_clip-vit-base-patch32_ptq_qnn_fp32_ctx.json, examples/clip/qnn/openai_clip-vit-base-patch32_ptq_qnn_qdq.json, examples/clip/qnn/openai_clip-vit-base-patch32_ptq_qnn_qdq_ctx.json
Updates to QNN clip olive example recipes for Accuracy and Performance improvement
- Increased number of samples used for quantization
- Updated ReplaceAttentionMaskValue to -50
- Removed disabling of MatMulAddFusion
- Added MatMulAddToGemm graph surgery
=> Updates to QNN clip olive example recipes

olive/olive_config.json, olive/passes/onnx/aimet_quantization.py, test/requirements-test-cpu.txt, test/unit_test/passes/onnx/test_aimet_quantization.py
Implements a new olive pass for quantizing with aimet-onnx.
=> Add aimet-onnx quantization pass

examples/phi3/README.md, olive/passes/onnx/nvmo_quantization.py
- Update NVMO pass to prepare input-shapes profile (min, max, opt) in case of NvTensorRtRtx EP.
=> [NVMO] Add Input-Shapes profiling option for NvTensorRtRtx EP

olive/common/ort_inference.py
=> Check for new EP API availability instead of version

examples/phi3_5/qnn_config.json, olive/data/component/dataloader.py
Using CalibStridedMinMax option in onnx quantization, only stride amount of data is used and all results are merged in the end during the calibration process. This helps in better managing mem usage.
=> Update CalibrationDataReader to support strided data for onnx quantization

olive/cli/quantize.py, olive/common/ort_inference.py
- Add the olive native `Gptq` pass as supported implementation in the `quantize` cli
- `maybe_register_ep_libraries`: skip registration if ort is not installed. This util is called everytime a system is created but onnxruntime is not always required. For instance, like when running only pytorch passes.
=> qauntize cli: Add gptq as supported implementation

olive/cli/base.py, olive/cli/capture_onnx.py, olive/cli/optimize.py, olive/passes/onnx/model_builder.py, test/passes/onnx/test_model_builder.py
Add extra_options to ModelBuilder pass
=> Add extra_options to ModelBuilder pass

olive/common/quant/hf_utils.py, olive/common/quant/linear.py, olive/evaluator/olive_evaluator.py, olive/passes/onnx/model_builder.py, olive/passes/pytorch/gptq.py, olive/passes/pytorch/selective_mixed_precision.py, test/passes/pytorch/test_gptq.py, test/passes/pytorch/test_selective_mixed_precision.py
- `Gptq` and olive quant checkpoint now supports lm_head quantization
- `SelectiveMixedPrecision` has a new heuristic called `k_quant_down` which is similar to `k_quant_mixed` but only takes the `down_proj` linears and `lm_head`.
- `QuantLinear` packing now doesn't do the gptq style -1 offset to the zero points while packing. This causes issues with asymmetric quantization when any zero point value is 0 as the values are expected to be unsigned int. It also now has a `from_tensor` method that can be used to create a new instance from already quantized weights.
=> Quantization: lm_head quantization, k_quant_down heuristic, No zero offset while packing

olive/passes/openvino/encapsulation.py
Adds capability in OV encapsulation pass to parse optional configs to use as override in the resulting genai_config.json
=> Add option to override genai_config.json property OV models
